/*
 * OpenAPI Example
 *
 * This is an  OpenAPI specification for Rest Countries API.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	restcountries "restcountries"
	"strings"

	"github.com/gin-gonic/gin"
)

type CountriesAPI struct {
	client *restcountries.APIClient
}

// Get /v3.1/all
// GET endpoint for retrieving all countries
func (api *CountriesAPI) GetAllCountries(c *gin.Context) {
	// Your handler implementation

	c.JSON(200, gin.H{"status": "OK"})
}

// Get /v3.1/capital/:capital
// Search by capital city name
func (api *CountriesAPI) GetCountryByCapital(c *gin.Context) {
	client_cfg := restcountries.NewConfiguration()
	client := restcountries.NewAPIClient(client_cfg)
	capital := c.Param("capital")
	client_helper := client.CountriesAPI.GetCountryByCapital(c, capital)
	fields := c.Query("fields")
	fieldsSlice := strings.Split(fields, ",")
	client1 := client_helper.Fields(fieldsSlice) // Set the fields query parameter if provided
	countries, _, err := client1.Execute()
	if err != nil {
		c.JSON(500, gin.H{"error": err.Error()})
		return
	}
	if len(countries) == 0 {
		c.JSON(404, gin.H{"error": "No countries found for the given capital"})
		return
	}
	c.JSON(200, countries)
}

// Get /v3.1/alpha/:code
// Search by country code. It can be the 2-letter or 3-letter code
func (api *CountriesAPI) GetCountryByCode(c *gin.Context) {
	client_cfg := restcountries.NewConfiguration()
	client := restcountries.NewAPIClient(client_cfg)
	code := c.Param("code")
	client_helper := client.CountriesAPI.GetCountryByCode(c, code)
	fields := c.Query("fields")
	fieldsSlice := strings.Split(fields, ",")
	client1 := client_helper.Fields(fieldsSlice) // Set the fields query parameter if provided
	countries, _, err := client1.Execute()
	if err != nil {
		c.JSON(500, gin.H{"error": err.Error()})
		return
	}
	if len(countries) == 0 {
		c.JSON(404, gin.H{"error": "No countries found for the given code"})
		return
	}
	c.JSON(200, countries)
}

// Get /v3.1/currency/:currency
// Search by currency code
func (api *CountriesAPI) GetCountryByCurrency(c *gin.Context) {
	client_cfg := restcountries.NewConfiguration()
	client := restcountries.NewAPIClient(client_cfg)
	currency := c.Param("currency")
	client_helper := client.CountriesAPI.GetCountryByCurrency(c, currency)
	fields := c.Query("fields")
	fieldsSlice := strings.Split(fields, ",")
	client1 := client_helper.Fields(fieldsSlice) // Set the fields query parameter if provided
	countries, _, err := client1.Execute()
	if err != nil {
		c.JSON(500, gin.H{"error": err.Error()})
		return
	}
	if len(countries) == 0 {
		c.JSON(404, gin.H{"error": "No countries found for the given currency"})
		return
	}
	c.JSON(200, countries)
}

// Get /v3.1/lang/:language
// Search by language code
func (api *CountriesAPI) GetCountryByLanguage(c *gin.Context) {
	// Your handler implementation
	client_cfg := restcountries.NewConfiguration()
	client := restcountries.NewAPIClient(client_cfg)
	language := c.Param("language")
	client_helper := client.CountriesAPI.GetCountryByLanguage(c, language)
	fields := c.Query("fields")
	fieldsSlice := strings.Split(fields, ",")
	client1 := client_helper.Fields(fieldsSlice) // Set the fields query parameter if provided
	countries, _, err := client1.Execute()
	if err != nil {
		c.JSON(500, gin.H{"error": err.Error()})
		return
	}
	if len(countries) == 0 {
		c.JSON(404, gin.H{"error": "No countries found for the given language"})
		return
	}
	c.JSON(200, countries)
}

// Get /v3.1/name/:name
// Search by country name. If you want to get an exact match, use the next endpoint. It can be the common or official value
func (api *CountriesAPI) GetCountryByName(c *gin.Context) {
	// Your handler implementation
	client_cfg := restcountries.NewConfiguration()
	client := restcountries.NewAPIClient(client_cfg)
	name := c.Param("name")
	client_helper := client.CountriesAPI.GetCountryByName(c, name)
	fields := c.Query("fields")
	fieldsSlice := strings.Split(fields, ",")
	client1 := client_helper.Fields(fieldsSlice) // Set the fields query parameter if provided
	countries, _, err := client1.Execute()
	if err != nil {
		c.JSON(500, gin.H{"error": err.Error()})
		return
	}
	if len(countries) == 0 {
		c.JSON(404, gin.H{"error": "No countries found for the given name"})
		return
	}
	c.JSON(200, countries)
}

// Get /v3.1/region/:region
// Search by region name
func (api *CountriesAPI) GetCountryByRegion(c *gin.Context) {
	// Your handler implementation
	client_cfg := restcountries.NewConfiguration()
	client := restcountries.NewAPIClient(client_cfg)
	region := c.Param("region")
	client_helper := client.CountriesAPI.GetCountryByRegion(c, region)
	fields := c.Query("fields")
	fieldsSlice := strings.Split(fields, ",")
	client1 := client_helper.Fields(fieldsSlice) // Set the fields query parameter if provided
	countries, _, err := client1.Execute()
	if err != nil {
		c.JSON(500, gin.H{"error": err.Error()})
		return
	}
	if len(countries) == 0 {
		c.JSON(404, gin.H{"error": "No countries found for the given region"})
		return
	}
	c.JSON(200, countries)

}

// Get /v3.1/subregion/:subregion
// Search by subregion name
func (api *CountriesAPI) GetCountryBySubregion(c *gin.Context) {
	client_cfg := restcountries.NewConfiguration()
	client := restcountries.NewAPIClient(client_cfg)
	subregion := c.Param("subregion")
	client_helper := client.CountriesAPI.GetCountryBySubregion(c, subregion)
	fields := c.Query("fields")
	fieldsSlice := strings.Split(fields, ",")
	client1 := client_helper.Fields(fieldsSlice) // Set the fields query parameter if provided
	countries, _, err := client1.Execute()
	if err != nil {
		c.JSON(500, gin.H{"error": err.Error()})
		return
	}
	if len(countries) == 0 {
		c.JSON(404, gin.H{"error": "No countries found for the given subregion"})
		return
	}
	c.JSON(200, countries)
}

// Get /v3.1/translation/:translation
// Search by translation name
func (api *CountriesAPI) GetCountryByTranslation(c *gin.Context) {
	client_cfg := restcountries.NewConfiguration()
	client := restcountries.NewAPIClient(client_cfg)
	translation := c.Param("translation")
	client_helper := client.CountriesAPI.GetCountryByTranslation(c, translation)
	fields := c.Query("fields")
	fieldsSlice := strings.Split(fields, ",")
	client1 := client_helper.Fields(fieldsSlice) // Set the fields query parameter if provided
	countries, _, err := client1.Execute()
	if err != nil {
		c.JSON(500, gin.H{"error": err.Error()})
		return
	}
	if len(countries) == 0 {
		c.JSON(404, gin.H{"error": "No countries found for the given subregion"})
		return
	}
	c.JSON(200, countries)
}

// Get /v3.1/independent
// Get independent countries
func (api *CountriesAPI) GetIndependentCountries(c *gin.Context) {
	// Your handler implementation
	client_cfg := restcountries.NewConfiguration()
	client := restcountries.NewAPIClient(client_cfg)
	client_helper := client.CountriesAPI.GetIndependentCountries(c)
	status := c.Query("status")
	if status == "true" {
		client_helper = client_helper.Status(true)
	} else {
		client_helper = client_helper.Status(false)
	}
	fields := c.Query("fields")
	fieldsSlice := strings.Split(fields, ",")
	client_helper = client_helper.Fields(fieldsSlice) // Set the fields query parameter if provided
	countries, _, err := client_helper.Execute()
	if err != nil {
		c.JSON(500, gin.H{"error": err.Error()})
		return
	}
	if len(countries) == 0 {
		c.JSON(404, gin.H{"error": "No countries found for the given subregion"})
		return
	}
	c.JSON(200, countries)
}
