/*
 * OpenAPI Example
 *
 * This is an  OpenAPI specification for Rest Countries API.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type NativeNameDetail struct {

	Official string `json:"official,omitempty"`

	Common string `json:"common,omitempty"`
}
