/*
 * OpenAPI Example
 *
 * This is an  OpenAPI specification for Rest Countries API.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type NameDetails struct {

	Common string `json:"common,omitempty"`

	Official string `json:"official,omitempty"`

	NativeName map[string]NativeNameDetail `json:"nativeName,omitempty"`
}
