/*
 * OpenAPI Example
 *
 * This is an  OpenAPI specification for Rest Countries API.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PostalCodeDetails struct {

	Format string `json:"format,omitempty"`

	Regex string `json:"regex,omitempty"`
}
