/*
 * OpenAPI Example
 *
 * This is an  OpenAPI specification for Rest Countries API.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type AllresponsebodyInner struct {

	Name NameDetails `json:"name,omitempty"`

	Tld []string `json:"tld,omitempty"`

	Cca2 string `json:"cca2,omitempty"`

	Cca3 string `json:"cca3,omitempty"`

	Ccn3 string `json:"ccn3,omitempty"`

	Cioc string `json:"cioc,omitempty"`

	Currencies map[string]CurrenciesDetails `json:"currencies,omitempty"`

	Region string `json:"region,omitempty"`

	Independent bool `json:"independent,omitempty"`

	UnMember bool `json:"unMember,omitempty"`

	Capital []string `json:"capital,omitempty"`

	Latlng []float32 `json:"latlng,omitempty"`

	Area float32 `json:"area,omitempty"`

	Population float32 `json:"population,omitempty"`

	Flags AllresponsebodyInnerFlags `json:"flags,omitempty"`

	Flag string `json:"flag,omitempty"`

	Landlocked bool `json:"landlocked,omitempty"`

	Borders []string `json:"borders,omitempty"`

	Translations map[string]NativeNameDetail `json:"translations,omitempty"`

	Demonyms map[string]DemonymsDetails `json:"demonyms,omitempty"`

	Timezones []string `json:"timezones,omitempty"`

	Continents []string `json:"continents,omitempty"`

	Fifa string `json:"fifa,omitempty"`

	Car CarDetails `json:"car,omitempty"`

	CoatOfArms ImageDetails `json:"coatOfArms,omitempty"`

	StartOfWeek string `json:"startOfWeek,omitempty"`

	CapitalInfo AllresponsebodyInnerCapitalInfo `json:"capitalInfo,omitempty"`

	Maps MapsDetails `json:"maps,omitempty"`

	Gini map[string]float32 `json:"gini,omitempty"`

	Status string `json:"status,omitempty"`

	Subregion string `json:"subregion,omitempty"`

	AltSpellings []string `json:"altSpellings,omitempty"`

	Idd IddDetails `json:"idd,omitempty"`

	PostalCode PostalCodeDetails `json:"postalCode,omitempty"`

	Languages map[string]string `json:"languages,omitempty"`
}
