/*
 * OpenAPI Example
 *
 * This is an  OpenAPI specification for Rest Countries API.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type CarDetails struct {

	Signs []string `json:"signs,omitempty"`

	Side string `json:"side,omitempty"`
}
