/*
 * OpenAPI Example
 *
 * This is an  OpenAPI specification for Rest Countries API.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// Route is the information for every URI.
type Route struct {
	// Name is the name of this Route.
	Name		string
	// Method is the string for the HTTP method. ex) GET, POST etc..
	Method		string
	// Pattern is the pattern of the URI.
	Pattern	 	string
	// HandlerFunc is the handler function of this route.
	HandlerFunc	gin.HandlerFunc
}

// NewRouter returns a new router.
func NewRouter(handleFunctions ApiHandleFunctions) *gin.Engine {
	return NewRouterWithGinEngine(gin.Default(), handleFunctions)
}

// NewRouter add routes to existing gin engine.
func NewRouterWithGinEngine(router *gin.Engine, handleFunctions ApiHandleFunctions) *gin.Engine {
	for _, route := range getRoutes(handleFunctions) {
		if route.HandlerFunc == nil {
			route.HandlerFunc = DefaultHandleFunc
		}
		switch route.Method {
		case http.MethodGet:
			router.GET(route.Pattern, route.HandlerFunc)
		case http.MethodPost:
			router.POST(route.Pattern, route.HandlerFunc)
		case http.MethodPut:
			router.PUT(route.Pattern, route.HandlerFunc)
		case http.MethodPatch:
			router.PATCH(route.Pattern, route.HandlerFunc)
		case http.MethodDelete:
			router.DELETE(route.Pattern, route.HandlerFunc)
		}
	}

	return router
}

// Default handler for not yet implemented routes
func DefaultHandleFunc(c *gin.Context) {
	c.String(http.StatusNotImplemented, "501 not implemented")
}

type ApiHandleFunctions struct {

	// Routes for the CountriesAPI part of the API
	CountriesAPI CountriesAPI
}

func getRoutes(handleFunctions ApiHandleFunctions) []Route {
	return []Route{ 
		{
			"GetAllCountries",
			http.MethodGet,
			"/v3.1/all",
			handleFunctions.CountriesAPI.GetAllCountries,
		},
		{
			"GetCountryByCapital",
			http.MethodGet,
			"/v3.1/capital/:capital",
			handleFunctions.CountriesAPI.GetCountryByCapital,
		},
		{
			"GetCountryByCode",
			http.MethodGet,
			"/v3.1/alpha/:code",
			handleFunctions.CountriesAPI.GetCountryByCode,
		},
		{
			"GetCountryByCurrency",
			http.MethodGet,
			"/v3.1/currency/:currency",
			handleFunctions.CountriesAPI.GetCountryByCurrency,
		},
		{
			"GetCountryByLanguage",
			http.MethodGet,
			"/v3.1/lang/:language",
			handleFunctions.CountriesAPI.GetCountryByLanguage,
		},
		{
			"GetCountryByName",
			http.MethodGet,
			"/v3.1/name/:name",
			handleFunctions.CountriesAPI.GetCountryByName,
		},
		{
			"GetCountryByRegion",
			http.MethodGet,
			"/v3.1/region/:region",
			handleFunctions.CountriesAPI.GetCountryByRegion,
		},
		{
			"GetCountryBySubregion",
			http.MethodGet,
			"/v3.1/subregion/:subregion",
			handleFunctions.CountriesAPI.GetCountryBySubregion,
		},
		{
			"GetCountryByTranslation",
			http.MethodGet,
			"/v3.1/translation/:translation",
			handleFunctions.CountriesAPI.GetCountryByTranslation,
		},
		{
			"GetIndependentCountries",
			http.MethodGet,
			"/v3.1/independent",
			handleFunctions.CountriesAPI.GetIndependentCountries,
		},
	}
}
