/*
REST Countries — Countries API (v5)

Read-only country data API. All endpoints are GET, JSON-only, and follow a JSON:API-like envelope: successful payloads sit under a top-level `data` key with `data.objects` (array of Country records) and `data.meta` (pagination block). Failures return an `errors` array of objects carrying a `message`. Authentication is a bearer API key. Spec written against https://restcountries.com/docs/countries (July 2026) and cross-checked against a live v5 record. 

API version: 5.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package restcountries

import (
	"encoding/json"
)

// checks if the Leader type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Leader{}

// Leader Premium field. Per docs each leader includes assets, attributes, links, name, and title; exact sub-shapes are x-unverified.
type Leader struct {
	Name *string `json:"name,omitempty"`
	Title *string `json:"title,omitempty"`
	Assets map[string]interface{} `json:"assets,omitempty"`
	Attributes map[string]interface{} `json:"attributes,omitempty"`
	Links map[string]interface{} `json:"links,omitempty"`
}

// NewLeader instantiates a new Leader object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLeader() *Leader {
	this := Leader{}
	return &this
}

// NewLeaderWithDefaults instantiates a new Leader object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLeaderWithDefaults() *Leader {
	this := Leader{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *Leader) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Leader) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *Leader) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *Leader) SetName(v string) {
	o.Name = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *Leader) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Leader) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *Leader) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *Leader) SetTitle(v string) {
	o.Title = &v
}

// GetAssets returns the Assets field value if set, zero value otherwise.
func (o *Leader) GetAssets() map[string]interface{} {
	if o == nil || IsNil(o.Assets) {
		var ret map[string]interface{}
		return ret
	}
	return o.Assets
}

// GetAssetsOk returns a tuple with the Assets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Leader) GetAssetsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Assets) {
		return map[string]interface{}{}, false
	}
	return o.Assets, true
}

// HasAssets returns a boolean if a field has been set.
func (o *Leader) HasAssets() bool {
	if o != nil && !IsNil(o.Assets) {
		return true
	}

	return false
}

// SetAssets gets a reference to the given map[string]interface{} and assigns it to the Assets field.
func (o *Leader) SetAssets(v map[string]interface{}) {
	o.Assets = v
}

// GetAttributes returns the Attributes field value if set, zero value otherwise.
func (o *Leader) GetAttributes() map[string]interface{} {
	if o == nil || IsNil(o.Attributes) {
		var ret map[string]interface{}
		return ret
	}
	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Leader) GetAttributesOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Attributes) {
		return map[string]interface{}{}, false
	}
	return o.Attributes, true
}

// HasAttributes returns a boolean if a field has been set.
func (o *Leader) HasAttributes() bool {
	if o != nil && !IsNil(o.Attributes) {
		return true
	}

	return false
}

// SetAttributes gets a reference to the given map[string]interface{} and assigns it to the Attributes field.
func (o *Leader) SetAttributes(v map[string]interface{}) {
	o.Attributes = v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *Leader) GetLinks() map[string]interface{} {
	if o == nil || IsNil(o.Links) {
		var ret map[string]interface{}
		return ret
	}
	return o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Leader) GetLinksOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Links) {
		return map[string]interface{}{}, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *Leader) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given map[string]interface{} and assigns it to the Links field.
func (o *Leader) SetLinks(v map[string]interface{}) {
	o.Links = v
}

func (o Leader) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Leader) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Assets) {
		toSerialize["assets"] = o.Assets
	}
	if !IsNil(o.Attributes) {
		toSerialize["attributes"] = o.Attributes
	}
	if !IsNil(o.Links) {
		toSerialize["links"] = o.Links
	}
	return toSerialize, nil
}

type NullableLeader struct {
	value *Leader
	isSet bool
}

func (v NullableLeader) Get() *Leader {
	return v.value
}

func (v *NullableLeader) Set(val *Leader) {
	v.value = val
	v.isSet = true
}

func (v NullableLeader) IsSet() bool {
	return v.isSet
}

func (v *NullableLeader) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLeader(val *Leader) *NullableLeader {
	return &NullableLeader{value: val, isSet: true}
}

func (v NullableLeader) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLeader) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


