/*
REST Countries — Countries API (v5)

Read-only country data API. All endpoints are GET, JSON-only, and follow a JSON:API-like envelope: successful payloads sit under a top-level `data` key with `data.objects` (array of Country records) and `data.meta` (pagination block). Failures return an `errors` array of objects carrying a `message`. Authentication is a bearer API key. Spec written against https://restcountries.com/docs/countries (July 2026) and cross-checked against a live v5 record. 

API version: 5.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package restcountries

import (
	"encoding/json"
)

// checks if the Demonym type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Demonym{}

// Demonym struct for Demonym
type Demonym struct {
	M *string `json:"m,omitempty"`
	F *string `json:"f,omitempty"`
}

// NewDemonym instantiates a new Demonym object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDemonym() *Demonym {
	this := Demonym{}
	return &this
}

// NewDemonymWithDefaults instantiates a new Demonym object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDemonymWithDefaults() *Demonym {
	this := Demonym{}
	return &this
}

// GetM returns the M field value if set, zero value otherwise.
func (o *Demonym) GetM() string {
	if o == nil || IsNil(o.M) {
		var ret string
		return ret
	}
	return *o.M
}

// GetMOk returns a tuple with the M field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Demonym) GetMOk() (*string, bool) {
	if o == nil || IsNil(o.M) {
		return nil, false
	}
	return o.M, true
}

// HasM returns a boolean if a field has been set.
func (o *Demonym) HasM() bool {
	if o != nil && !IsNil(o.M) {
		return true
	}

	return false
}

// SetM gets a reference to the given string and assigns it to the M field.
func (o *Demonym) SetM(v string) {
	o.M = &v
}

// GetF returns the F field value if set, zero value otherwise.
func (o *Demonym) GetF() string {
	if o == nil || IsNil(o.F) {
		var ret string
		return ret
	}
	return *o.F
}

// GetFOk returns a tuple with the F field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Demonym) GetFOk() (*string, bool) {
	if o == nil || IsNil(o.F) {
		return nil, false
	}
	return o.F, true
}

// HasF returns a boolean if a field has been set.
func (o *Demonym) HasF() bool {
	if o != nil && !IsNil(o.F) {
		return true
	}

	return false
}

// SetF gets a reference to the given string and assigns it to the F field.
func (o *Demonym) SetF(v string) {
	o.F = &v
}

func (o Demonym) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Demonym) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.M) {
		toSerialize["m"] = o.M
	}
	if !IsNil(o.F) {
		toSerialize["f"] = o.F
	}
	return toSerialize, nil
}

type NullableDemonym struct {
	value *Demonym
	isSet bool
}

func (v NullableDemonym) Get() *Demonym {
	return v.value
}

func (v *NullableDemonym) Set(val *Demonym) {
	v.value = val
	v.isSet = true
}

func (v NullableDemonym) IsSet() bool {
	return v.isSet
}

func (v *NullableDemonym) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDemonym(val *Demonym) *NullableDemonym {
	return &NullableDemonym{value: val, isSet: true}
}

func (v NullableDemonym) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDemonym) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


