/*
REST Countries — Countries API (v5)

Read-only country data API. All endpoints are GET, JSON-only, and follow a JSON:API-like envelope: successful payloads sit under a top-level `data` key with `data.objects` (array of Country records) and `data.meta` (pagination block). Failures return an `errors` array of objects carrying a `message`. Authentication is a bearer API key. Spec written against https://restcountries.com/docs/countries (July 2026) and cross-checked against a live v5 record. 

API version: 5.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package restcountries

import (
	"encoding/json"
)

// checks if the Memberships type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Memberships{}

// Memberships struct for Memberships
type Memberships struct {
	Un *bool `json:"un,omitempty"`
	Eu *bool `json:"eu,omitempty"`
	Eurozone *bool `json:"eurozone,omitempty"`
	Schengen *bool `json:"schengen,omitempty"`
	Nato *bool `json:"nato,omitempty"`
	Commonwealth *bool `json:"commonwealth,omitempty"`
	Oecd *bool `json:"oecd,omitempty"`
	G7 *bool `json:"g7,omitempty"`
	G20 *bool `json:"g20,omitempty"`
	Brics *bool `json:"brics,omitempty"`
	Opec *bool `json:"opec,omitempty"`
	AfricanUnion *bool `json:"african_union,omitempty"`
	Asean *bool `json:"asean,omitempty"`
	ArabLeague *bool `json:"arab_league,omitempty"`
}

// NewMemberships instantiates a new Memberships object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMemberships() *Memberships {
	this := Memberships{}
	return &this
}

// NewMembershipsWithDefaults instantiates a new Memberships object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMembershipsWithDefaults() *Memberships {
	this := Memberships{}
	return &this
}

// GetUn returns the Un field value if set, zero value otherwise.
func (o *Memberships) GetUn() bool {
	if o == nil || IsNil(o.Un) {
		var ret bool
		return ret
	}
	return *o.Un
}

// GetUnOk returns a tuple with the Un field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Memberships) GetUnOk() (*bool, bool) {
	if o == nil || IsNil(o.Un) {
		return nil, false
	}
	return o.Un, true
}

// HasUn returns a boolean if a field has been set.
func (o *Memberships) HasUn() bool {
	if o != nil && !IsNil(o.Un) {
		return true
	}

	return false
}

// SetUn gets a reference to the given bool and assigns it to the Un field.
func (o *Memberships) SetUn(v bool) {
	o.Un = &v
}

// GetEu returns the Eu field value if set, zero value otherwise.
func (o *Memberships) GetEu() bool {
	if o == nil || IsNil(o.Eu) {
		var ret bool
		return ret
	}
	return *o.Eu
}

// GetEuOk returns a tuple with the Eu field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Memberships) GetEuOk() (*bool, bool) {
	if o == nil || IsNil(o.Eu) {
		return nil, false
	}
	return o.Eu, true
}

// HasEu returns a boolean if a field has been set.
func (o *Memberships) HasEu() bool {
	if o != nil && !IsNil(o.Eu) {
		return true
	}

	return false
}

// SetEu gets a reference to the given bool and assigns it to the Eu field.
func (o *Memberships) SetEu(v bool) {
	o.Eu = &v
}

// GetEurozone returns the Eurozone field value if set, zero value otherwise.
func (o *Memberships) GetEurozone() bool {
	if o == nil || IsNil(o.Eurozone) {
		var ret bool
		return ret
	}
	return *o.Eurozone
}

// GetEurozoneOk returns a tuple with the Eurozone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Memberships) GetEurozoneOk() (*bool, bool) {
	if o == nil || IsNil(o.Eurozone) {
		return nil, false
	}
	return o.Eurozone, true
}

// HasEurozone returns a boolean if a field has been set.
func (o *Memberships) HasEurozone() bool {
	if o != nil && !IsNil(o.Eurozone) {
		return true
	}

	return false
}

// SetEurozone gets a reference to the given bool and assigns it to the Eurozone field.
func (o *Memberships) SetEurozone(v bool) {
	o.Eurozone = &v
}

// GetSchengen returns the Schengen field value if set, zero value otherwise.
func (o *Memberships) GetSchengen() bool {
	if o == nil || IsNil(o.Schengen) {
		var ret bool
		return ret
	}
	return *o.Schengen
}

// GetSchengenOk returns a tuple with the Schengen field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Memberships) GetSchengenOk() (*bool, bool) {
	if o == nil || IsNil(o.Schengen) {
		return nil, false
	}
	return o.Schengen, true
}

// HasSchengen returns a boolean if a field has been set.
func (o *Memberships) HasSchengen() bool {
	if o != nil && !IsNil(o.Schengen) {
		return true
	}

	return false
}

// SetSchengen gets a reference to the given bool and assigns it to the Schengen field.
func (o *Memberships) SetSchengen(v bool) {
	o.Schengen = &v
}

// GetNato returns the Nato field value if set, zero value otherwise.
func (o *Memberships) GetNato() bool {
	if o == nil || IsNil(o.Nato) {
		var ret bool
		return ret
	}
	return *o.Nato
}

// GetNatoOk returns a tuple with the Nato field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Memberships) GetNatoOk() (*bool, bool) {
	if o == nil || IsNil(o.Nato) {
		return nil, false
	}
	return o.Nato, true
}

// HasNato returns a boolean if a field has been set.
func (o *Memberships) HasNato() bool {
	if o != nil && !IsNil(o.Nato) {
		return true
	}

	return false
}

// SetNato gets a reference to the given bool and assigns it to the Nato field.
func (o *Memberships) SetNato(v bool) {
	o.Nato = &v
}

// GetCommonwealth returns the Commonwealth field value if set, zero value otherwise.
func (o *Memberships) GetCommonwealth() bool {
	if o == nil || IsNil(o.Commonwealth) {
		var ret bool
		return ret
	}
	return *o.Commonwealth
}

// GetCommonwealthOk returns a tuple with the Commonwealth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Memberships) GetCommonwealthOk() (*bool, bool) {
	if o == nil || IsNil(o.Commonwealth) {
		return nil, false
	}
	return o.Commonwealth, true
}

// HasCommonwealth returns a boolean if a field has been set.
func (o *Memberships) HasCommonwealth() bool {
	if o != nil && !IsNil(o.Commonwealth) {
		return true
	}

	return false
}

// SetCommonwealth gets a reference to the given bool and assigns it to the Commonwealth field.
func (o *Memberships) SetCommonwealth(v bool) {
	o.Commonwealth = &v
}

// GetOecd returns the Oecd field value if set, zero value otherwise.
func (o *Memberships) GetOecd() bool {
	if o == nil || IsNil(o.Oecd) {
		var ret bool
		return ret
	}
	return *o.Oecd
}

// GetOecdOk returns a tuple with the Oecd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Memberships) GetOecdOk() (*bool, bool) {
	if o == nil || IsNil(o.Oecd) {
		return nil, false
	}
	return o.Oecd, true
}

// HasOecd returns a boolean if a field has been set.
func (o *Memberships) HasOecd() bool {
	if o != nil && !IsNil(o.Oecd) {
		return true
	}

	return false
}

// SetOecd gets a reference to the given bool and assigns it to the Oecd field.
func (o *Memberships) SetOecd(v bool) {
	o.Oecd = &v
}

// GetG7 returns the G7 field value if set, zero value otherwise.
func (o *Memberships) GetG7() bool {
	if o == nil || IsNil(o.G7) {
		var ret bool
		return ret
	}
	return *o.G7
}

// GetG7Ok returns a tuple with the G7 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Memberships) GetG7Ok() (*bool, bool) {
	if o == nil || IsNil(o.G7) {
		return nil, false
	}
	return o.G7, true
}

// HasG7 returns a boolean if a field has been set.
func (o *Memberships) HasG7() bool {
	if o != nil && !IsNil(o.G7) {
		return true
	}

	return false
}

// SetG7 gets a reference to the given bool and assigns it to the G7 field.
func (o *Memberships) SetG7(v bool) {
	o.G7 = &v
}

// GetG20 returns the G20 field value if set, zero value otherwise.
func (o *Memberships) GetG20() bool {
	if o == nil || IsNil(o.G20) {
		var ret bool
		return ret
	}
	return *o.G20
}

// GetG20Ok returns a tuple with the G20 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Memberships) GetG20Ok() (*bool, bool) {
	if o == nil || IsNil(o.G20) {
		return nil, false
	}
	return o.G20, true
}

// HasG20 returns a boolean if a field has been set.
func (o *Memberships) HasG20() bool {
	if o != nil && !IsNil(o.G20) {
		return true
	}

	return false
}

// SetG20 gets a reference to the given bool and assigns it to the G20 field.
func (o *Memberships) SetG20(v bool) {
	o.G20 = &v
}

// GetBrics returns the Brics field value if set, zero value otherwise.
func (o *Memberships) GetBrics() bool {
	if o == nil || IsNil(o.Brics) {
		var ret bool
		return ret
	}
	return *o.Brics
}

// GetBricsOk returns a tuple with the Brics field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Memberships) GetBricsOk() (*bool, bool) {
	if o == nil || IsNil(o.Brics) {
		return nil, false
	}
	return o.Brics, true
}

// HasBrics returns a boolean if a field has been set.
func (o *Memberships) HasBrics() bool {
	if o != nil && !IsNil(o.Brics) {
		return true
	}

	return false
}

// SetBrics gets a reference to the given bool and assigns it to the Brics field.
func (o *Memberships) SetBrics(v bool) {
	o.Brics = &v
}

// GetOpec returns the Opec field value if set, zero value otherwise.
func (o *Memberships) GetOpec() bool {
	if o == nil || IsNil(o.Opec) {
		var ret bool
		return ret
	}
	return *o.Opec
}

// GetOpecOk returns a tuple with the Opec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Memberships) GetOpecOk() (*bool, bool) {
	if o == nil || IsNil(o.Opec) {
		return nil, false
	}
	return o.Opec, true
}

// HasOpec returns a boolean if a field has been set.
func (o *Memberships) HasOpec() bool {
	if o != nil && !IsNil(o.Opec) {
		return true
	}

	return false
}

// SetOpec gets a reference to the given bool and assigns it to the Opec field.
func (o *Memberships) SetOpec(v bool) {
	o.Opec = &v
}

// GetAfricanUnion returns the AfricanUnion field value if set, zero value otherwise.
func (o *Memberships) GetAfricanUnion() bool {
	if o == nil || IsNil(o.AfricanUnion) {
		var ret bool
		return ret
	}
	return *o.AfricanUnion
}

// GetAfricanUnionOk returns a tuple with the AfricanUnion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Memberships) GetAfricanUnionOk() (*bool, bool) {
	if o == nil || IsNil(o.AfricanUnion) {
		return nil, false
	}
	return o.AfricanUnion, true
}

// HasAfricanUnion returns a boolean if a field has been set.
func (o *Memberships) HasAfricanUnion() bool {
	if o != nil && !IsNil(o.AfricanUnion) {
		return true
	}

	return false
}

// SetAfricanUnion gets a reference to the given bool and assigns it to the AfricanUnion field.
func (o *Memberships) SetAfricanUnion(v bool) {
	o.AfricanUnion = &v
}

// GetAsean returns the Asean field value if set, zero value otherwise.
func (o *Memberships) GetAsean() bool {
	if o == nil || IsNil(o.Asean) {
		var ret bool
		return ret
	}
	return *o.Asean
}

// GetAseanOk returns a tuple with the Asean field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Memberships) GetAseanOk() (*bool, bool) {
	if o == nil || IsNil(o.Asean) {
		return nil, false
	}
	return o.Asean, true
}

// HasAsean returns a boolean if a field has been set.
func (o *Memberships) HasAsean() bool {
	if o != nil && !IsNil(o.Asean) {
		return true
	}

	return false
}

// SetAsean gets a reference to the given bool and assigns it to the Asean field.
func (o *Memberships) SetAsean(v bool) {
	o.Asean = &v
}

// GetArabLeague returns the ArabLeague field value if set, zero value otherwise.
func (o *Memberships) GetArabLeague() bool {
	if o == nil || IsNil(o.ArabLeague) {
		var ret bool
		return ret
	}
	return *o.ArabLeague
}

// GetArabLeagueOk returns a tuple with the ArabLeague field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Memberships) GetArabLeagueOk() (*bool, bool) {
	if o == nil || IsNil(o.ArabLeague) {
		return nil, false
	}
	return o.ArabLeague, true
}

// HasArabLeague returns a boolean if a field has been set.
func (o *Memberships) HasArabLeague() bool {
	if o != nil && !IsNil(o.ArabLeague) {
		return true
	}

	return false
}

// SetArabLeague gets a reference to the given bool and assigns it to the ArabLeague field.
func (o *Memberships) SetArabLeague(v bool) {
	o.ArabLeague = &v
}

func (o Memberships) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Memberships) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Un) {
		toSerialize["un"] = o.Un
	}
	if !IsNil(o.Eu) {
		toSerialize["eu"] = o.Eu
	}
	if !IsNil(o.Eurozone) {
		toSerialize["eurozone"] = o.Eurozone
	}
	if !IsNil(o.Schengen) {
		toSerialize["schengen"] = o.Schengen
	}
	if !IsNil(o.Nato) {
		toSerialize["nato"] = o.Nato
	}
	if !IsNil(o.Commonwealth) {
		toSerialize["commonwealth"] = o.Commonwealth
	}
	if !IsNil(o.Oecd) {
		toSerialize["oecd"] = o.Oecd
	}
	if !IsNil(o.G7) {
		toSerialize["g7"] = o.G7
	}
	if !IsNil(o.G20) {
		toSerialize["g20"] = o.G20
	}
	if !IsNil(o.Brics) {
		toSerialize["brics"] = o.Brics
	}
	if !IsNil(o.Opec) {
		toSerialize["opec"] = o.Opec
	}
	if !IsNil(o.AfricanUnion) {
		toSerialize["african_union"] = o.AfricanUnion
	}
	if !IsNil(o.Asean) {
		toSerialize["asean"] = o.Asean
	}
	if !IsNil(o.ArabLeague) {
		toSerialize["arab_league"] = o.ArabLeague
	}
	return toSerialize, nil
}

type NullableMemberships struct {
	value *Memberships
	isSet bool
}

func (v NullableMemberships) Get() *Memberships {
	return v.value
}

func (v *NullableMemberships) Set(val *Memberships) {
	v.value = val
	v.isSet = true
}

func (v NullableMemberships) IsSet() bool {
	return v.isSet
}

func (v *NullableMemberships) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMemberships(val *Memberships) *NullableMemberships {
	return &NullableMemberships{value: val, isSet: true}
}

func (v NullableMemberships) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMemberships) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


