/*
OpenAPI Example

This is an  OpenAPI specification for Rest Countries API.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CarDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CarDetails{}

// CarDetails struct for CarDetails
type CarDetails struct {
	Signs []string `json:"signs,omitempty"`
	Side *string `json:"side,omitempty"`
}

// NewCarDetails instantiates a new CarDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCarDetails() *CarDetails {
	this := CarDetails{}
	return &this
}

// NewCarDetailsWithDefaults instantiates a new CarDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCarDetailsWithDefaults() *CarDetails {
	this := CarDetails{}
	return &this
}

// GetSigns returns the Signs field value if set, zero value otherwise.
func (o *CarDetails) GetSigns() []string {
	if o == nil || IsNil(o.Signs) {
		var ret []string
		return ret
	}
	return o.Signs
}

// GetSignsOk returns a tuple with the Signs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CarDetails) GetSignsOk() ([]string, bool) {
	if o == nil || IsNil(o.Signs) {
		return nil, false
	}
	return o.Signs, true
}

// HasSigns returns a boolean if a field has been set.
func (o *CarDetails) HasSigns() bool {
	if o != nil && !IsNil(o.Signs) {
		return true
	}

	return false
}

// SetSigns gets a reference to the given []string and assigns it to the Signs field.
func (o *CarDetails) SetSigns(v []string) {
	o.Signs = v
}

// GetSide returns the Side field value if set, zero value otherwise.
func (o *CarDetails) GetSide() string {
	if o == nil || IsNil(o.Side) {
		var ret string
		return ret
	}
	return *o.Side
}

// GetSideOk returns a tuple with the Side field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CarDetails) GetSideOk() (*string, bool) {
	if o == nil || IsNil(o.Side) {
		return nil, false
	}
	return o.Side, true
}

// HasSide returns a boolean if a field has been set.
func (o *CarDetails) HasSide() bool {
	if o != nil && !IsNil(o.Side) {
		return true
	}

	return false
}

// SetSide gets a reference to the given string and assigns it to the Side field.
func (o *CarDetails) SetSide(v string) {
	o.Side = &v
}

func (o CarDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CarDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Signs) {
		toSerialize["signs"] = o.Signs
	}
	if !IsNil(o.Side) {
		toSerialize["side"] = o.Side
	}
	return toSerialize, nil
}

type NullableCarDetails struct {
	value *CarDetails
	isSet bool
}

func (v NullableCarDetails) Get() *CarDetails {
	return v.value
}

func (v *NullableCarDetails) Set(val *CarDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableCarDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableCarDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCarDetails(val *CarDetails) *NullableCarDetails {
	return &NullableCarDetails{value: val, isSet: true}
}

func (v NullableCarDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCarDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


