/*
REST Countries — Countries API (v5)

Read-only country data API. All endpoints are GET, JSON-only, and follow a JSON:API-like envelope: successful payloads sit under a top-level `data` key with `data.objects` (array of Country records) and `data.meta` (pagination block). Failures return an `errors` array of objects carrying a `message`. Authentication is a bearer API key. Spec written against https://restcountries.com/docs/countries (July 2026) and cross-checked against a live v5 record. 

API version: 5.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package restcountries

import (
	"encoding/json"
)

// checks if the Language type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Language{}

// Language struct for Language
type Language struct {
	// English name. Verified lookup path (languages.name).
	Name *string `json:"name,omitempty"`
	// x-unverified key name.
	NativeName *string `json:"native_name,omitempty"`
	// x-unverified key name.
	Bcp47 *string `json:"bcp_47,omitempty"`
	// x-unverified key name.
	Iso6391 *string `json:"iso_639_1,omitempty"`
	// x-unverified key name.
	Iso6393 *string `json:"iso_639_3,omitempty"`
}

// NewLanguage instantiates a new Language object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLanguage() *Language {
	this := Language{}
	return &this
}

// NewLanguageWithDefaults instantiates a new Language object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLanguageWithDefaults() *Language {
	this := Language{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *Language) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Language) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *Language) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *Language) SetName(v string) {
	o.Name = &v
}

// GetNativeName returns the NativeName field value if set, zero value otherwise.
func (o *Language) GetNativeName() string {
	if o == nil || IsNil(o.NativeName) {
		var ret string
		return ret
	}
	return *o.NativeName
}

// GetNativeNameOk returns a tuple with the NativeName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Language) GetNativeNameOk() (*string, bool) {
	if o == nil || IsNil(o.NativeName) {
		return nil, false
	}
	return o.NativeName, true
}

// HasNativeName returns a boolean if a field has been set.
func (o *Language) HasNativeName() bool {
	if o != nil && !IsNil(o.NativeName) {
		return true
	}

	return false
}

// SetNativeName gets a reference to the given string and assigns it to the NativeName field.
func (o *Language) SetNativeName(v string) {
	o.NativeName = &v
}

// GetBcp47 returns the Bcp47 field value if set, zero value otherwise.
func (o *Language) GetBcp47() string {
	if o == nil || IsNil(o.Bcp47) {
		var ret string
		return ret
	}
	return *o.Bcp47
}

// GetBcp47Ok returns a tuple with the Bcp47 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Language) GetBcp47Ok() (*string, bool) {
	if o == nil || IsNil(o.Bcp47) {
		return nil, false
	}
	return o.Bcp47, true
}

// HasBcp47 returns a boolean if a field has been set.
func (o *Language) HasBcp47() bool {
	if o != nil && !IsNil(o.Bcp47) {
		return true
	}

	return false
}

// SetBcp47 gets a reference to the given string and assigns it to the Bcp47 field.
func (o *Language) SetBcp47(v string) {
	o.Bcp47 = &v
}

// GetIso6391 returns the Iso6391 field value if set, zero value otherwise.
func (o *Language) GetIso6391() string {
	if o == nil || IsNil(o.Iso6391) {
		var ret string
		return ret
	}
	return *o.Iso6391
}

// GetIso6391Ok returns a tuple with the Iso6391 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Language) GetIso6391Ok() (*string, bool) {
	if o == nil || IsNil(o.Iso6391) {
		return nil, false
	}
	return o.Iso6391, true
}

// HasIso6391 returns a boolean if a field has been set.
func (o *Language) HasIso6391() bool {
	if o != nil && !IsNil(o.Iso6391) {
		return true
	}

	return false
}

// SetIso6391 gets a reference to the given string and assigns it to the Iso6391 field.
func (o *Language) SetIso6391(v string) {
	o.Iso6391 = &v
}

// GetIso6393 returns the Iso6393 field value if set, zero value otherwise.
func (o *Language) GetIso6393() string {
	if o == nil || IsNil(o.Iso6393) {
		var ret string
		return ret
	}
	return *o.Iso6393
}

// GetIso6393Ok returns a tuple with the Iso6393 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Language) GetIso6393Ok() (*string, bool) {
	if o == nil || IsNil(o.Iso6393) {
		return nil, false
	}
	return o.Iso6393, true
}

// HasIso6393 returns a boolean if a field has been set.
func (o *Language) HasIso6393() bool {
	if o != nil && !IsNil(o.Iso6393) {
		return true
	}

	return false
}

// SetIso6393 gets a reference to the given string and assigns it to the Iso6393 field.
func (o *Language) SetIso6393(v string) {
	o.Iso6393 = &v
}

func (o Language) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Language) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.NativeName) {
		toSerialize["native_name"] = o.NativeName
	}
	if !IsNil(o.Bcp47) {
		toSerialize["bcp_47"] = o.Bcp47
	}
	if !IsNil(o.Iso6391) {
		toSerialize["iso_639_1"] = o.Iso6391
	}
	if !IsNil(o.Iso6393) {
		toSerialize["iso_639_3"] = o.Iso6393
	}
	return toSerialize, nil
}

type NullableLanguage struct {
	value *Language
	isSet bool
}

func (v NullableLanguage) Get() *Language {
	return v.value
}

func (v *NullableLanguage) Set(val *Language) {
	v.value = val
	v.isSet = true
}

func (v NullableLanguage) IsSet() bool {
	return v.isSet
}

func (v *NullableLanguage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLanguage(val *Language) *NullableLanguage {
	return &NullableLanguage{value: val, isSet: true}
}

func (v NullableLanguage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLanguage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


