/*
REST Countries — Countries API (v5)

Read-only country data API. All endpoints are GET, JSON-only, and follow a JSON:API-like envelope: successful payloads sit under a top-level `data` key with `data.objects` (array of Country records) and `data.meta` (pagination block). Failures return an `errors` array of objects carrying a `message`. Authentication is a bearer API key. Spec written against https://restcountries.com/docs/countries (July 2026) and cross-checked against a live v5 record. 

API version: 5.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package restcountries

import (
	"encoding/json"
)

// checks if the ResponseMeta type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseMeta{}

// ResponseMeta struct for ResponseMeta
type ResponseMeta struct {
	// Total matched count after filters.
	Total *int32 `json:"total,omitempty"`
	// Size of the returned slice.
	Count *int32 `json:"count,omitempty"`
	Limit *int32 `json:"limit,omitempty"`
	Offset *int32 `json:"offset,omitempty"`
	// Whether records exist past this page.
	More *bool `json:"more,omitempty"`
	RequestId *string `json:"request_id,omitempty"`
}

// NewResponseMeta instantiates a new ResponseMeta object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseMeta() *ResponseMeta {
	this := ResponseMeta{}
	return &this
}

// NewResponseMetaWithDefaults instantiates a new ResponseMeta object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseMetaWithDefaults() *ResponseMeta {
	this := ResponseMeta{}
	return &this
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *ResponseMeta) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseMeta) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *ResponseMeta) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *ResponseMeta) SetTotal(v int32) {
	o.Total = &v
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *ResponseMeta) GetCount() int32 {
	if o == nil || IsNil(o.Count) {
		var ret int32
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseMeta) GetCountOk() (*int32, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *ResponseMeta) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int32 and assigns it to the Count field.
func (o *ResponseMeta) SetCount(v int32) {
	o.Count = &v
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *ResponseMeta) GetLimit() int32 {
	if o == nil || IsNil(o.Limit) {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseMeta) GetLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.Limit) {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *ResponseMeta) HasLimit() bool {
	if o != nil && !IsNil(o.Limit) {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *ResponseMeta) SetLimit(v int32) {
	o.Limit = &v
}

// GetOffset returns the Offset field value if set, zero value otherwise.
func (o *ResponseMeta) GetOffset() int32 {
	if o == nil || IsNil(o.Offset) {
		var ret int32
		return ret
	}
	return *o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseMeta) GetOffsetOk() (*int32, bool) {
	if o == nil || IsNil(o.Offset) {
		return nil, false
	}
	return o.Offset, true
}

// HasOffset returns a boolean if a field has been set.
func (o *ResponseMeta) HasOffset() bool {
	if o != nil && !IsNil(o.Offset) {
		return true
	}

	return false
}

// SetOffset gets a reference to the given int32 and assigns it to the Offset field.
func (o *ResponseMeta) SetOffset(v int32) {
	o.Offset = &v
}

// GetMore returns the More field value if set, zero value otherwise.
func (o *ResponseMeta) GetMore() bool {
	if o == nil || IsNil(o.More) {
		var ret bool
		return ret
	}
	return *o.More
}

// GetMoreOk returns a tuple with the More field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseMeta) GetMoreOk() (*bool, bool) {
	if o == nil || IsNil(o.More) {
		return nil, false
	}
	return o.More, true
}

// HasMore returns a boolean if a field has been set.
func (o *ResponseMeta) HasMore() bool {
	if o != nil && !IsNil(o.More) {
		return true
	}

	return false
}

// SetMore gets a reference to the given bool and assigns it to the More field.
func (o *ResponseMeta) SetMore(v bool) {
	o.More = &v
}

// GetRequestId returns the RequestId field value if set, zero value otherwise.
func (o *ResponseMeta) GetRequestId() string {
	if o == nil || IsNil(o.RequestId) {
		var ret string
		return ret
	}
	return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseMeta) GetRequestIdOk() (*string, bool) {
	if o == nil || IsNil(o.RequestId) {
		return nil, false
	}
	return o.RequestId, true
}

// HasRequestId returns a boolean if a field has been set.
func (o *ResponseMeta) HasRequestId() bool {
	if o != nil && !IsNil(o.RequestId) {
		return true
	}

	return false
}

// SetRequestId gets a reference to the given string and assigns it to the RequestId field.
func (o *ResponseMeta) SetRequestId(v string) {
	o.RequestId = &v
}

func (o ResponseMeta) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseMeta) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	if !IsNil(o.Limit) {
		toSerialize["limit"] = o.Limit
	}
	if !IsNil(o.Offset) {
		toSerialize["offset"] = o.Offset
	}
	if !IsNil(o.More) {
		toSerialize["more"] = o.More
	}
	if !IsNil(o.RequestId) {
		toSerialize["request_id"] = o.RequestId
	}
	return toSerialize, nil
}

type NullableResponseMeta struct {
	value *ResponseMeta
	isSet bool
}

func (v NullableResponseMeta) Get() *ResponseMeta {
	return v.value
}

func (v *NullableResponseMeta) Set(val *ResponseMeta) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseMeta) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseMeta) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseMeta(val *ResponseMeta) *NullableResponseMeta {
	return &NullableResponseMeta{value: val, isSet: true}
}

func (v NullableResponseMeta) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseMeta) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


