/*
REST Countries — Countries API (v5)

Read-only country data API. All endpoints are GET, JSON-only, and follow a JSON:API-like envelope: successful payloads sit under a top-level `data` key with `data.objects` (array of Country records) and `data.meta` (pagination block). Failures return an `errors` array of objects carrying a `message`. Authentication is a bearer API key. Spec written against https://restcountries.com/docs/countries (July 2026) and cross-checked against a live v5 record. 

API version: 5.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package restcountries

import (
	"encoding/json"
)

// checks if the CountryListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CountryListResponse{}

// CountryListResponse Standard v5 success envelope. Records live under data.objects.
type CountryListResponse struct {
	Data *CountryListResponseData `json:"data,omitempty"`
}

// NewCountryListResponse instantiates a new CountryListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCountryListResponse() *CountryListResponse {
	this := CountryListResponse{}
	return &this
}

// NewCountryListResponseWithDefaults instantiates a new CountryListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCountryListResponseWithDefaults() *CountryListResponse {
	this := CountryListResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *CountryListResponse) GetData() CountryListResponseData {
	if o == nil || IsNil(o.Data) {
		var ret CountryListResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CountryListResponse) GetDataOk() (*CountryListResponseData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *CountryListResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given CountryListResponseData and assigns it to the Data field.
func (o *CountryListResponse) SetData(v CountryListResponseData) {
	o.Data = &v
}

func (o CountryListResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CountryListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableCountryListResponse struct {
	value *CountryListResponse
	isSet bool
}

func (v NullableCountryListResponse) Get() *CountryListResponse {
	return v.value
}

func (v *NullableCountryListResponse) Set(val *CountryListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCountryListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCountryListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCountryListResponse(val *CountryListResponse) *NullableCountryListResponse {
	return &NullableCountryListResponse{value: val, isSet: true}
}

func (v NullableCountryListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCountryListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


