/*
OpenAPI Example

This is an  OpenAPI specification for Rest Countries API.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AllresponsebodyInnerCapitalInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AllresponsebodyInnerCapitalInfo{}

// AllresponsebodyInnerCapitalInfo struct for AllresponsebodyInnerCapitalInfo
type AllresponsebodyInnerCapitalInfo struct {
	Latlng []float32 `json:"latlng,omitempty"`
}

// NewAllresponsebodyInnerCapitalInfo instantiates a new AllresponsebodyInnerCapitalInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAllresponsebodyInnerCapitalInfo() *AllresponsebodyInnerCapitalInfo {
	this := AllresponsebodyInnerCapitalInfo{}
	return &this
}

// NewAllresponsebodyInnerCapitalInfoWithDefaults instantiates a new AllresponsebodyInnerCapitalInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAllresponsebodyInnerCapitalInfoWithDefaults() *AllresponsebodyInnerCapitalInfo {
	this := AllresponsebodyInnerCapitalInfo{}
	return &this
}

// GetLatlng returns the Latlng field value if set, zero value otherwise.
func (o *AllresponsebodyInnerCapitalInfo) GetLatlng() []float32 {
	if o == nil || IsNil(o.Latlng) {
		var ret []float32
		return ret
	}
	return o.Latlng
}

// GetLatlngOk returns a tuple with the Latlng field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AllresponsebodyInnerCapitalInfo) GetLatlngOk() ([]float32, bool) {
	if o == nil || IsNil(o.Latlng) {
		return nil, false
	}
	return o.Latlng, true
}

// HasLatlng returns a boolean if a field has been set.
func (o *AllresponsebodyInnerCapitalInfo) HasLatlng() bool {
	if o != nil && !IsNil(o.Latlng) {
		return true
	}

	return false
}

// SetLatlng gets a reference to the given []float32 and assigns it to the Latlng field.
func (o *AllresponsebodyInnerCapitalInfo) SetLatlng(v []float32) {
	o.Latlng = v
}

func (o AllresponsebodyInnerCapitalInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AllresponsebodyInnerCapitalInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Latlng) {
		toSerialize["latlng"] = o.Latlng
	}
	return toSerialize, nil
}

type NullableAllresponsebodyInnerCapitalInfo struct {
	value *AllresponsebodyInnerCapitalInfo
	isSet bool
}

func (v NullableAllresponsebodyInnerCapitalInfo) Get() *AllresponsebodyInnerCapitalInfo {
	return v.value
}

func (v *NullableAllresponsebodyInnerCapitalInfo) Set(val *AllresponsebodyInnerCapitalInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableAllresponsebodyInnerCapitalInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableAllresponsebodyInnerCapitalInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAllresponsebodyInnerCapitalInfo(val *AllresponsebodyInnerCapitalInfo) *NullableAllresponsebodyInnerCapitalInfo {
	return &NullableAllresponsebodyInnerCapitalInfo{value: val, isSet: true}
}

func (v NullableAllresponsebodyInnerCapitalInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAllresponsebodyInnerCapitalInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


