/*
OpenAPI Example

This is an  OpenAPI specification for Rest Countries API.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the IddDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IddDetails{}

// IddDetails struct for IddDetails
type IddDetails struct {
	Root *string `json:"root,omitempty"`
	Suffixes []string `json:"suffixes,omitempty"`
}

// NewIddDetails instantiates a new IddDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIddDetails() *IddDetails {
	this := IddDetails{}
	return &this
}

// NewIddDetailsWithDefaults instantiates a new IddDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIddDetailsWithDefaults() *IddDetails {
	this := IddDetails{}
	return &this
}

// GetRoot returns the Root field value if set, zero value otherwise.
func (o *IddDetails) GetRoot() string {
	if o == nil || IsNil(o.Root) {
		var ret string
		return ret
	}
	return *o.Root
}

// GetRootOk returns a tuple with the Root field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IddDetails) GetRootOk() (*string, bool) {
	if o == nil || IsNil(o.Root) {
		return nil, false
	}
	return o.Root, true
}

// HasRoot returns a boolean if a field has been set.
func (o *IddDetails) HasRoot() bool {
	if o != nil && !IsNil(o.Root) {
		return true
	}

	return false
}

// SetRoot gets a reference to the given string and assigns it to the Root field.
func (o *IddDetails) SetRoot(v string) {
	o.Root = &v
}

// GetSuffixes returns the Suffixes field value if set, zero value otherwise.
func (o *IddDetails) GetSuffixes() []string {
	if o == nil || IsNil(o.Suffixes) {
		var ret []string
		return ret
	}
	return o.Suffixes
}

// GetSuffixesOk returns a tuple with the Suffixes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IddDetails) GetSuffixesOk() ([]string, bool) {
	if o == nil || IsNil(o.Suffixes) {
		return nil, false
	}
	return o.Suffixes, true
}

// HasSuffixes returns a boolean if a field has been set.
func (o *IddDetails) HasSuffixes() bool {
	if o != nil && !IsNil(o.Suffixes) {
		return true
	}

	return false
}

// SetSuffixes gets a reference to the given []string and assigns it to the Suffixes field.
func (o *IddDetails) SetSuffixes(v []string) {
	o.Suffixes = v
}

func (o IddDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IddDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Root) {
		toSerialize["root"] = o.Root
	}
	if !IsNil(o.Suffixes) {
		toSerialize["suffixes"] = o.Suffixes
	}
	return toSerialize, nil
}

type NullableIddDetails struct {
	value *IddDetails
	isSet bool
}

func (v NullableIddDetails) Get() *IddDetails {
	return v.value
}

func (v *NullableIddDetails) Set(val *IddDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableIddDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableIddDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIddDetails(val *IddDetails) *NullableIddDetails {
	return &NullableIddDetails{value: val, isSet: true}
}

func (v NullableIddDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIddDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


