/*
REST Countries — Countries API (v5)

Read-only country data API. All endpoints are GET, JSON-only, and follow a JSON:API-like envelope: successful payloads sit under a top-level `data` key with `data.objects` (array of Country records) and `data.meta` (pagination block). Failures return an `errors` array of objects carrying a `message`. Authentication is a bearer API key. Spec written against https://restcountries.com/docs/countries (July 2026) and cross-checked against a live v5 record. 

API version: 5.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package restcountries

import (
	"encoding/json"
)

// checks if the CountryUnits type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CountryUnits{}

// CountryUnits struct for CountryUnits
type CountryUnits struct {
	MeasurementSystem *string `json:"measurement_system,omitempty"`
	TemperatureScale *string `json:"temperature_scale,omitempty"`
}

// NewCountryUnits instantiates a new CountryUnits object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCountryUnits() *CountryUnits {
	this := CountryUnits{}
	return &this
}

// NewCountryUnitsWithDefaults instantiates a new CountryUnits object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCountryUnitsWithDefaults() *CountryUnits {
	this := CountryUnits{}
	return &this
}

// GetMeasurementSystem returns the MeasurementSystem field value if set, zero value otherwise.
func (o *CountryUnits) GetMeasurementSystem() string {
	if o == nil || IsNil(o.MeasurementSystem) {
		var ret string
		return ret
	}
	return *o.MeasurementSystem
}

// GetMeasurementSystemOk returns a tuple with the MeasurementSystem field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CountryUnits) GetMeasurementSystemOk() (*string, bool) {
	if o == nil || IsNil(o.MeasurementSystem) {
		return nil, false
	}
	return o.MeasurementSystem, true
}

// HasMeasurementSystem returns a boolean if a field has been set.
func (o *CountryUnits) HasMeasurementSystem() bool {
	if o != nil && !IsNil(o.MeasurementSystem) {
		return true
	}

	return false
}

// SetMeasurementSystem gets a reference to the given string and assigns it to the MeasurementSystem field.
func (o *CountryUnits) SetMeasurementSystem(v string) {
	o.MeasurementSystem = &v
}

// GetTemperatureScale returns the TemperatureScale field value if set, zero value otherwise.
func (o *CountryUnits) GetTemperatureScale() string {
	if o == nil || IsNil(o.TemperatureScale) {
		var ret string
		return ret
	}
	return *o.TemperatureScale
}

// GetTemperatureScaleOk returns a tuple with the TemperatureScale field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CountryUnits) GetTemperatureScaleOk() (*string, bool) {
	if o == nil || IsNil(o.TemperatureScale) {
		return nil, false
	}
	return o.TemperatureScale, true
}

// HasTemperatureScale returns a boolean if a field has been set.
func (o *CountryUnits) HasTemperatureScale() bool {
	if o != nil && !IsNil(o.TemperatureScale) {
		return true
	}

	return false
}

// SetTemperatureScale gets a reference to the given string and assigns it to the TemperatureScale field.
func (o *CountryUnits) SetTemperatureScale(v string) {
	o.TemperatureScale = &v
}

func (o CountryUnits) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CountryUnits) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MeasurementSystem) {
		toSerialize["measurement_system"] = o.MeasurementSystem
	}
	if !IsNil(o.TemperatureScale) {
		toSerialize["temperature_scale"] = o.TemperatureScale
	}
	return toSerialize, nil
}

type NullableCountryUnits struct {
	value *CountryUnits
	isSet bool
}

func (v NullableCountryUnits) Get() *CountryUnits {
	return v.value
}

func (v *NullableCountryUnits) Set(val *CountryUnits) {
	v.value = val
	v.isSet = true
}

func (v NullableCountryUnits) IsSet() bool {
	return v.isSet
}

func (v *NullableCountryUnits) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCountryUnits(val *CountryUnits) *NullableCountryUnits {
	return &NullableCountryUnits{value: val, isSet: true}
}

func (v NullableCountryUnits) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCountryUnits) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


