/*
REST Countries — Countries API (v5)

Read-only country data API. All endpoints are GET, JSON-only, and follow a JSON:API-like envelope: successful payloads sit under a top-level `data` key with `data.objects` (array of Country records) and `data.meta` (pagination block). Failures return an `errors` array of objects carrying a `message`. Authentication is a bearer API key. Spec written against https://restcountries.com/docs/countries (July 2026) and cross-checked against a live v5 record. 

API version: 5.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package restcountries

import (
	"encoding/json"
)

// checks if the Capital type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Capital{}

// Capital struct for Capital
type Capital struct {
	Name *string `json:"name,omitempty"`
	Coordinates *Coordinates `json:"coordinates,omitempty"`
	Attributes *CapitalAttributes `json:"attributes,omitempty"`
}

// NewCapital instantiates a new Capital object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCapital() *Capital {
	this := Capital{}
	return &this
}

// NewCapitalWithDefaults instantiates a new Capital object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCapitalWithDefaults() *Capital {
	this := Capital{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *Capital) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Capital) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *Capital) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *Capital) SetName(v string) {
	o.Name = &v
}

// GetCoordinates returns the Coordinates field value if set, zero value otherwise.
func (o *Capital) GetCoordinates() Coordinates {
	if o == nil || IsNil(o.Coordinates) {
		var ret Coordinates
		return ret
	}
	return *o.Coordinates
}

// GetCoordinatesOk returns a tuple with the Coordinates field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Capital) GetCoordinatesOk() (*Coordinates, bool) {
	if o == nil || IsNil(o.Coordinates) {
		return nil, false
	}
	return o.Coordinates, true
}

// HasCoordinates returns a boolean if a field has been set.
func (o *Capital) HasCoordinates() bool {
	if o != nil && !IsNil(o.Coordinates) {
		return true
	}

	return false
}

// SetCoordinates gets a reference to the given Coordinates and assigns it to the Coordinates field.
func (o *Capital) SetCoordinates(v Coordinates) {
	o.Coordinates = &v
}

// GetAttributes returns the Attributes field value if set, zero value otherwise.
func (o *Capital) GetAttributes() CapitalAttributes {
	if o == nil || IsNil(o.Attributes) {
		var ret CapitalAttributes
		return ret
	}
	return *o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Capital) GetAttributesOk() (*CapitalAttributes, bool) {
	if o == nil || IsNil(o.Attributes) {
		return nil, false
	}
	return o.Attributes, true
}

// HasAttributes returns a boolean if a field has been set.
func (o *Capital) HasAttributes() bool {
	if o != nil && !IsNil(o.Attributes) {
		return true
	}

	return false
}

// SetAttributes gets a reference to the given CapitalAttributes and assigns it to the Attributes field.
func (o *Capital) SetAttributes(v CapitalAttributes) {
	o.Attributes = &v
}

func (o Capital) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Capital) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Coordinates) {
		toSerialize["coordinates"] = o.Coordinates
	}
	if !IsNil(o.Attributes) {
		toSerialize["attributes"] = o.Attributes
	}
	return toSerialize, nil
}

type NullableCapital struct {
	value *Capital
	isSet bool
}

func (v NullableCapital) Get() *Capital {
	return v.value
}

func (v *NullableCapital) Set(val *Capital) {
	v.value = val
	v.isSet = true
}

func (v NullableCapital) IsSet() bool {
	return v.isSet
}

func (v *NullableCapital) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCapital(val *Capital) *NullableCapital {
	return &NullableCapital{value: val, isSet: true}
}

func (v NullableCapital) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCapital) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


