/*
REST Countries — Countries API (v5)

Read-only country data API. All endpoints are GET, JSON-only, and follow a JSON:API-like envelope: successful payloads sit under a top-level `data` key with `data.objects` (array of Country records) and `data.meta` (pagination block). Failures return an `errors` array of objects carrying a `message`. Authentication is a bearer API key. Spec written against https://restcountries.com/docs/countries (July 2026) and cross-checked against a live v5 record. 

API version: 5.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package restcountries

import (
	"encoding/json"
)

// checks if the Flag type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Flag{}

// Flag struct for Flag
type Flag struct {
	Emoji *string `json:"emoji,omitempty"`
	Unicode *string `json:"unicode,omitempty"`
	HtmlEntity *string `json:"html_entity,omitempty"`
	UrlPng *string `json:"url_png,omitempty"`
	UrlSvg *string `json:"url_svg,omitempty"`
	Description *string `json:"description,omitempty"`
	Colors *FlagColors `json:"colors,omitempty"`
}

// NewFlag instantiates a new Flag object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFlag() *Flag {
	this := Flag{}
	return &this
}

// NewFlagWithDefaults instantiates a new Flag object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFlagWithDefaults() *Flag {
	this := Flag{}
	return &this
}

// GetEmoji returns the Emoji field value if set, zero value otherwise.
func (o *Flag) GetEmoji() string {
	if o == nil || IsNil(o.Emoji) {
		var ret string
		return ret
	}
	return *o.Emoji
}

// GetEmojiOk returns a tuple with the Emoji field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Flag) GetEmojiOk() (*string, bool) {
	if o == nil || IsNil(o.Emoji) {
		return nil, false
	}
	return o.Emoji, true
}

// HasEmoji returns a boolean if a field has been set.
func (o *Flag) HasEmoji() bool {
	if o != nil && !IsNil(o.Emoji) {
		return true
	}

	return false
}

// SetEmoji gets a reference to the given string and assigns it to the Emoji field.
func (o *Flag) SetEmoji(v string) {
	o.Emoji = &v
}

// GetUnicode returns the Unicode field value if set, zero value otherwise.
func (o *Flag) GetUnicode() string {
	if o == nil || IsNil(o.Unicode) {
		var ret string
		return ret
	}
	return *o.Unicode
}

// GetUnicodeOk returns a tuple with the Unicode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Flag) GetUnicodeOk() (*string, bool) {
	if o == nil || IsNil(o.Unicode) {
		return nil, false
	}
	return o.Unicode, true
}

// HasUnicode returns a boolean if a field has been set.
func (o *Flag) HasUnicode() bool {
	if o != nil && !IsNil(o.Unicode) {
		return true
	}

	return false
}

// SetUnicode gets a reference to the given string and assigns it to the Unicode field.
func (o *Flag) SetUnicode(v string) {
	o.Unicode = &v
}

// GetHtmlEntity returns the HtmlEntity field value if set, zero value otherwise.
func (o *Flag) GetHtmlEntity() string {
	if o == nil || IsNil(o.HtmlEntity) {
		var ret string
		return ret
	}
	return *o.HtmlEntity
}

// GetHtmlEntityOk returns a tuple with the HtmlEntity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Flag) GetHtmlEntityOk() (*string, bool) {
	if o == nil || IsNil(o.HtmlEntity) {
		return nil, false
	}
	return o.HtmlEntity, true
}

// HasHtmlEntity returns a boolean if a field has been set.
func (o *Flag) HasHtmlEntity() bool {
	if o != nil && !IsNil(o.HtmlEntity) {
		return true
	}

	return false
}

// SetHtmlEntity gets a reference to the given string and assigns it to the HtmlEntity field.
func (o *Flag) SetHtmlEntity(v string) {
	o.HtmlEntity = &v
}

// GetUrlPng returns the UrlPng field value if set, zero value otherwise.
func (o *Flag) GetUrlPng() string {
	if o == nil || IsNil(o.UrlPng) {
		var ret string
		return ret
	}
	return *o.UrlPng
}

// GetUrlPngOk returns a tuple with the UrlPng field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Flag) GetUrlPngOk() (*string, bool) {
	if o == nil || IsNil(o.UrlPng) {
		return nil, false
	}
	return o.UrlPng, true
}

// HasUrlPng returns a boolean if a field has been set.
func (o *Flag) HasUrlPng() bool {
	if o != nil && !IsNil(o.UrlPng) {
		return true
	}

	return false
}

// SetUrlPng gets a reference to the given string and assigns it to the UrlPng field.
func (o *Flag) SetUrlPng(v string) {
	o.UrlPng = &v
}

// GetUrlSvg returns the UrlSvg field value if set, zero value otherwise.
func (o *Flag) GetUrlSvg() string {
	if o == nil || IsNil(o.UrlSvg) {
		var ret string
		return ret
	}
	return *o.UrlSvg
}

// GetUrlSvgOk returns a tuple with the UrlSvg field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Flag) GetUrlSvgOk() (*string, bool) {
	if o == nil || IsNil(o.UrlSvg) {
		return nil, false
	}
	return o.UrlSvg, true
}

// HasUrlSvg returns a boolean if a field has been set.
func (o *Flag) HasUrlSvg() bool {
	if o != nil && !IsNil(o.UrlSvg) {
		return true
	}

	return false
}

// SetUrlSvg gets a reference to the given string and assigns it to the UrlSvg field.
func (o *Flag) SetUrlSvg(v string) {
	o.UrlSvg = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *Flag) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Flag) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *Flag) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *Flag) SetDescription(v string) {
	o.Description = &v
}

// GetColors returns the Colors field value if set, zero value otherwise.
func (o *Flag) GetColors() FlagColors {
	if o == nil || IsNil(o.Colors) {
		var ret FlagColors
		return ret
	}
	return *o.Colors
}

// GetColorsOk returns a tuple with the Colors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Flag) GetColorsOk() (*FlagColors, bool) {
	if o == nil || IsNil(o.Colors) {
		return nil, false
	}
	return o.Colors, true
}

// HasColors returns a boolean if a field has been set.
func (o *Flag) HasColors() bool {
	if o != nil && !IsNil(o.Colors) {
		return true
	}

	return false
}

// SetColors gets a reference to the given FlagColors and assigns it to the Colors field.
func (o *Flag) SetColors(v FlagColors) {
	o.Colors = &v
}

func (o Flag) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Flag) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Emoji) {
		toSerialize["emoji"] = o.Emoji
	}
	if !IsNil(o.Unicode) {
		toSerialize["unicode"] = o.Unicode
	}
	if !IsNil(o.HtmlEntity) {
		toSerialize["html_entity"] = o.HtmlEntity
	}
	if !IsNil(o.UrlPng) {
		toSerialize["url_png"] = o.UrlPng
	}
	if !IsNil(o.UrlSvg) {
		toSerialize["url_svg"] = o.UrlSvg
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Colors) {
		toSerialize["colors"] = o.Colors
	}
	return toSerialize, nil
}

type NullableFlag struct {
	value *Flag
	isSet bool
}

func (v NullableFlag) Get() *Flag {
	return v.value
}

func (v *NullableFlag) Set(val *Flag) {
	v.value = val
	v.isSet = true
}

func (v NullableFlag) IsSet() bool {
	return v.isSet
}

func (v *NullableFlag) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFlag(val *Flag) *NullableFlag {
	return &NullableFlag{value: val, isSet: true}
}

func (v NullableFlag) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFlag) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


