/*
REST Countries — Countries API (v5)

Read-only country data API. All endpoints are GET, JSON-only, and follow a JSON:API-like envelope: successful payloads sit under a top-level `data` key with `data.objects` (array of Country records) and `data.meta` (pagination block). Failures return an `errors` array of objects carrying a `message`. Authentication is a bearer API key. Spec written against https://restcountries.com/docs/countries (July 2026) and cross-checked against a live v5 record. 

API version: 5.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package restcountries

import (
	"encoding/json"
)

// checks if the CountryLinks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CountryLinks{}

// CountryLinks struct for CountryLinks
type CountryLinks struct {
	Official *string `json:"official,omitempty"`
	Wikipedia *string `json:"wikipedia,omitempty"`
	OpenStreetMaps *string `json:"open_street_maps,omitempty"`
	GoogleMaps *string `json:"google_maps,omitempty"`
}

// NewCountryLinks instantiates a new CountryLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCountryLinks() *CountryLinks {
	this := CountryLinks{}
	return &this
}

// NewCountryLinksWithDefaults instantiates a new CountryLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCountryLinksWithDefaults() *CountryLinks {
	this := CountryLinks{}
	return &this
}

// GetOfficial returns the Official field value if set, zero value otherwise.
func (o *CountryLinks) GetOfficial() string {
	if o == nil || IsNil(o.Official) {
		var ret string
		return ret
	}
	return *o.Official
}

// GetOfficialOk returns a tuple with the Official field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CountryLinks) GetOfficialOk() (*string, bool) {
	if o == nil || IsNil(o.Official) {
		return nil, false
	}
	return o.Official, true
}

// HasOfficial returns a boolean if a field has been set.
func (o *CountryLinks) HasOfficial() bool {
	if o != nil && !IsNil(o.Official) {
		return true
	}

	return false
}

// SetOfficial gets a reference to the given string and assigns it to the Official field.
func (o *CountryLinks) SetOfficial(v string) {
	o.Official = &v
}

// GetWikipedia returns the Wikipedia field value if set, zero value otherwise.
func (o *CountryLinks) GetWikipedia() string {
	if o == nil || IsNil(o.Wikipedia) {
		var ret string
		return ret
	}
	return *o.Wikipedia
}

// GetWikipediaOk returns a tuple with the Wikipedia field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CountryLinks) GetWikipediaOk() (*string, bool) {
	if o == nil || IsNil(o.Wikipedia) {
		return nil, false
	}
	return o.Wikipedia, true
}

// HasWikipedia returns a boolean if a field has been set.
func (o *CountryLinks) HasWikipedia() bool {
	if o != nil && !IsNil(o.Wikipedia) {
		return true
	}

	return false
}

// SetWikipedia gets a reference to the given string and assigns it to the Wikipedia field.
func (o *CountryLinks) SetWikipedia(v string) {
	o.Wikipedia = &v
}

// GetOpenStreetMaps returns the OpenStreetMaps field value if set, zero value otherwise.
func (o *CountryLinks) GetOpenStreetMaps() string {
	if o == nil || IsNil(o.OpenStreetMaps) {
		var ret string
		return ret
	}
	return *o.OpenStreetMaps
}

// GetOpenStreetMapsOk returns a tuple with the OpenStreetMaps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CountryLinks) GetOpenStreetMapsOk() (*string, bool) {
	if o == nil || IsNil(o.OpenStreetMaps) {
		return nil, false
	}
	return o.OpenStreetMaps, true
}

// HasOpenStreetMaps returns a boolean if a field has been set.
func (o *CountryLinks) HasOpenStreetMaps() bool {
	if o != nil && !IsNil(o.OpenStreetMaps) {
		return true
	}

	return false
}

// SetOpenStreetMaps gets a reference to the given string and assigns it to the OpenStreetMaps field.
func (o *CountryLinks) SetOpenStreetMaps(v string) {
	o.OpenStreetMaps = &v
}

// GetGoogleMaps returns the GoogleMaps field value if set, zero value otherwise.
func (o *CountryLinks) GetGoogleMaps() string {
	if o == nil || IsNil(o.GoogleMaps) {
		var ret string
		return ret
	}
	return *o.GoogleMaps
}

// GetGoogleMapsOk returns a tuple with the GoogleMaps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CountryLinks) GetGoogleMapsOk() (*string, bool) {
	if o == nil || IsNil(o.GoogleMaps) {
		return nil, false
	}
	return o.GoogleMaps, true
}

// HasGoogleMaps returns a boolean if a field has been set.
func (o *CountryLinks) HasGoogleMaps() bool {
	if o != nil && !IsNil(o.GoogleMaps) {
		return true
	}

	return false
}

// SetGoogleMaps gets a reference to the given string and assigns it to the GoogleMaps field.
func (o *CountryLinks) SetGoogleMaps(v string) {
	o.GoogleMaps = &v
}

func (o CountryLinks) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CountryLinks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Official) {
		toSerialize["official"] = o.Official
	}
	if !IsNil(o.Wikipedia) {
		toSerialize["wikipedia"] = o.Wikipedia
	}
	if !IsNil(o.OpenStreetMaps) {
		toSerialize["open_street_maps"] = o.OpenStreetMaps
	}
	if !IsNil(o.GoogleMaps) {
		toSerialize["google_maps"] = o.GoogleMaps
	}
	return toSerialize, nil
}

type NullableCountryLinks struct {
	value *CountryLinks
	isSet bool
}

func (v NullableCountryLinks) Get() *CountryLinks {
	return v.value
}

func (v *NullableCountryLinks) Set(val *CountryLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableCountryLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableCountryLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCountryLinks(val *CountryLinks) *NullableCountryLinks {
	return &NullableCountryLinks{value: val, isSet: true}
}

func (v NullableCountryLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCountryLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


