/*
REST Countries — Countries API (v5)

Read-only country data API. All endpoints are GET, JSON-only, and follow a JSON:API-like envelope: successful payloads sit under a top-level `data` key with `data.objects` (array of Country records) and `data.meta` (pagination block). Failures return an `errors` array of objects carrying a `message`. Authentication is a bearer API key. Spec written against https://restcountries.com/docs/countries (July 2026) and cross-checked against a live v5 record. 

API version: 5.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package restcountries

import (
	"encoding/json"
)

// checks if the FlagColorsSwatches type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FlagColorsSwatches{}

// FlagColorsSwatches All six roles always present; null when no matching color.
type FlagColorsSwatches struct {
	Vibrant NullableString `json:"vibrant,omitempty"`
	Muted NullableString `json:"muted,omitempty"`
	DarkVibrant NullableString `json:"dark_vibrant,omitempty"`
	DarkMuted NullableString `json:"dark_muted,omitempty"`
	LightVibrant NullableString `json:"light_vibrant,omitempty"`
	LightMuted NullableString `json:"light_muted,omitempty"`
}

// NewFlagColorsSwatches instantiates a new FlagColorsSwatches object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFlagColorsSwatches() *FlagColorsSwatches {
	this := FlagColorsSwatches{}
	return &this
}

// NewFlagColorsSwatchesWithDefaults instantiates a new FlagColorsSwatches object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFlagColorsSwatchesWithDefaults() *FlagColorsSwatches {
	this := FlagColorsSwatches{}
	return &this
}

// GetVibrant returns the Vibrant field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FlagColorsSwatches) GetVibrant() string {
	if o == nil || IsNil(o.Vibrant.Get()) {
		var ret string
		return ret
	}
	return *o.Vibrant.Get()
}

// GetVibrantOk returns a tuple with the Vibrant field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FlagColorsSwatches) GetVibrantOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Vibrant.Get(), o.Vibrant.IsSet()
}

// HasVibrant returns a boolean if a field has been set.
func (o *FlagColorsSwatches) HasVibrant() bool {
	if o != nil && o.Vibrant.IsSet() {
		return true
	}

	return false
}

// SetVibrant gets a reference to the given NullableString and assigns it to the Vibrant field.
func (o *FlagColorsSwatches) SetVibrant(v string) {
	o.Vibrant.Set(&v)
}
// SetVibrantNil sets the value for Vibrant to be an explicit nil
func (o *FlagColorsSwatches) SetVibrantNil() {
	o.Vibrant.Set(nil)
}

// UnsetVibrant ensures that no value is present for Vibrant, not even an explicit nil
func (o *FlagColorsSwatches) UnsetVibrant() {
	o.Vibrant.Unset()
}

// GetMuted returns the Muted field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FlagColorsSwatches) GetMuted() string {
	if o == nil || IsNil(o.Muted.Get()) {
		var ret string
		return ret
	}
	return *o.Muted.Get()
}

// GetMutedOk returns a tuple with the Muted field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FlagColorsSwatches) GetMutedOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Muted.Get(), o.Muted.IsSet()
}

// HasMuted returns a boolean if a field has been set.
func (o *FlagColorsSwatches) HasMuted() bool {
	if o != nil && o.Muted.IsSet() {
		return true
	}

	return false
}

// SetMuted gets a reference to the given NullableString and assigns it to the Muted field.
func (o *FlagColorsSwatches) SetMuted(v string) {
	o.Muted.Set(&v)
}
// SetMutedNil sets the value for Muted to be an explicit nil
func (o *FlagColorsSwatches) SetMutedNil() {
	o.Muted.Set(nil)
}

// UnsetMuted ensures that no value is present for Muted, not even an explicit nil
func (o *FlagColorsSwatches) UnsetMuted() {
	o.Muted.Unset()
}

// GetDarkVibrant returns the DarkVibrant field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FlagColorsSwatches) GetDarkVibrant() string {
	if o == nil || IsNil(o.DarkVibrant.Get()) {
		var ret string
		return ret
	}
	return *o.DarkVibrant.Get()
}

// GetDarkVibrantOk returns a tuple with the DarkVibrant field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FlagColorsSwatches) GetDarkVibrantOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DarkVibrant.Get(), o.DarkVibrant.IsSet()
}

// HasDarkVibrant returns a boolean if a field has been set.
func (o *FlagColorsSwatches) HasDarkVibrant() bool {
	if o != nil && o.DarkVibrant.IsSet() {
		return true
	}

	return false
}

// SetDarkVibrant gets a reference to the given NullableString and assigns it to the DarkVibrant field.
func (o *FlagColorsSwatches) SetDarkVibrant(v string) {
	o.DarkVibrant.Set(&v)
}
// SetDarkVibrantNil sets the value for DarkVibrant to be an explicit nil
func (o *FlagColorsSwatches) SetDarkVibrantNil() {
	o.DarkVibrant.Set(nil)
}

// UnsetDarkVibrant ensures that no value is present for DarkVibrant, not even an explicit nil
func (o *FlagColorsSwatches) UnsetDarkVibrant() {
	o.DarkVibrant.Unset()
}

// GetDarkMuted returns the DarkMuted field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FlagColorsSwatches) GetDarkMuted() string {
	if o == nil || IsNil(o.DarkMuted.Get()) {
		var ret string
		return ret
	}
	return *o.DarkMuted.Get()
}

// GetDarkMutedOk returns a tuple with the DarkMuted field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FlagColorsSwatches) GetDarkMutedOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DarkMuted.Get(), o.DarkMuted.IsSet()
}

// HasDarkMuted returns a boolean if a field has been set.
func (o *FlagColorsSwatches) HasDarkMuted() bool {
	if o != nil && o.DarkMuted.IsSet() {
		return true
	}

	return false
}

// SetDarkMuted gets a reference to the given NullableString and assigns it to the DarkMuted field.
func (o *FlagColorsSwatches) SetDarkMuted(v string) {
	o.DarkMuted.Set(&v)
}
// SetDarkMutedNil sets the value for DarkMuted to be an explicit nil
func (o *FlagColorsSwatches) SetDarkMutedNil() {
	o.DarkMuted.Set(nil)
}

// UnsetDarkMuted ensures that no value is present for DarkMuted, not even an explicit nil
func (o *FlagColorsSwatches) UnsetDarkMuted() {
	o.DarkMuted.Unset()
}

// GetLightVibrant returns the LightVibrant field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FlagColorsSwatches) GetLightVibrant() string {
	if o == nil || IsNil(o.LightVibrant.Get()) {
		var ret string
		return ret
	}
	return *o.LightVibrant.Get()
}

// GetLightVibrantOk returns a tuple with the LightVibrant field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FlagColorsSwatches) GetLightVibrantOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LightVibrant.Get(), o.LightVibrant.IsSet()
}

// HasLightVibrant returns a boolean if a field has been set.
func (o *FlagColorsSwatches) HasLightVibrant() bool {
	if o != nil && o.LightVibrant.IsSet() {
		return true
	}

	return false
}

// SetLightVibrant gets a reference to the given NullableString and assigns it to the LightVibrant field.
func (o *FlagColorsSwatches) SetLightVibrant(v string) {
	o.LightVibrant.Set(&v)
}
// SetLightVibrantNil sets the value for LightVibrant to be an explicit nil
func (o *FlagColorsSwatches) SetLightVibrantNil() {
	o.LightVibrant.Set(nil)
}

// UnsetLightVibrant ensures that no value is present for LightVibrant, not even an explicit nil
func (o *FlagColorsSwatches) UnsetLightVibrant() {
	o.LightVibrant.Unset()
}

// GetLightMuted returns the LightMuted field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FlagColorsSwatches) GetLightMuted() string {
	if o == nil || IsNil(o.LightMuted.Get()) {
		var ret string
		return ret
	}
	return *o.LightMuted.Get()
}

// GetLightMutedOk returns a tuple with the LightMuted field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FlagColorsSwatches) GetLightMutedOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LightMuted.Get(), o.LightMuted.IsSet()
}

// HasLightMuted returns a boolean if a field has been set.
func (o *FlagColorsSwatches) HasLightMuted() bool {
	if o != nil && o.LightMuted.IsSet() {
		return true
	}

	return false
}

// SetLightMuted gets a reference to the given NullableString and assigns it to the LightMuted field.
func (o *FlagColorsSwatches) SetLightMuted(v string) {
	o.LightMuted.Set(&v)
}
// SetLightMutedNil sets the value for LightMuted to be an explicit nil
func (o *FlagColorsSwatches) SetLightMutedNil() {
	o.LightMuted.Set(nil)
}

// UnsetLightMuted ensures that no value is present for LightMuted, not even an explicit nil
func (o *FlagColorsSwatches) UnsetLightMuted() {
	o.LightMuted.Unset()
}

func (o FlagColorsSwatches) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FlagColorsSwatches) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Vibrant.IsSet() {
		toSerialize["vibrant"] = o.Vibrant.Get()
	}
	if o.Muted.IsSet() {
		toSerialize["muted"] = o.Muted.Get()
	}
	if o.DarkVibrant.IsSet() {
		toSerialize["dark_vibrant"] = o.DarkVibrant.Get()
	}
	if o.DarkMuted.IsSet() {
		toSerialize["dark_muted"] = o.DarkMuted.Get()
	}
	if o.LightVibrant.IsSet() {
		toSerialize["light_vibrant"] = o.LightVibrant.Get()
	}
	if o.LightMuted.IsSet() {
		toSerialize["light_muted"] = o.LightMuted.Get()
	}
	return toSerialize, nil
}

type NullableFlagColorsSwatches struct {
	value *FlagColorsSwatches
	isSet bool
}

func (v NullableFlagColorsSwatches) Get() *FlagColorsSwatches {
	return v.value
}

func (v *NullableFlagColorsSwatches) Set(val *FlagColorsSwatches) {
	v.value = val
	v.isSet = true
}

func (v NullableFlagColorsSwatches) IsSet() bool {
	return v.isSet
}

func (v *NullableFlagColorsSwatches) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFlagColorsSwatches(val *FlagColorsSwatches) *NullableFlagColorsSwatches {
	return &NullableFlagColorsSwatches{value: val, isSet: true}
}

func (v NullableFlagColorsSwatches) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFlagColorsSwatches) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


