/*
REST Countries — Countries API (v5)

Read-only country data API. All endpoints are GET, JSON-only, and follow a JSON:API-like envelope: successful payloads sit under a top-level `data` key with `data.objects` (array of Country records) and `data.meta` (pagination block). Failures return an `errors` array of objects carrying a `message`. Authentication is a bearer API key. Spec written against https://restcountries.com/docs/countries (July 2026) and cross-checked against a live v5 record. 

API version: 5.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package restcountries

import (
	"encoding/json"
)

// checks if the FlagColorsPaletteInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FlagColorsPaletteInner{}

// FlagColorsPaletteInner struct for FlagColorsPaletteInner
type FlagColorsPaletteInner struct {
	Hex *string `json:"hex,omitempty"`
	Proportion *float32 `json:"proportion,omitempty"`
}

// NewFlagColorsPaletteInner instantiates a new FlagColorsPaletteInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFlagColorsPaletteInner() *FlagColorsPaletteInner {
	this := FlagColorsPaletteInner{}
	return &this
}

// NewFlagColorsPaletteInnerWithDefaults instantiates a new FlagColorsPaletteInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFlagColorsPaletteInnerWithDefaults() *FlagColorsPaletteInner {
	this := FlagColorsPaletteInner{}
	return &this
}

// GetHex returns the Hex field value if set, zero value otherwise.
func (o *FlagColorsPaletteInner) GetHex() string {
	if o == nil || IsNil(o.Hex) {
		var ret string
		return ret
	}
	return *o.Hex
}

// GetHexOk returns a tuple with the Hex field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FlagColorsPaletteInner) GetHexOk() (*string, bool) {
	if o == nil || IsNil(o.Hex) {
		return nil, false
	}
	return o.Hex, true
}

// HasHex returns a boolean if a field has been set.
func (o *FlagColorsPaletteInner) HasHex() bool {
	if o != nil && !IsNil(o.Hex) {
		return true
	}

	return false
}

// SetHex gets a reference to the given string and assigns it to the Hex field.
func (o *FlagColorsPaletteInner) SetHex(v string) {
	o.Hex = &v
}

// GetProportion returns the Proportion field value if set, zero value otherwise.
func (o *FlagColorsPaletteInner) GetProportion() float32 {
	if o == nil || IsNil(o.Proportion) {
		var ret float32
		return ret
	}
	return *o.Proportion
}

// GetProportionOk returns a tuple with the Proportion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FlagColorsPaletteInner) GetProportionOk() (*float32, bool) {
	if o == nil || IsNil(o.Proportion) {
		return nil, false
	}
	return o.Proportion, true
}

// HasProportion returns a boolean if a field has been set.
func (o *FlagColorsPaletteInner) HasProportion() bool {
	if o != nil && !IsNil(o.Proportion) {
		return true
	}

	return false
}

// SetProportion gets a reference to the given float32 and assigns it to the Proportion field.
func (o *FlagColorsPaletteInner) SetProportion(v float32) {
	o.Proportion = &v
}

func (o FlagColorsPaletteInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FlagColorsPaletteInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Hex) {
		toSerialize["hex"] = o.Hex
	}
	if !IsNil(o.Proportion) {
		toSerialize["proportion"] = o.Proportion
	}
	return toSerialize, nil
}

type NullableFlagColorsPaletteInner struct {
	value *FlagColorsPaletteInner
	isSet bool
}

func (v NullableFlagColorsPaletteInner) Get() *FlagColorsPaletteInner {
	return v.value
}

func (v *NullableFlagColorsPaletteInner) Set(val *FlagColorsPaletteInner) {
	v.value = val
	v.isSet = true
}

func (v NullableFlagColorsPaletteInner) IsSet() bool {
	return v.isSet
}

func (v *NullableFlagColorsPaletteInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFlagColorsPaletteInner(val *FlagColorsPaletteInner) *NullableFlagColorsPaletteInner {
	return &NullableFlagColorsPaletteInner{value: val, isSet: true}
}

func (v NullableFlagColorsPaletteInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFlagColorsPaletteInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


