/*
REST Countries — Countries API (v5)

Read-only country data API. All endpoints are GET, JSON-only, and follow a JSON:API-like envelope: successful payloads sit under a top-level `data` key with `data.objects` (array of Country records) and `data.meta` (pagination block). Failures return an `errors` array of objects carrying a `message`. Authentication is a bearer API key. Spec written against https://restcountries.com/docs/countries (July 2026) and cross-checked against a live v5 record. 

API version: 5.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package restcountries

import (
	"encoding/json"
)

// checks if the FlagColors type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FlagColors{}

// FlagColors struct for FlagColors
type FlagColors struct {
	Dominant *string `json:"dominant,omitempty"`
	Prominent *string `json:"prominent,omitempty"`
	Palette []FlagColorsPaletteInner `json:"palette,omitempty"`
	Swatches *FlagColorsSwatches `json:"swatches,omitempty"`
}

// NewFlagColors instantiates a new FlagColors object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFlagColors() *FlagColors {
	this := FlagColors{}
	return &this
}

// NewFlagColorsWithDefaults instantiates a new FlagColors object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFlagColorsWithDefaults() *FlagColors {
	this := FlagColors{}
	return &this
}

// GetDominant returns the Dominant field value if set, zero value otherwise.
func (o *FlagColors) GetDominant() string {
	if o == nil || IsNil(o.Dominant) {
		var ret string
		return ret
	}
	return *o.Dominant
}

// GetDominantOk returns a tuple with the Dominant field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FlagColors) GetDominantOk() (*string, bool) {
	if o == nil || IsNil(o.Dominant) {
		return nil, false
	}
	return o.Dominant, true
}

// HasDominant returns a boolean if a field has been set.
func (o *FlagColors) HasDominant() bool {
	if o != nil && !IsNil(o.Dominant) {
		return true
	}

	return false
}

// SetDominant gets a reference to the given string and assigns it to the Dominant field.
func (o *FlagColors) SetDominant(v string) {
	o.Dominant = &v
}

// GetProminent returns the Prominent field value if set, zero value otherwise.
func (o *FlagColors) GetProminent() string {
	if o == nil || IsNil(o.Prominent) {
		var ret string
		return ret
	}
	return *o.Prominent
}

// GetProminentOk returns a tuple with the Prominent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FlagColors) GetProminentOk() (*string, bool) {
	if o == nil || IsNil(o.Prominent) {
		return nil, false
	}
	return o.Prominent, true
}

// HasProminent returns a boolean if a field has been set.
func (o *FlagColors) HasProminent() bool {
	if o != nil && !IsNil(o.Prominent) {
		return true
	}

	return false
}

// SetProminent gets a reference to the given string and assigns it to the Prominent field.
func (o *FlagColors) SetProminent(v string) {
	o.Prominent = &v
}

// GetPalette returns the Palette field value if set, zero value otherwise.
func (o *FlagColors) GetPalette() []FlagColorsPaletteInner {
	if o == nil || IsNil(o.Palette) {
		var ret []FlagColorsPaletteInner
		return ret
	}
	return o.Palette
}

// GetPaletteOk returns a tuple with the Palette field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FlagColors) GetPaletteOk() ([]FlagColorsPaletteInner, bool) {
	if o == nil || IsNil(o.Palette) {
		return nil, false
	}
	return o.Palette, true
}

// HasPalette returns a boolean if a field has been set.
func (o *FlagColors) HasPalette() bool {
	if o != nil && !IsNil(o.Palette) {
		return true
	}

	return false
}

// SetPalette gets a reference to the given []FlagColorsPaletteInner and assigns it to the Palette field.
func (o *FlagColors) SetPalette(v []FlagColorsPaletteInner) {
	o.Palette = v
}

// GetSwatches returns the Swatches field value if set, zero value otherwise.
func (o *FlagColors) GetSwatches() FlagColorsSwatches {
	if o == nil || IsNil(o.Swatches) {
		var ret FlagColorsSwatches
		return ret
	}
	return *o.Swatches
}

// GetSwatchesOk returns a tuple with the Swatches field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FlagColors) GetSwatchesOk() (*FlagColorsSwatches, bool) {
	if o == nil || IsNil(o.Swatches) {
		return nil, false
	}
	return o.Swatches, true
}

// HasSwatches returns a boolean if a field has been set.
func (o *FlagColors) HasSwatches() bool {
	if o != nil && !IsNil(o.Swatches) {
		return true
	}

	return false
}

// SetSwatches gets a reference to the given FlagColorsSwatches and assigns it to the Swatches field.
func (o *FlagColors) SetSwatches(v FlagColorsSwatches) {
	o.Swatches = &v
}

func (o FlagColors) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FlagColors) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Dominant) {
		toSerialize["dominant"] = o.Dominant
	}
	if !IsNil(o.Prominent) {
		toSerialize["prominent"] = o.Prominent
	}
	if !IsNil(o.Palette) {
		toSerialize["palette"] = o.Palette
	}
	if !IsNil(o.Swatches) {
		toSerialize["swatches"] = o.Swatches
	}
	return toSerialize, nil
}

type NullableFlagColors struct {
	value *FlagColors
	isSet bool
}

func (v NullableFlagColors) Get() *FlagColors {
	return v.value
}

func (v *NullableFlagColors) Set(val *FlagColors) {
	v.value = val
	v.isSet = true
}

func (v NullableFlagColors) IsSet() bool {
	return v.isSet
}

func (v *NullableFlagColors) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFlagColors(val *FlagColors) *NullableFlagColors {
	return &NullableFlagColors{value: val, isSet: true}
}

func (v NullableFlagColors) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFlagColors) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


