/*
REST Countries — Countries API (v5)

Read-only country data API. All endpoints are GET, JSON-only, and follow a JSON:API-like envelope: successful payloads sit under a top-level `data` key with `data.objects` (array of Country records) and `data.meta` (pagination block). Failures return an `errors` array of objects carrying a `message`. Authentication is a bearer API key. Spec written against https://restcountries.com/docs/countries (July 2026) and cross-checked against a live v5 record. 

API version: 5.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package restcountries

import (
	"encoding/json"
)

// checks if the DateConventionsFiscalYearStart type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DateConventionsFiscalYearStart{}

// DateConventionsFiscalYearStart struct for DateConventionsFiscalYearStart
type DateConventionsFiscalYearStart struct {
	Government *MonthDay `json:"government,omitempty"`
	Corporate *DateConventionsFiscalYearStartCorporate `json:"corporate,omitempty"`
	Personal *MonthDay `json:"personal,omitempty"`
}

// NewDateConventionsFiscalYearStart instantiates a new DateConventionsFiscalYearStart object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDateConventionsFiscalYearStart() *DateConventionsFiscalYearStart {
	this := DateConventionsFiscalYearStart{}
	return &this
}

// NewDateConventionsFiscalYearStartWithDefaults instantiates a new DateConventionsFiscalYearStart object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDateConventionsFiscalYearStartWithDefaults() *DateConventionsFiscalYearStart {
	this := DateConventionsFiscalYearStart{}
	return &this
}

// GetGovernment returns the Government field value if set, zero value otherwise.
func (o *DateConventionsFiscalYearStart) GetGovernment() MonthDay {
	if o == nil || IsNil(o.Government) {
		var ret MonthDay
		return ret
	}
	return *o.Government
}

// GetGovernmentOk returns a tuple with the Government field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DateConventionsFiscalYearStart) GetGovernmentOk() (*MonthDay, bool) {
	if o == nil || IsNil(o.Government) {
		return nil, false
	}
	return o.Government, true
}

// HasGovernment returns a boolean if a field has been set.
func (o *DateConventionsFiscalYearStart) HasGovernment() bool {
	if o != nil && !IsNil(o.Government) {
		return true
	}

	return false
}

// SetGovernment gets a reference to the given MonthDay and assigns it to the Government field.
func (o *DateConventionsFiscalYearStart) SetGovernment(v MonthDay) {
	o.Government = &v
}

// GetCorporate returns the Corporate field value if set, zero value otherwise.
func (o *DateConventionsFiscalYearStart) GetCorporate() DateConventionsFiscalYearStartCorporate {
	if o == nil || IsNil(o.Corporate) {
		var ret DateConventionsFiscalYearStartCorporate
		return ret
	}
	return *o.Corporate
}

// GetCorporateOk returns a tuple with the Corporate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DateConventionsFiscalYearStart) GetCorporateOk() (*DateConventionsFiscalYearStartCorporate, bool) {
	if o == nil || IsNil(o.Corporate) {
		return nil, false
	}
	return o.Corporate, true
}

// HasCorporate returns a boolean if a field has been set.
func (o *DateConventionsFiscalYearStart) HasCorporate() bool {
	if o != nil && !IsNil(o.Corporate) {
		return true
	}

	return false
}

// SetCorporate gets a reference to the given DateConventionsFiscalYearStartCorporate and assigns it to the Corporate field.
func (o *DateConventionsFiscalYearStart) SetCorporate(v DateConventionsFiscalYearStartCorporate) {
	o.Corporate = &v
}

// GetPersonal returns the Personal field value if set, zero value otherwise.
func (o *DateConventionsFiscalYearStart) GetPersonal() MonthDay {
	if o == nil || IsNil(o.Personal) {
		var ret MonthDay
		return ret
	}
	return *o.Personal
}

// GetPersonalOk returns a tuple with the Personal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DateConventionsFiscalYearStart) GetPersonalOk() (*MonthDay, bool) {
	if o == nil || IsNil(o.Personal) {
		return nil, false
	}
	return o.Personal, true
}

// HasPersonal returns a boolean if a field has been set.
func (o *DateConventionsFiscalYearStart) HasPersonal() bool {
	if o != nil && !IsNil(o.Personal) {
		return true
	}

	return false
}

// SetPersonal gets a reference to the given MonthDay and assigns it to the Personal field.
func (o *DateConventionsFiscalYearStart) SetPersonal(v MonthDay) {
	o.Personal = &v
}

func (o DateConventionsFiscalYearStart) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DateConventionsFiscalYearStart) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Government) {
		toSerialize["government"] = o.Government
	}
	if !IsNil(o.Corporate) {
		toSerialize["corporate"] = o.Corporate
	}
	if !IsNil(o.Personal) {
		toSerialize["personal"] = o.Personal
	}
	return toSerialize, nil
}

type NullableDateConventionsFiscalYearStart struct {
	value *DateConventionsFiscalYearStart
	isSet bool
}

func (v NullableDateConventionsFiscalYearStart) Get() *DateConventionsFiscalYearStart {
	return v.value
}

func (v *NullableDateConventionsFiscalYearStart) Set(val *DateConventionsFiscalYearStart) {
	v.value = val
	v.isSet = true
}

func (v NullableDateConventionsFiscalYearStart) IsSet() bool {
	return v.isSet
}

func (v *NullableDateConventionsFiscalYearStart) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDateConventionsFiscalYearStart(val *DateConventionsFiscalYearStart) *NullableDateConventionsFiscalYearStart {
	return &NullableDateConventionsFiscalYearStart{value: val, isSet: true}
}

func (v NullableDateConventionsFiscalYearStart) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDateConventionsFiscalYearStart) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


