/*
REST Countries — Countries API (v5)

Read-only country data API. All endpoints are GET, JSON-only, and follow a JSON:API-like envelope: successful payloads sit under a top-level `data` key with `data.objects` (array of Country records) and `data.meta` (pagination block). Failures return an `errors` array of objects carrying a `message`. Authentication is a bearer API key. Spec written against https://restcountries.com/docs/countries (July 2026) and cross-checked against a live v5 record. 

API version: 5.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package restcountries

import (
	"encoding/json"
)

// checks if the Classification type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Classification{}

// Classification struct for Classification
type Classification struct {
	// Replaces v3.1's `independent` (verified against a live v5 record).
	Sovereign *bool `json:"sovereign,omitempty"`
	UnMember *bool `json:"un_member,omitempty"`
	UnObserver *bool `json:"un_observer,omitempty"`
	Disputed *bool `json:"disputed,omitempty"`
	Dependency *bool `json:"dependency,omitempty"`
	DependencyType *string `json:"dependency_type,omitempty"`
	IsoStatus *string `json:"iso_status,omitempty"`
}

// NewClassification instantiates a new Classification object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClassification() *Classification {
	this := Classification{}
	return &this
}

// NewClassificationWithDefaults instantiates a new Classification object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClassificationWithDefaults() *Classification {
	this := Classification{}
	return &this
}

// GetSovereign returns the Sovereign field value if set, zero value otherwise.
func (o *Classification) GetSovereign() bool {
	if o == nil || IsNil(o.Sovereign) {
		var ret bool
		return ret
	}
	return *o.Sovereign
}

// GetSovereignOk returns a tuple with the Sovereign field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Classification) GetSovereignOk() (*bool, bool) {
	if o == nil || IsNil(o.Sovereign) {
		return nil, false
	}
	return o.Sovereign, true
}

// HasSovereign returns a boolean if a field has been set.
func (o *Classification) HasSovereign() bool {
	if o != nil && !IsNil(o.Sovereign) {
		return true
	}

	return false
}

// SetSovereign gets a reference to the given bool and assigns it to the Sovereign field.
func (o *Classification) SetSovereign(v bool) {
	o.Sovereign = &v
}

// GetUnMember returns the UnMember field value if set, zero value otherwise.
func (o *Classification) GetUnMember() bool {
	if o == nil || IsNil(o.UnMember) {
		var ret bool
		return ret
	}
	return *o.UnMember
}

// GetUnMemberOk returns a tuple with the UnMember field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Classification) GetUnMemberOk() (*bool, bool) {
	if o == nil || IsNil(o.UnMember) {
		return nil, false
	}
	return o.UnMember, true
}

// HasUnMember returns a boolean if a field has been set.
func (o *Classification) HasUnMember() bool {
	if o != nil && !IsNil(o.UnMember) {
		return true
	}

	return false
}

// SetUnMember gets a reference to the given bool and assigns it to the UnMember field.
func (o *Classification) SetUnMember(v bool) {
	o.UnMember = &v
}

// GetUnObserver returns the UnObserver field value if set, zero value otherwise.
func (o *Classification) GetUnObserver() bool {
	if o == nil || IsNil(o.UnObserver) {
		var ret bool
		return ret
	}
	return *o.UnObserver
}

// GetUnObserverOk returns a tuple with the UnObserver field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Classification) GetUnObserverOk() (*bool, bool) {
	if o == nil || IsNil(o.UnObserver) {
		return nil, false
	}
	return o.UnObserver, true
}

// HasUnObserver returns a boolean if a field has been set.
func (o *Classification) HasUnObserver() bool {
	if o != nil && !IsNil(o.UnObserver) {
		return true
	}

	return false
}

// SetUnObserver gets a reference to the given bool and assigns it to the UnObserver field.
func (o *Classification) SetUnObserver(v bool) {
	o.UnObserver = &v
}

// GetDisputed returns the Disputed field value if set, zero value otherwise.
func (o *Classification) GetDisputed() bool {
	if o == nil || IsNil(o.Disputed) {
		var ret bool
		return ret
	}
	return *o.Disputed
}

// GetDisputedOk returns a tuple with the Disputed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Classification) GetDisputedOk() (*bool, bool) {
	if o == nil || IsNil(o.Disputed) {
		return nil, false
	}
	return o.Disputed, true
}

// HasDisputed returns a boolean if a field has been set.
func (o *Classification) HasDisputed() bool {
	if o != nil && !IsNil(o.Disputed) {
		return true
	}

	return false
}

// SetDisputed gets a reference to the given bool and assigns it to the Disputed field.
func (o *Classification) SetDisputed(v bool) {
	o.Disputed = &v
}

// GetDependency returns the Dependency field value if set, zero value otherwise.
func (o *Classification) GetDependency() bool {
	if o == nil || IsNil(o.Dependency) {
		var ret bool
		return ret
	}
	return *o.Dependency
}

// GetDependencyOk returns a tuple with the Dependency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Classification) GetDependencyOk() (*bool, bool) {
	if o == nil || IsNil(o.Dependency) {
		return nil, false
	}
	return o.Dependency, true
}

// HasDependency returns a boolean if a field has been set.
func (o *Classification) HasDependency() bool {
	if o != nil && !IsNil(o.Dependency) {
		return true
	}

	return false
}

// SetDependency gets a reference to the given bool and assigns it to the Dependency field.
func (o *Classification) SetDependency(v bool) {
	o.Dependency = &v
}

// GetDependencyType returns the DependencyType field value if set, zero value otherwise.
func (o *Classification) GetDependencyType() string {
	if o == nil || IsNil(o.DependencyType) {
		var ret string
		return ret
	}
	return *o.DependencyType
}

// GetDependencyTypeOk returns a tuple with the DependencyType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Classification) GetDependencyTypeOk() (*string, bool) {
	if o == nil || IsNil(o.DependencyType) {
		return nil, false
	}
	return o.DependencyType, true
}

// HasDependencyType returns a boolean if a field has been set.
func (o *Classification) HasDependencyType() bool {
	if o != nil && !IsNil(o.DependencyType) {
		return true
	}

	return false
}

// SetDependencyType gets a reference to the given string and assigns it to the DependencyType field.
func (o *Classification) SetDependencyType(v string) {
	o.DependencyType = &v
}

// GetIsoStatus returns the IsoStatus field value if set, zero value otherwise.
func (o *Classification) GetIsoStatus() string {
	if o == nil || IsNil(o.IsoStatus) {
		var ret string
		return ret
	}
	return *o.IsoStatus
}

// GetIsoStatusOk returns a tuple with the IsoStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Classification) GetIsoStatusOk() (*string, bool) {
	if o == nil || IsNil(o.IsoStatus) {
		return nil, false
	}
	return o.IsoStatus, true
}

// HasIsoStatus returns a boolean if a field has been set.
func (o *Classification) HasIsoStatus() bool {
	if o != nil && !IsNil(o.IsoStatus) {
		return true
	}

	return false
}

// SetIsoStatus gets a reference to the given string and assigns it to the IsoStatus field.
func (o *Classification) SetIsoStatus(v string) {
	o.IsoStatus = &v
}

func (o Classification) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Classification) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Sovereign) {
		toSerialize["sovereign"] = o.Sovereign
	}
	if !IsNil(o.UnMember) {
		toSerialize["un_member"] = o.UnMember
	}
	if !IsNil(o.UnObserver) {
		toSerialize["un_observer"] = o.UnObserver
	}
	if !IsNil(o.Disputed) {
		toSerialize["disputed"] = o.Disputed
	}
	if !IsNil(o.Dependency) {
		toSerialize["dependency"] = o.Dependency
	}
	if !IsNil(o.DependencyType) {
		toSerialize["dependency_type"] = o.DependencyType
	}
	if !IsNil(o.IsoStatus) {
		toSerialize["iso_status"] = o.IsoStatus
	}
	return toSerialize, nil
}

type NullableClassification struct {
	value *Classification
	isSet bool
}

func (v NullableClassification) Get() *Classification {
	return v.value
}

func (v *NullableClassification) Set(val *Classification) {
	v.value = val
	v.isSet = true
}

func (v NullableClassification) IsSet() bool {
	return v.isSet
}

func (v *NullableClassification) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClassification(val *Classification) *NullableClassification {
	return &NullableClassification{value: val, isSet: true}
}

func (v NullableClassification) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClassification) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


