/*
OpenAPI Example

This is an  OpenAPI specification for Rest Countries API.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the NameDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NameDetails{}

// NameDetails struct for NameDetails
type NameDetails struct {
	Common *string `json:"common,omitempty"`
	Official *string `json:"official,omitempty"`
	NativeName *map[string]NativeNameDetail `json:"nativeName,omitempty"`
}

// NewNameDetails instantiates a new NameDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNameDetails() *NameDetails {
	this := NameDetails{}
	return &this
}

// NewNameDetailsWithDefaults instantiates a new NameDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNameDetailsWithDefaults() *NameDetails {
	this := NameDetails{}
	return &this
}

// GetCommon returns the Common field value if set, zero value otherwise.
func (o *NameDetails) GetCommon() string {
	if o == nil || IsNil(o.Common) {
		var ret string
		return ret
	}
	return *o.Common
}

// GetCommonOk returns a tuple with the Common field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NameDetails) GetCommonOk() (*string, bool) {
	if o == nil || IsNil(o.Common) {
		return nil, false
	}
	return o.Common, true
}

// HasCommon returns a boolean if a field has been set.
func (o *NameDetails) HasCommon() bool {
	if o != nil && !IsNil(o.Common) {
		return true
	}

	return false
}

// SetCommon gets a reference to the given string and assigns it to the Common field.
func (o *NameDetails) SetCommon(v string) {
	o.Common = &v
}

// GetOfficial returns the Official field value if set, zero value otherwise.
func (o *NameDetails) GetOfficial() string {
	if o == nil || IsNil(o.Official) {
		var ret string
		return ret
	}
	return *o.Official
}

// GetOfficialOk returns a tuple with the Official field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NameDetails) GetOfficialOk() (*string, bool) {
	if o == nil || IsNil(o.Official) {
		return nil, false
	}
	return o.Official, true
}

// HasOfficial returns a boolean if a field has been set.
func (o *NameDetails) HasOfficial() bool {
	if o != nil && !IsNil(o.Official) {
		return true
	}

	return false
}

// SetOfficial gets a reference to the given string and assigns it to the Official field.
func (o *NameDetails) SetOfficial(v string) {
	o.Official = &v
}

// GetNativeName returns the NativeName field value if set, zero value otherwise.
func (o *NameDetails) GetNativeName() map[string]NativeNameDetail {
	if o == nil || IsNil(o.NativeName) {
		var ret map[string]NativeNameDetail
		return ret
	}
	return *o.NativeName
}

// GetNativeNameOk returns a tuple with the NativeName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NameDetails) GetNativeNameOk() (*map[string]NativeNameDetail, bool) {
	if o == nil || IsNil(o.NativeName) {
		return nil, false
	}
	return o.NativeName, true
}

// HasNativeName returns a boolean if a field has been set.
func (o *NameDetails) HasNativeName() bool {
	if o != nil && !IsNil(o.NativeName) {
		return true
	}

	return false
}

// SetNativeName gets a reference to the given map[string]NativeNameDetail and assigns it to the NativeName field.
func (o *NameDetails) SetNativeName(v map[string]NativeNameDetail) {
	o.NativeName = &v
}

func (o NameDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NameDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Common) {
		toSerialize["common"] = o.Common
	}
	if !IsNil(o.Official) {
		toSerialize["official"] = o.Official
	}
	if !IsNil(o.NativeName) {
		toSerialize["nativeName"] = o.NativeName
	}
	return toSerialize, nil
}

type NullableNameDetails struct {
	value *NameDetails
	isSet bool
}

func (v NullableNameDetails) Get() *NameDetails {
	return v.value
}

func (v *NullableNameDetails) Set(val *NameDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableNameDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableNameDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNameDetails(val *NameDetails) *NullableNameDetails {
	return &NullableNameDetails{value: val, isSet: true}
}

func (v NullableNameDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNameDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


