/*
REST Countries — Countries API (v5)

Read-only country data API. All endpoints are GET, JSON-only, and follow a JSON:API-like envelope: successful payloads sit under a top-level `data` key with `data.objects` (array of Country records) and `data.meta` (pagination block). Failures return an `errors` array of objects carrying a `message`. Authentication is a bearer API key. Spec written against https://restcountries.com/docs/countries (July 2026) and cross-checked against a live v5 record. 

API version: 5.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package restcountries

import (
	"encoding/json"
)

// checks if the Coordinates type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Coordinates{}

// Coordinates struct for Coordinates
type Coordinates struct {
	Lat *float32 `json:"lat,omitempty"`
	Lng *float32 `json:"lng,omitempty"`
}

// NewCoordinates instantiates a new Coordinates object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCoordinates() *Coordinates {
	this := Coordinates{}
	return &this
}

// NewCoordinatesWithDefaults instantiates a new Coordinates object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCoordinatesWithDefaults() *Coordinates {
	this := Coordinates{}
	return &this
}

// GetLat returns the Lat field value if set, zero value otherwise.
func (o *Coordinates) GetLat() float32 {
	if o == nil || IsNil(o.Lat) {
		var ret float32
		return ret
	}
	return *o.Lat
}

// GetLatOk returns a tuple with the Lat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Coordinates) GetLatOk() (*float32, bool) {
	if o == nil || IsNil(o.Lat) {
		return nil, false
	}
	return o.Lat, true
}

// HasLat returns a boolean if a field has been set.
func (o *Coordinates) HasLat() bool {
	if o != nil && !IsNil(o.Lat) {
		return true
	}

	return false
}

// SetLat gets a reference to the given float32 and assigns it to the Lat field.
func (o *Coordinates) SetLat(v float32) {
	o.Lat = &v
}

// GetLng returns the Lng field value if set, zero value otherwise.
func (o *Coordinates) GetLng() float32 {
	if o == nil || IsNil(o.Lng) {
		var ret float32
		return ret
	}
	return *o.Lng
}

// GetLngOk returns a tuple with the Lng field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Coordinates) GetLngOk() (*float32, bool) {
	if o == nil || IsNil(o.Lng) {
		return nil, false
	}
	return o.Lng, true
}

// HasLng returns a boolean if a field has been set.
func (o *Coordinates) HasLng() bool {
	if o != nil && !IsNil(o.Lng) {
		return true
	}

	return false
}

// SetLng gets a reference to the given float32 and assigns it to the Lng field.
func (o *Coordinates) SetLng(v float32) {
	o.Lng = &v
}

func (o Coordinates) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Coordinates) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Lat) {
		toSerialize["lat"] = o.Lat
	}
	if !IsNil(o.Lng) {
		toSerialize["lng"] = o.Lng
	}
	return toSerialize, nil
}

type NullableCoordinates struct {
	value *Coordinates
	isSet bool
}

func (v NullableCoordinates) Get() *Coordinates {
	return v.value
}

func (v *NullableCoordinates) Set(val *Coordinates) {
	v.value = val
	v.isSet = true
}

func (v NullableCoordinates) IsSet() bool {
	return v.isSet
}

func (v *NullableCoordinates) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCoordinates(val *Coordinates) *NullableCoordinates {
	return &NullableCoordinates{value: val, isSet: true}
}

func (v NullableCoordinates) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCoordinates) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


