/*
REST Countries — Countries API (v5)

Read-only country data API. All endpoints are GET, JSON-only, and follow a JSON:API-like envelope: successful payloads sit under a top-level `data` key with `data.objects` (array of Country records) and `data.meta` (pagination block). Failures return an `errors` array of objects carrying a `message`. Authentication is a bearer API key. Spec written against https://restcountries.com/docs/countries (July 2026) and cross-checked against a live v5 record. 

API version: 5.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package restcountries

import (
	"encoding/json"
)

// checks if the NameForms type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NameForms{}

// NameForms struct for NameForms
type NameForms struct {
	Common *string `json:"common,omitempty"`
	Official *string `json:"official,omitempty"`
}

// NewNameForms instantiates a new NameForms object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNameForms() *NameForms {
	this := NameForms{}
	return &this
}

// NewNameFormsWithDefaults instantiates a new NameForms object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNameFormsWithDefaults() *NameForms {
	this := NameForms{}
	return &this
}

// GetCommon returns the Common field value if set, zero value otherwise.
func (o *NameForms) GetCommon() string {
	if o == nil || IsNil(o.Common) {
		var ret string
		return ret
	}
	return *o.Common
}

// GetCommonOk returns a tuple with the Common field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NameForms) GetCommonOk() (*string, bool) {
	if o == nil || IsNil(o.Common) {
		return nil, false
	}
	return o.Common, true
}

// HasCommon returns a boolean if a field has been set.
func (o *NameForms) HasCommon() bool {
	if o != nil && !IsNil(o.Common) {
		return true
	}

	return false
}

// SetCommon gets a reference to the given string and assigns it to the Common field.
func (o *NameForms) SetCommon(v string) {
	o.Common = &v
}

// GetOfficial returns the Official field value if set, zero value otherwise.
func (o *NameForms) GetOfficial() string {
	if o == nil || IsNil(o.Official) {
		var ret string
		return ret
	}
	return *o.Official
}

// GetOfficialOk returns a tuple with the Official field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NameForms) GetOfficialOk() (*string, bool) {
	if o == nil || IsNil(o.Official) {
		return nil, false
	}
	return o.Official, true
}

// HasOfficial returns a boolean if a field has been set.
func (o *NameForms) HasOfficial() bool {
	if o != nil && !IsNil(o.Official) {
		return true
	}

	return false
}

// SetOfficial gets a reference to the given string and assigns it to the Official field.
func (o *NameForms) SetOfficial(v string) {
	o.Official = &v
}

func (o NameForms) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NameForms) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Common) {
		toSerialize["common"] = o.Common
	}
	if !IsNil(o.Official) {
		toSerialize["official"] = o.Official
	}
	return toSerialize, nil
}

type NullableNameForms struct {
	value *NameForms
	isSet bool
}

func (v NullableNameForms) Get() *NameForms {
	return v.value
}

func (v *NullableNameForms) Set(val *NameForms) {
	v.value = val
	v.isSet = true
}

func (v NullableNameForms) IsSet() bool {
	return v.isSet
}

func (v *NullableNameForms) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNameForms(val *NameForms) *NullableNameForms {
	return &NullableNameForms{value: val, isSet: true}
}

func (v NullableNameForms) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNameForms) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


