/*
OpenAPI Example

This is an  OpenAPI specification for Rest Countries API.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the DemonymsDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DemonymsDetails{}

// DemonymsDetails struct for DemonymsDetails
type DemonymsDetails struct {
	F *string `json:"f,omitempty"`
	M *string `json:"m,omitempty"`
}

// NewDemonymsDetails instantiates a new DemonymsDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDemonymsDetails() *DemonymsDetails {
	this := DemonymsDetails{}
	return &this
}

// NewDemonymsDetailsWithDefaults instantiates a new DemonymsDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDemonymsDetailsWithDefaults() *DemonymsDetails {
	this := DemonymsDetails{}
	return &this
}

// GetF returns the F field value if set, zero value otherwise.
func (o *DemonymsDetails) GetF() string {
	if o == nil || IsNil(o.F) {
		var ret string
		return ret
	}
	return *o.F
}

// GetFOk returns a tuple with the F field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DemonymsDetails) GetFOk() (*string, bool) {
	if o == nil || IsNil(o.F) {
		return nil, false
	}
	return o.F, true
}

// HasF returns a boolean if a field has been set.
func (o *DemonymsDetails) HasF() bool {
	if o != nil && !IsNil(o.F) {
		return true
	}

	return false
}

// SetF gets a reference to the given string and assigns it to the F field.
func (o *DemonymsDetails) SetF(v string) {
	o.F = &v
}

// GetM returns the M field value if set, zero value otherwise.
func (o *DemonymsDetails) GetM() string {
	if o == nil || IsNil(o.M) {
		var ret string
		return ret
	}
	return *o.M
}

// GetMOk returns a tuple with the M field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DemonymsDetails) GetMOk() (*string, bool) {
	if o == nil || IsNil(o.M) {
		return nil, false
	}
	return o.M, true
}

// HasM returns a boolean if a field has been set.
func (o *DemonymsDetails) HasM() bool {
	if o != nil && !IsNil(o.M) {
		return true
	}

	return false
}

// SetM gets a reference to the given string and assigns it to the M field.
func (o *DemonymsDetails) SetM(v string) {
	o.M = &v
}

func (o DemonymsDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DemonymsDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.F) {
		toSerialize["f"] = o.F
	}
	if !IsNil(o.M) {
		toSerialize["m"] = o.M
	}
	return toSerialize, nil
}

type NullableDemonymsDetails struct {
	value *DemonymsDetails
	isSet bool
}

func (v NullableDemonymsDetails) Get() *DemonymsDetails {
	return v.value
}

func (v *NullableDemonymsDetails) Set(val *DemonymsDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableDemonymsDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableDemonymsDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDemonymsDetails(val *DemonymsDetails) *NullableDemonymsDetails {
	return &NullableDemonymsDetails{value: val, isSet: true}
}

func (v NullableDemonymsDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDemonymsDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


