/*
OpenAPI Example

This is an  OpenAPI specification for Rest Countries API.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ImageDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ImageDetails{}

// ImageDetails struct for ImageDetails
type ImageDetails struct {
	Png string `json:"png"`
	Svg string `json:"svg"`
	Alt *string `json:"alt,omitempty"`
}

type _ImageDetails ImageDetails

// NewImageDetails instantiates a new ImageDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImageDetails(png string, svg string) *ImageDetails {
	this := ImageDetails{}
	this.Png = png
	this.Svg = svg
	return &this
}

// NewImageDetailsWithDefaults instantiates a new ImageDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImageDetailsWithDefaults() *ImageDetails {
	this := ImageDetails{}
	return &this
}

// GetPng returns the Png field value
func (o *ImageDetails) GetPng() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Png
}

// GetPngOk returns a tuple with the Png field value
// and a boolean to check if the value has been set.
func (o *ImageDetails) GetPngOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Png, true
}

// SetPng sets field value
func (o *ImageDetails) SetPng(v string) {
	o.Png = v
}

// GetSvg returns the Svg field value
func (o *ImageDetails) GetSvg() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Svg
}

// GetSvgOk returns a tuple with the Svg field value
// and a boolean to check if the value has been set.
func (o *ImageDetails) GetSvgOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Svg, true
}

// SetSvg sets field value
func (o *ImageDetails) SetSvg(v string) {
	o.Svg = v
}

// GetAlt returns the Alt field value if set, zero value otherwise.
func (o *ImageDetails) GetAlt() string {
	if o == nil || IsNil(o.Alt) {
		var ret string
		return ret
	}
	return *o.Alt
}

// GetAltOk returns a tuple with the Alt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageDetails) GetAltOk() (*string, bool) {
	if o == nil || IsNil(o.Alt) {
		return nil, false
	}
	return o.Alt, true
}

// HasAlt returns a boolean if a field has been set.
func (o *ImageDetails) HasAlt() bool {
	if o != nil && !IsNil(o.Alt) {
		return true
	}

	return false
}

// SetAlt gets a reference to the given string and assigns it to the Alt field.
func (o *ImageDetails) SetAlt(v string) {
	o.Alt = &v
}

func (o ImageDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ImageDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["png"] = o.Png
	toSerialize["svg"] = o.Svg
	if !IsNil(o.Alt) {
		toSerialize["alt"] = o.Alt
	}
	return toSerialize, nil
}

func (o *ImageDetails) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"png",
		"svg",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varImageDetails := _ImageDetails{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varImageDetails)

	if err != nil {
		return err
	}

	*o = ImageDetails(varImageDetails)

	return err
}

type NullableImageDetails struct {
	value *ImageDetails
	isSet bool
}

func (v NullableImageDetails) Get() *ImageDetails {
	return v.value
}

func (v *NullableImageDetails) Set(val *ImageDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableImageDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableImageDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImageDetails(val *ImageDetails) *NullableImageDetails {
	return &NullableImageDetails{value: val, isSet: true}
}

func (v NullableImageDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImageDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


