/*
REST Countries — Countries API (v5)

Read-only country data API. All endpoints are GET, JSON-only, and follow a JSON:API-like envelope: successful payloads sit under a top-level `data` key with `data.objects` (array of Country records) and `data.meta` (pagination block). Failures return an `errors` array of objects carrying a `message`. Authentication is a bearer API key. Spec written against https://restcountries.com/docs/countries (July 2026) and cross-checked against a live v5 record. 

API version: 5.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package restcountries

import (
	"encoding/json"
)

// checks if the ErrorResponseErrorsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ErrorResponseErrorsInner{}

// ErrorResponseErrorsInner struct for ErrorResponseErrorsInner
type ErrorResponseErrorsInner struct {
	Message *string `json:"message,omitempty"`
}

// NewErrorResponseErrorsInner instantiates a new ErrorResponseErrorsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewErrorResponseErrorsInner() *ErrorResponseErrorsInner {
	this := ErrorResponseErrorsInner{}
	return &this
}

// NewErrorResponseErrorsInnerWithDefaults instantiates a new ErrorResponseErrorsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewErrorResponseErrorsInnerWithDefaults() *ErrorResponseErrorsInner {
	this := ErrorResponseErrorsInner{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ErrorResponseErrorsInner) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ErrorResponseErrorsInner) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ErrorResponseErrorsInner) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ErrorResponseErrorsInner) SetMessage(v string) {
	o.Message = &v
}

func (o ErrorResponseErrorsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ErrorResponseErrorsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableErrorResponseErrorsInner struct {
	value *ErrorResponseErrorsInner
	isSet bool
}

func (v NullableErrorResponseErrorsInner) Get() *ErrorResponseErrorsInner {
	return v.value
}

func (v *NullableErrorResponseErrorsInner) Set(val *ErrorResponseErrorsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableErrorResponseErrorsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableErrorResponseErrorsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableErrorResponseErrorsInner(val *ErrorResponseErrorsInner) *NullableErrorResponseErrorsInner {
	return &NullableErrorResponseErrorsInner{value: val, isSet: true}
}

func (v NullableErrorResponseErrorsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableErrorResponseErrorsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


