/*
REST Countries — Countries API (v5)

Read-only country data API. All endpoints are GET, JSON-only, and follow a JSON:API-like envelope: successful payloads sit under a top-level `data` key with `data.objects` (array of Country records) and `data.meta` (pagination block). Failures return an `errors` array of objects carrying a `message`. Authentication is a bearer API key. Spec written against https://restcountries.com/docs/countries (July 2026) and cross-checked against a live v5 record. 

API version: 5.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package restcountries

import (
	"encoding/json"
)

// checks if the Codes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Codes{}

// Codes struct for Codes
type Codes struct {
	Alpha2 *string `json:"alpha_2,omitempty"`
	Alpha3 *string `json:"alpha_3,omitempty"`
	Ccn3 *string `json:"ccn3,omitempty"`
	Fips *string `json:"fips,omitempty"`
	Gec *string `json:"gec,omitempty"`
	Cioc *string `json:"cioc,omitempty"`
	Fifa *string `json:"fifa,omitempty"`
}

// NewCodes instantiates a new Codes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCodes() *Codes {
	this := Codes{}
	return &this
}

// NewCodesWithDefaults instantiates a new Codes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCodesWithDefaults() *Codes {
	this := Codes{}
	return &this
}

// GetAlpha2 returns the Alpha2 field value if set, zero value otherwise.
func (o *Codes) GetAlpha2() string {
	if o == nil || IsNil(o.Alpha2) {
		var ret string
		return ret
	}
	return *o.Alpha2
}

// GetAlpha2Ok returns a tuple with the Alpha2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Codes) GetAlpha2Ok() (*string, bool) {
	if o == nil || IsNil(o.Alpha2) {
		return nil, false
	}
	return o.Alpha2, true
}

// HasAlpha2 returns a boolean if a field has been set.
func (o *Codes) HasAlpha2() bool {
	if o != nil && !IsNil(o.Alpha2) {
		return true
	}

	return false
}

// SetAlpha2 gets a reference to the given string and assigns it to the Alpha2 field.
func (o *Codes) SetAlpha2(v string) {
	o.Alpha2 = &v
}

// GetAlpha3 returns the Alpha3 field value if set, zero value otherwise.
func (o *Codes) GetAlpha3() string {
	if o == nil || IsNil(o.Alpha3) {
		var ret string
		return ret
	}
	return *o.Alpha3
}

// GetAlpha3Ok returns a tuple with the Alpha3 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Codes) GetAlpha3Ok() (*string, bool) {
	if o == nil || IsNil(o.Alpha3) {
		return nil, false
	}
	return o.Alpha3, true
}

// HasAlpha3 returns a boolean if a field has been set.
func (o *Codes) HasAlpha3() bool {
	if o != nil && !IsNil(o.Alpha3) {
		return true
	}

	return false
}

// SetAlpha3 gets a reference to the given string and assigns it to the Alpha3 field.
func (o *Codes) SetAlpha3(v string) {
	o.Alpha3 = &v
}

// GetCcn3 returns the Ccn3 field value if set, zero value otherwise.
func (o *Codes) GetCcn3() string {
	if o == nil || IsNil(o.Ccn3) {
		var ret string
		return ret
	}
	return *o.Ccn3
}

// GetCcn3Ok returns a tuple with the Ccn3 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Codes) GetCcn3Ok() (*string, bool) {
	if o == nil || IsNil(o.Ccn3) {
		return nil, false
	}
	return o.Ccn3, true
}

// HasCcn3 returns a boolean if a field has been set.
func (o *Codes) HasCcn3() bool {
	if o != nil && !IsNil(o.Ccn3) {
		return true
	}

	return false
}

// SetCcn3 gets a reference to the given string and assigns it to the Ccn3 field.
func (o *Codes) SetCcn3(v string) {
	o.Ccn3 = &v
}

// GetFips returns the Fips field value if set, zero value otherwise.
func (o *Codes) GetFips() string {
	if o == nil || IsNil(o.Fips) {
		var ret string
		return ret
	}
	return *o.Fips
}

// GetFipsOk returns a tuple with the Fips field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Codes) GetFipsOk() (*string, bool) {
	if o == nil || IsNil(o.Fips) {
		return nil, false
	}
	return o.Fips, true
}

// HasFips returns a boolean if a field has been set.
func (o *Codes) HasFips() bool {
	if o != nil && !IsNil(o.Fips) {
		return true
	}

	return false
}

// SetFips gets a reference to the given string and assigns it to the Fips field.
func (o *Codes) SetFips(v string) {
	o.Fips = &v
}

// GetGec returns the Gec field value if set, zero value otherwise.
func (o *Codes) GetGec() string {
	if o == nil || IsNil(o.Gec) {
		var ret string
		return ret
	}
	return *o.Gec
}

// GetGecOk returns a tuple with the Gec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Codes) GetGecOk() (*string, bool) {
	if o == nil || IsNil(o.Gec) {
		return nil, false
	}
	return o.Gec, true
}

// HasGec returns a boolean if a field has been set.
func (o *Codes) HasGec() bool {
	if o != nil && !IsNil(o.Gec) {
		return true
	}

	return false
}

// SetGec gets a reference to the given string and assigns it to the Gec field.
func (o *Codes) SetGec(v string) {
	o.Gec = &v
}

// GetCioc returns the Cioc field value if set, zero value otherwise.
func (o *Codes) GetCioc() string {
	if o == nil || IsNil(o.Cioc) {
		var ret string
		return ret
	}
	return *o.Cioc
}

// GetCiocOk returns a tuple with the Cioc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Codes) GetCiocOk() (*string, bool) {
	if o == nil || IsNil(o.Cioc) {
		return nil, false
	}
	return o.Cioc, true
}

// HasCioc returns a boolean if a field has been set.
func (o *Codes) HasCioc() bool {
	if o != nil && !IsNil(o.Cioc) {
		return true
	}

	return false
}

// SetCioc gets a reference to the given string and assigns it to the Cioc field.
func (o *Codes) SetCioc(v string) {
	o.Cioc = &v
}

// GetFifa returns the Fifa field value if set, zero value otherwise.
func (o *Codes) GetFifa() string {
	if o == nil || IsNil(o.Fifa) {
		var ret string
		return ret
	}
	return *o.Fifa
}

// GetFifaOk returns a tuple with the Fifa field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Codes) GetFifaOk() (*string, bool) {
	if o == nil || IsNil(o.Fifa) {
		return nil, false
	}
	return o.Fifa, true
}

// HasFifa returns a boolean if a field has been set.
func (o *Codes) HasFifa() bool {
	if o != nil && !IsNil(o.Fifa) {
		return true
	}

	return false
}

// SetFifa gets a reference to the given string and assigns it to the Fifa field.
func (o *Codes) SetFifa(v string) {
	o.Fifa = &v
}

func (o Codes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Codes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Alpha2) {
		toSerialize["alpha_2"] = o.Alpha2
	}
	if !IsNil(o.Alpha3) {
		toSerialize["alpha_3"] = o.Alpha3
	}
	if !IsNil(o.Ccn3) {
		toSerialize["ccn3"] = o.Ccn3
	}
	if !IsNil(o.Fips) {
		toSerialize["fips"] = o.Fips
	}
	if !IsNil(o.Gec) {
		toSerialize["gec"] = o.Gec
	}
	if !IsNil(o.Cioc) {
		toSerialize["cioc"] = o.Cioc
	}
	if !IsNil(o.Fifa) {
		toSerialize["fifa"] = o.Fifa
	}
	return toSerialize, nil
}

type NullableCodes struct {
	value *Codes
	isSet bool
}

func (v NullableCodes) Get() *Codes {
	return v.value
}

func (v *NullableCodes) Set(val *Codes) {
	v.value = val
	v.isSet = true
}

func (v NullableCodes) IsSet() bool {
	return v.isSet
}

func (v *NullableCodes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCodes(val *Codes) *NullableCodes {
	return &NullableCodes{value: val, isSet: true}
}

func (v NullableCodes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCodes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


