/*
REST Countries — Countries API (v5)

Read-only country data API. All endpoints are GET, JSON-only, and follow a JSON:API-like envelope: successful payloads sit under a top-level `data` key with `data.objects` (array of Country records) and `data.meta` (pagination block). Failures return an `errors` array of objects carrying a `message`. Authentication is a bearer API key. Spec written against https://restcountries.com/docs/countries (July 2026) and cross-checked against a live v5 record. 

API version: 5.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package restcountries

import (
	"encoding/json"
)

// checks if the Names type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Names{}

// Names struct for Names
type Names struct {
	Common *string `json:"common,omitempty"`
	Official *string `json:"official,omitempty"`
	Alternates []string `json:"alternates,omitempty"`
	// Keyed by ISO 639-3 language code.
	Native *map[string]NameForms `json:"native,omitempty"`
	// Keyed by ISO 639-3 language code. Heavy branch; consider response_fields_omit=names.translations.
	Translations *map[string]NameForms `json:"translations,omitempty"`
}

// NewNames instantiates a new Names object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNames() *Names {
	this := Names{}
	return &this
}

// NewNamesWithDefaults instantiates a new Names object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNamesWithDefaults() *Names {
	this := Names{}
	return &this
}

// GetCommon returns the Common field value if set, zero value otherwise.
func (o *Names) GetCommon() string {
	if o == nil || IsNil(o.Common) {
		var ret string
		return ret
	}
	return *o.Common
}

// GetCommonOk returns a tuple with the Common field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Names) GetCommonOk() (*string, bool) {
	if o == nil || IsNil(o.Common) {
		return nil, false
	}
	return o.Common, true
}

// HasCommon returns a boolean if a field has been set.
func (o *Names) HasCommon() bool {
	if o != nil && !IsNil(o.Common) {
		return true
	}

	return false
}

// SetCommon gets a reference to the given string and assigns it to the Common field.
func (o *Names) SetCommon(v string) {
	o.Common = &v
}

// GetOfficial returns the Official field value if set, zero value otherwise.
func (o *Names) GetOfficial() string {
	if o == nil || IsNil(o.Official) {
		var ret string
		return ret
	}
	return *o.Official
}

// GetOfficialOk returns a tuple with the Official field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Names) GetOfficialOk() (*string, bool) {
	if o == nil || IsNil(o.Official) {
		return nil, false
	}
	return o.Official, true
}

// HasOfficial returns a boolean if a field has been set.
func (o *Names) HasOfficial() bool {
	if o != nil && !IsNil(o.Official) {
		return true
	}

	return false
}

// SetOfficial gets a reference to the given string and assigns it to the Official field.
func (o *Names) SetOfficial(v string) {
	o.Official = &v
}

// GetAlternates returns the Alternates field value if set, zero value otherwise.
func (o *Names) GetAlternates() []string {
	if o == nil || IsNil(o.Alternates) {
		var ret []string
		return ret
	}
	return o.Alternates
}

// GetAlternatesOk returns a tuple with the Alternates field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Names) GetAlternatesOk() ([]string, bool) {
	if o == nil || IsNil(o.Alternates) {
		return nil, false
	}
	return o.Alternates, true
}

// HasAlternates returns a boolean if a field has been set.
func (o *Names) HasAlternates() bool {
	if o != nil && !IsNil(o.Alternates) {
		return true
	}

	return false
}

// SetAlternates gets a reference to the given []string and assigns it to the Alternates field.
func (o *Names) SetAlternates(v []string) {
	o.Alternates = v
}

// GetNative returns the Native field value if set, zero value otherwise.
func (o *Names) GetNative() map[string]NameForms {
	if o == nil || IsNil(o.Native) {
		var ret map[string]NameForms
		return ret
	}
	return *o.Native
}

// GetNativeOk returns a tuple with the Native field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Names) GetNativeOk() (*map[string]NameForms, bool) {
	if o == nil || IsNil(o.Native) {
		return nil, false
	}
	return o.Native, true
}

// HasNative returns a boolean if a field has been set.
func (o *Names) HasNative() bool {
	if o != nil && !IsNil(o.Native) {
		return true
	}

	return false
}

// SetNative gets a reference to the given map[string]NameForms and assigns it to the Native field.
func (o *Names) SetNative(v map[string]NameForms) {
	o.Native = &v
}

// GetTranslations returns the Translations field value if set, zero value otherwise.
func (o *Names) GetTranslations() map[string]NameForms {
	if o == nil || IsNil(o.Translations) {
		var ret map[string]NameForms
		return ret
	}
	return *o.Translations
}

// GetTranslationsOk returns a tuple with the Translations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Names) GetTranslationsOk() (*map[string]NameForms, bool) {
	if o == nil || IsNil(o.Translations) {
		return nil, false
	}
	return o.Translations, true
}

// HasTranslations returns a boolean if a field has been set.
func (o *Names) HasTranslations() bool {
	if o != nil && !IsNil(o.Translations) {
		return true
	}

	return false
}

// SetTranslations gets a reference to the given map[string]NameForms and assigns it to the Translations field.
func (o *Names) SetTranslations(v map[string]NameForms) {
	o.Translations = &v
}

func (o Names) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Names) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Common) {
		toSerialize["common"] = o.Common
	}
	if !IsNil(o.Official) {
		toSerialize["official"] = o.Official
	}
	if !IsNil(o.Alternates) {
		toSerialize["alternates"] = o.Alternates
	}
	if !IsNil(o.Native) {
		toSerialize["native"] = o.Native
	}
	if !IsNil(o.Translations) {
		toSerialize["translations"] = o.Translations
	}
	return toSerialize, nil
}

type NullableNames struct {
	value *Names
	isSet bool
}

func (v NullableNames) Get() *Names {
	return v.value
}

func (v *NullableNames) Set(val *Names) {
	v.value = val
	v.isSet = true
}

func (v NullableNames) IsSet() bool {
	return v.isSet
}

func (v *NullableNames) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNames(val *Names) *NullableNames {
	return &NullableNames{value: val, isSet: true}
}

func (v NullableNames) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNames) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


