/*
OpenAPI Example

This is an  OpenAPI specification for Rest Countries API.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the NativeNameDetail type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NativeNameDetail{}

// NativeNameDetail struct for NativeNameDetail
type NativeNameDetail struct {
	Official *string `json:"official,omitempty"`
	Common *string `json:"common,omitempty"`
}

// NewNativeNameDetail instantiates a new NativeNameDetail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNativeNameDetail() *NativeNameDetail {
	this := NativeNameDetail{}
	return &this
}

// NewNativeNameDetailWithDefaults instantiates a new NativeNameDetail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNativeNameDetailWithDefaults() *NativeNameDetail {
	this := NativeNameDetail{}
	return &this
}

// GetOfficial returns the Official field value if set, zero value otherwise.
func (o *NativeNameDetail) GetOfficial() string {
	if o == nil || IsNil(o.Official) {
		var ret string
		return ret
	}
	return *o.Official
}

// GetOfficialOk returns a tuple with the Official field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NativeNameDetail) GetOfficialOk() (*string, bool) {
	if o == nil || IsNil(o.Official) {
		return nil, false
	}
	return o.Official, true
}

// HasOfficial returns a boolean if a field has been set.
func (o *NativeNameDetail) HasOfficial() bool {
	if o != nil && !IsNil(o.Official) {
		return true
	}

	return false
}

// SetOfficial gets a reference to the given string and assigns it to the Official field.
func (o *NativeNameDetail) SetOfficial(v string) {
	o.Official = &v
}

// GetCommon returns the Common field value if set, zero value otherwise.
func (o *NativeNameDetail) GetCommon() string {
	if o == nil || IsNil(o.Common) {
		var ret string
		return ret
	}
	return *o.Common
}

// GetCommonOk returns a tuple with the Common field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NativeNameDetail) GetCommonOk() (*string, bool) {
	if o == nil || IsNil(o.Common) {
		return nil, false
	}
	return o.Common, true
}

// HasCommon returns a boolean if a field has been set.
func (o *NativeNameDetail) HasCommon() bool {
	if o != nil && !IsNil(o.Common) {
		return true
	}

	return false
}

// SetCommon gets a reference to the given string and assigns it to the Common field.
func (o *NativeNameDetail) SetCommon(v string) {
	o.Common = &v
}

func (o NativeNameDetail) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NativeNameDetail) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Official) {
		toSerialize["official"] = o.Official
	}
	if !IsNil(o.Common) {
		toSerialize["common"] = o.Common
	}
	return toSerialize, nil
}

type NullableNativeNameDetail struct {
	value *NativeNameDetail
	isSet bool
}

func (v NullableNativeNameDetail) Get() *NativeNameDetail {
	return v.value
}

func (v *NullableNativeNameDetail) Set(val *NativeNameDetail) {
	v.value = val
	v.isSet = true
}

func (v NullableNativeNameDetail) IsSet() bool {
	return v.isSet
}

func (v *NullableNativeNameDetail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNativeNameDetail(val *NativeNameDetail) *NullableNativeNameDetail {
	return &NullableNativeNameDetail{value: val, isSet: true}
}

func (v NullableNativeNameDetail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNativeNameDetail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


