/*
REST Countries — Countries API (v5)

Read-only country data API. All endpoints are GET, JSON-only, and follow a JSON:API-like envelope: successful payloads sit under a top-level `data` key with `data.objects` (array of Country records) and `data.meta` (pagination block). Failures return an `errors` array of objects carrying a `message`. Authentication is a bearer API key. Spec written against https://restcountries.com/docs/countries (July 2026) and cross-checked against a live v5 record. 

API version: 5.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package restcountries

import (
	"encoding/json"
)

// checks if the CountryCars type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CountryCars{}

// CountryCars struct for CountryCars
type CountryCars struct {
	DrivingSide *string `json:"driving_side,omitempty"`
	Signs []string `json:"signs,omitempty"`
}

// NewCountryCars instantiates a new CountryCars object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCountryCars() *CountryCars {
	this := CountryCars{}
	return &this
}

// NewCountryCarsWithDefaults instantiates a new CountryCars object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCountryCarsWithDefaults() *CountryCars {
	this := CountryCars{}
	return &this
}

// GetDrivingSide returns the DrivingSide field value if set, zero value otherwise.
func (o *CountryCars) GetDrivingSide() string {
	if o == nil || IsNil(o.DrivingSide) {
		var ret string
		return ret
	}
	return *o.DrivingSide
}

// GetDrivingSideOk returns a tuple with the DrivingSide field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CountryCars) GetDrivingSideOk() (*string, bool) {
	if o == nil || IsNil(o.DrivingSide) {
		return nil, false
	}
	return o.DrivingSide, true
}

// HasDrivingSide returns a boolean if a field has been set.
func (o *CountryCars) HasDrivingSide() bool {
	if o != nil && !IsNil(o.DrivingSide) {
		return true
	}

	return false
}

// SetDrivingSide gets a reference to the given string and assigns it to the DrivingSide field.
func (o *CountryCars) SetDrivingSide(v string) {
	o.DrivingSide = &v
}

// GetSigns returns the Signs field value if set, zero value otherwise.
func (o *CountryCars) GetSigns() []string {
	if o == nil || IsNil(o.Signs) {
		var ret []string
		return ret
	}
	return o.Signs
}

// GetSignsOk returns a tuple with the Signs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CountryCars) GetSignsOk() ([]string, bool) {
	if o == nil || IsNil(o.Signs) {
		return nil, false
	}
	return o.Signs, true
}

// HasSigns returns a boolean if a field has been set.
func (o *CountryCars) HasSigns() bool {
	if o != nil && !IsNil(o.Signs) {
		return true
	}

	return false
}

// SetSigns gets a reference to the given []string and assigns it to the Signs field.
func (o *CountryCars) SetSigns(v []string) {
	o.Signs = v
}

func (o CountryCars) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CountryCars) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DrivingSide) {
		toSerialize["driving_side"] = o.DrivingSide
	}
	if !IsNil(o.Signs) {
		toSerialize["signs"] = o.Signs
	}
	return toSerialize, nil
}

type NullableCountryCars struct {
	value *CountryCars
	isSet bool
}

func (v NullableCountryCars) Get() *CountryCars {
	return v.value
}

func (v *NullableCountryCars) Set(val *CountryCars) {
	v.value = val
	v.isSet = true
}

func (v NullableCountryCars) IsSet() bool {
	return v.isSet
}

func (v *NullableCountryCars) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCountryCars(val *CountryCars) *NullableCountryCars {
	return &NullableCountryCars{value: val, isSet: true}
}

func (v NullableCountryCars) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCountryCars) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


