/*
REST Countries — Countries API (v5)

Read-only country data API. All endpoints are GET, JSON-only, and follow a JSON:API-like envelope: successful payloads sit under a top-level `data` key with `data.objects` (array of Country records) and `data.meta` (pagination block). Failures return an `errors` array of objects carrying a `message`. Authentication is a bearer API key. Spec written against https://restcountries.com/docs/countries (July 2026) and cross-checked against a live v5 record. 

API version: 5.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package restcountries

import (
	"encoding/json"
)

// checks if the MonthDay type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MonthDay{}

// MonthDay struct for MonthDay
type MonthDay struct {
	Month *int32 `json:"month,omitempty"`
	Day *int32 `json:"day,omitempty"`
}

// NewMonthDay instantiates a new MonthDay object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMonthDay() *MonthDay {
	this := MonthDay{}
	return &this
}

// NewMonthDayWithDefaults instantiates a new MonthDay object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMonthDayWithDefaults() *MonthDay {
	this := MonthDay{}
	return &this
}

// GetMonth returns the Month field value if set, zero value otherwise.
func (o *MonthDay) GetMonth() int32 {
	if o == nil || IsNil(o.Month) {
		var ret int32
		return ret
	}
	return *o.Month
}

// GetMonthOk returns a tuple with the Month field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MonthDay) GetMonthOk() (*int32, bool) {
	if o == nil || IsNil(o.Month) {
		return nil, false
	}
	return o.Month, true
}

// HasMonth returns a boolean if a field has been set.
func (o *MonthDay) HasMonth() bool {
	if o != nil && !IsNil(o.Month) {
		return true
	}

	return false
}

// SetMonth gets a reference to the given int32 and assigns it to the Month field.
func (o *MonthDay) SetMonth(v int32) {
	o.Month = &v
}

// GetDay returns the Day field value if set, zero value otherwise.
func (o *MonthDay) GetDay() int32 {
	if o == nil || IsNil(o.Day) {
		var ret int32
		return ret
	}
	return *o.Day
}

// GetDayOk returns a tuple with the Day field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MonthDay) GetDayOk() (*int32, bool) {
	if o == nil || IsNil(o.Day) {
		return nil, false
	}
	return o.Day, true
}

// HasDay returns a boolean if a field has been set.
func (o *MonthDay) HasDay() bool {
	if o != nil && !IsNil(o.Day) {
		return true
	}

	return false
}

// SetDay gets a reference to the given int32 and assigns it to the Day field.
func (o *MonthDay) SetDay(v int32) {
	o.Day = &v
}

func (o MonthDay) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MonthDay) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Month) {
		toSerialize["month"] = o.Month
	}
	if !IsNil(o.Day) {
		toSerialize["day"] = o.Day
	}
	return toSerialize, nil
}

type NullableMonthDay struct {
	value *MonthDay
	isSet bool
}

func (v NullableMonthDay) Get() *MonthDay {
	return v.value
}

func (v *NullableMonthDay) Set(val *MonthDay) {
	v.value = val
	v.isSet = true
}

func (v NullableMonthDay) IsSet() bool {
	return v.isSet
}

func (v *NullableMonthDay) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMonthDay(val *MonthDay) *NullableMonthDay {
	return &NullableMonthDay{value: val, isSet: true}
}

func (v NullableMonthDay) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMonthDay) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


