/*
OpenAPI Example

This is an  OpenAPI specification for Rest Countries API.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CurrenciesDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CurrenciesDetails{}

// CurrenciesDetails struct for CurrenciesDetails
type CurrenciesDetails struct {
	Name *string `json:"name,omitempty"`
	Symbol *string `json:"symbol,omitempty"`
}

// NewCurrenciesDetails instantiates a new CurrenciesDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCurrenciesDetails() *CurrenciesDetails {
	this := CurrenciesDetails{}
	return &this
}

// NewCurrenciesDetailsWithDefaults instantiates a new CurrenciesDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCurrenciesDetailsWithDefaults() *CurrenciesDetails {
	this := CurrenciesDetails{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CurrenciesDetails) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CurrenciesDetails) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CurrenciesDetails) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CurrenciesDetails) SetName(v string) {
	o.Name = &v
}

// GetSymbol returns the Symbol field value if set, zero value otherwise.
func (o *CurrenciesDetails) GetSymbol() string {
	if o == nil || IsNil(o.Symbol) {
		var ret string
		return ret
	}
	return *o.Symbol
}

// GetSymbolOk returns a tuple with the Symbol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CurrenciesDetails) GetSymbolOk() (*string, bool) {
	if o == nil || IsNil(o.Symbol) {
		return nil, false
	}
	return o.Symbol, true
}

// HasSymbol returns a boolean if a field has been set.
func (o *CurrenciesDetails) HasSymbol() bool {
	if o != nil && !IsNil(o.Symbol) {
		return true
	}

	return false
}

// SetSymbol gets a reference to the given string and assigns it to the Symbol field.
func (o *CurrenciesDetails) SetSymbol(v string) {
	o.Symbol = &v
}

func (o CurrenciesDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CurrenciesDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Symbol) {
		toSerialize["symbol"] = o.Symbol
	}
	return toSerialize, nil
}

type NullableCurrenciesDetails struct {
	value *CurrenciesDetails
	isSet bool
}

func (v NullableCurrenciesDetails) Get() *CurrenciesDetails {
	return v.value
}

func (v *NullableCurrenciesDetails) Set(val *CurrenciesDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableCurrenciesDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableCurrenciesDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCurrenciesDetails(val *CurrenciesDetails) *NullableCurrenciesDetails {
	return &NullableCurrenciesDetails{value: val, isSet: true}
}

func (v NullableCurrenciesDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCurrenciesDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


