/*
OpenAPI Example

This is an  OpenAPI specification for Rest Countries API.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AllresponsebodyInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AllresponsebodyInner{}

// AllresponsebodyInner struct for AllresponsebodyInner
type AllresponsebodyInner struct {
	Name *NameDetails `json:"name,omitempty"`
	Tld []string `json:"tld,omitempty"`
	Cca2 *string `json:"cca2,omitempty"`
	Cca3 *string `json:"cca3,omitempty"`
	Ccn3 *string `json:"ccn3,omitempty"`
	Cioc *string `json:"cioc,omitempty"`
	Currencies *map[string]CurrenciesDetails `json:"currencies,omitempty"`
	Region *string `json:"region,omitempty"`
	Independent *bool `json:"independent,omitempty"`
	UnMember *bool `json:"unMember,omitempty"`
	Capital []string `json:"capital,omitempty"`
	Latlng []float32 `json:"latlng,omitempty"`
	Area *float32 `json:"area,omitempty"`
	Population *float32 `json:"population,omitempty"`
	Flags *AllresponsebodyInnerFlags `json:"flags,omitempty"`
	Flag *string `json:"flag,omitempty"`
	Landlocked *bool `json:"landlocked,omitempty"`
	Borders []string `json:"borders,omitempty"`
	Translations *map[string]NativeNameDetail `json:"translations,omitempty"`
	Demonyms *map[string]DemonymsDetails `json:"demonyms,omitempty"`
	Timezones []string `json:"timezones,omitempty"`
	Continents []string `json:"continents,omitempty"`
	Fifa *string `json:"fifa,omitempty"`
	Car *CarDetails `json:"car,omitempty"`
	CoatOfArms *ImageDetails `json:"coatOfArms,omitempty"`
	StartOfWeek *string `json:"startOfWeek,omitempty"`
	CapitalInfo *AllresponsebodyInnerCapitalInfo `json:"capitalInfo,omitempty"`
	Maps *MapsDetails `json:"maps,omitempty"`
	Gini *map[string]float32 `json:"gini,omitempty"`
	Status *string `json:"status,omitempty"`
	Subregion *string `json:"subregion,omitempty"`
	AltSpellings []string `json:"altSpellings,omitempty"`
	Idd *IddDetails `json:"idd,omitempty"`
	PostalCode *PostalCodeDetails `json:"postalCode,omitempty"`
	Languages *map[string]string `json:"languages,omitempty"`
}

// NewAllresponsebodyInner instantiates a new AllresponsebodyInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAllresponsebodyInner() *AllresponsebodyInner {
	this := AllresponsebodyInner{}
	return &this
}

// NewAllresponsebodyInnerWithDefaults instantiates a new AllresponsebodyInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAllresponsebodyInnerWithDefaults() *AllresponsebodyInner {
	this := AllresponsebodyInner{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *AllresponsebodyInner) GetName() NameDetails {
	if o == nil || IsNil(o.Name) {
		var ret NameDetails
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AllresponsebodyInner) GetNameOk() (*NameDetails, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *AllresponsebodyInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given NameDetails and assigns it to the Name field.
func (o *AllresponsebodyInner) SetName(v NameDetails) {
	o.Name = &v
}

// GetTld returns the Tld field value if set, zero value otherwise.
func (o *AllresponsebodyInner) GetTld() []string {
	if o == nil || IsNil(o.Tld) {
		var ret []string
		return ret
	}
	return o.Tld
}

// GetTldOk returns a tuple with the Tld field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AllresponsebodyInner) GetTldOk() ([]string, bool) {
	if o == nil || IsNil(o.Tld) {
		return nil, false
	}
	return o.Tld, true
}

// HasTld returns a boolean if a field has been set.
func (o *AllresponsebodyInner) HasTld() bool {
	if o != nil && !IsNil(o.Tld) {
		return true
	}

	return false
}

// SetTld gets a reference to the given []string and assigns it to the Tld field.
func (o *AllresponsebodyInner) SetTld(v []string) {
	o.Tld = v
}

// GetCca2 returns the Cca2 field value if set, zero value otherwise.
func (o *AllresponsebodyInner) GetCca2() string {
	if o == nil || IsNil(o.Cca2) {
		var ret string
		return ret
	}
	return *o.Cca2
}

// GetCca2Ok returns a tuple with the Cca2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AllresponsebodyInner) GetCca2Ok() (*string, bool) {
	if o == nil || IsNil(o.Cca2) {
		return nil, false
	}
	return o.Cca2, true
}

// HasCca2 returns a boolean if a field has been set.
func (o *AllresponsebodyInner) HasCca2() bool {
	if o != nil && !IsNil(o.Cca2) {
		return true
	}

	return false
}

// SetCca2 gets a reference to the given string and assigns it to the Cca2 field.
func (o *AllresponsebodyInner) SetCca2(v string) {
	o.Cca2 = &v
}

// GetCca3 returns the Cca3 field value if set, zero value otherwise.
func (o *AllresponsebodyInner) GetCca3() string {
	if o == nil || IsNil(o.Cca3) {
		var ret string
		return ret
	}
	return *o.Cca3
}

// GetCca3Ok returns a tuple with the Cca3 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AllresponsebodyInner) GetCca3Ok() (*string, bool) {
	if o == nil || IsNil(o.Cca3) {
		return nil, false
	}
	return o.Cca3, true
}

// HasCca3 returns a boolean if a field has been set.
func (o *AllresponsebodyInner) HasCca3() bool {
	if o != nil && !IsNil(o.Cca3) {
		return true
	}

	return false
}

// SetCca3 gets a reference to the given string and assigns it to the Cca3 field.
func (o *AllresponsebodyInner) SetCca3(v string) {
	o.Cca3 = &v
}

// GetCcn3 returns the Ccn3 field value if set, zero value otherwise.
func (o *AllresponsebodyInner) GetCcn3() string {
	if o == nil || IsNil(o.Ccn3) {
		var ret string
		return ret
	}
	return *o.Ccn3
}

// GetCcn3Ok returns a tuple with the Ccn3 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AllresponsebodyInner) GetCcn3Ok() (*string, bool) {
	if o == nil || IsNil(o.Ccn3) {
		return nil, false
	}
	return o.Ccn3, true
}

// HasCcn3 returns a boolean if a field has been set.
func (o *AllresponsebodyInner) HasCcn3() bool {
	if o != nil && !IsNil(o.Ccn3) {
		return true
	}

	return false
}

// SetCcn3 gets a reference to the given string and assigns it to the Ccn3 field.
func (o *AllresponsebodyInner) SetCcn3(v string) {
	o.Ccn3 = &v
}

// GetCioc returns the Cioc field value if set, zero value otherwise.
func (o *AllresponsebodyInner) GetCioc() string {
	if o == nil || IsNil(o.Cioc) {
		var ret string
		return ret
	}
	return *o.Cioc
}

// GetCiocOk returns a tuple with the Cioc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AllresponsebodyInner) GetCiocOk() (*string, bool) {
	if o == nil || IsNil(o.Cioc) {
		return nil, false
	}
	return o.Cioc, true
}

// HasCioc returns a boolean if a field has been set.
func (o *AllresponsebodyInner) HasCioc() bool {
	if o != nil && !IsNil(o.Cioc) {
		return true
	}

	return false
}

// SetCioc gets a reference to the given string and assigns it to the Cioc field.
func (o *AllresponsebodyInner) SetCioc(v string) {
	o.Cioc = &v
}

// GetCurrencies returns the Currencies field value if set, zero value otherwise.
func (o *AllresponsebodyInner) GetCurrencies() map[string]CurrenciesDetails {
	if o == nil || IsNil(o.Currencies) {
		var ret map[string]CurrenciesDetails
		return ret
	}
	return *o.Currencies
}

// GetCurrenciesOk returns a tuple with the Currencies field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AllresponsebodyInner) GetCurrenciesOk() (*map[string]CurrenciesDetails, bool) {
	if o == nil || IsNil(o.Currencies) {
		return nil, false
	}
	return o.Currencies, true
}

// HasCurrencies returns a boolean if a field has been set.
func (o *AllresponsebodyInner) HasCurrencies() bool {
	if o != nil && !IsNil(o.Currencies) {
		return true
	}

	return false
}

// SetCurrencies gets a reference to the given map[string]CurrenciesDetails and assigns it to the Currencies field.
func (o *AllresponsebodyInner) SetCurrencies(v map[string]CurrenciesDetails) {
	o.Currencies = &v
}

// GetRegion returns the Region field value if set, zero value otherwise.
func (o *AllresponsebodyInner) GetRegion() string {
	if o == nil || IsNil(o.Region) {
		var ret string
		return ret
	}
	return *o.Region
}

// GetRegionOk returns a tuple with the Region field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AllresponsebodyInner) GetRegionOk() (*string, bool) {
	if o == nil || IsNil(o.Region) {
		return nil, false
	}
	return o.Region, true
}

// HasRegion returns a boolean if a field has been set.
func (o *AllresponsebodyInner) HasRegion() bool {
	if o != nil && !IsNil(o.Region) {
		return true
	}

	return false
}

// SetRegion gets a reference to the given string and assigns it to the Region field.
func (o *AllresponsebodyInner) SetRegion(v string) {
	o.Region = &v
}

// GetIndependent returns the Independent field value if set, zero value otherwise.
func (o *AllresponsebodyInner) GetIndependent() bool {
	if o == nil || IsNil(o.Independent) {
		var ret bool
		return ret
	}
	return *o.Independent
}

// GetIndependentOk returns a tuple with the Independent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AllresponsebodyInner) GetIndependentOk() (*bool, bool) {
	if o == nil || IsNil(o.Independent) {
		return nil, false
	}
	return o.Independent, true
}

// HasIndependent returns a boolean if a field has been set.
func (o *AllresponsebodyInner) HasIndependent() bool {
	if o != nil && !IsNil(o.Independent) {
		return true
	}

	return false
}

// SetIndependent gets a reference to the given bool and assigns it to the Independent field.
func (o *AllresponsebodyInner) SetIndependent(v bool) {
	o.Independent = &v
}

// GetUnMember returns the UnMember field value if set, zero value otherwise.
func (o *AllresponsebodyInner) GetUnMember() bool {
	if o == nil || IsNil(o.UnMember) {
		var ret bool
		return ret
	}
	return *o.UnMember
}

// GetUnMemberOk returns a tuple with the UnMember field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AllresponsebodyInner) GetUnMemberOk() (*bool, bool) {
	if o == nil || IsNil(o.UnMember) {
		return nil, false
	}
	return o.UnMember, true
}

// HasUnMember returns a boolean if a field has been set.
func (o *AllresponsebodyInner) HasUnMember() bool {
	if o != nil && !IsNil(o.UnMember) {
		return true
	}

	return false
}

// SetUnMember gets a reference to the given bool and assigns it to the UnMember field.
func (o *AllresponsebodyInner) SetUnMember(v bool) {
	o.UnMember = &v
}

// GetCapital returns the Capital field value if set, zero value otherwise.
func (o *AllresponsebodyInner) GetCapital() []string {
	if o == nil || IsNil(o.Capital) {
		var ret []string
		return ret
	}
	return o.Capital
}

// GetCapitalOk returns a tuple with the Capital field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AllresponsebodyInner) GetCapitalOk() ([]string, bool) {
	if o == nil || IsNil(o.Capital) {
		return nil, false
	}
	return o.Capital, true
}

// HasCapital returns a boolean if a field has been set.
func (o *AllresponsebodyInner) HasCapital() bool {
	if o != nil && !IsNil(o.Capital) {
		return true
	}

	return false
}

// SetCapital gets a reference to the given []string and assigns it to the Capital field.
func (o *AllresponsebodyInner) SetCapital(v []string) {
	o.Capital = v
}

// GetLatlng returns the Latlng field value if set, zero value otherwise.
func (o *AllresponsebodyInner) GetLatlng() []float32 {
	if o == nil || IsNil(o.Latlng) {
		var ret []float32
		return ret
	}
	return o.Latlng
}

// GetLatlngOk returns a tuple with the Latlng field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AllresponsebodyInner) GetLatlngOk() ([]float32, bool) {
	if o == nil || IsNil(o.Latlng) {
		return nil, false
	}
	return o.Latlng, true
}

// HasLatlng returns a boolean if a field has been set.
func (o *AllresponsebodyInner) HasLatlng() bool {
	if o != nil && !IsNil(o.Latlng) {
		return true
	}

	return false
}

// SetLatlng gets a reference to the given []float32 and assigns it to the Latlng field.
func (o *AllresponsebodyInner) SetLatlng(v []float32) {
	o.Latlng = v
}

// GetArea returns the Area field value if set, zero value otherwise.
func (o *AllresponsebodyInner) GetArea() float32 {
	if o == nil || IsNil(o.Area) {
		var ret float32
		return ret
	}
	return *o.Area
}

// GetAreaOk returns a tuple with the Area field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AllresponsebodyInner) GetAreaOk() (*float32, bool) {
	if o == nil || IsNil(o.Area) {
		return nil, false
	}
	return o.Area, true
}

// HasArea returns a boolean if a field has been set.
func (o *AllresponsebodyInner) HasArea() bool {
	if o != nil && !IsNil(o.Area) {
		return true
	}

	return false
}

// SetArea gets a reference to the given float32 and assigns it to the Area field.
func (o *AllresponsebodyInner) SetArea(v float32) {
	o.Area = &v
}

// GetPopulation returns the Population field value if set, zero value otherwise.
func (o *AllresponsebodyInner) GetPopulation() float32 {
	if o == nil || IsNil(o.Population) {
		var ret float32
		return ret
	}
	return *o.Population
}

// GetPopulationOk returns a tuple with the Population field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AllresponsebodyInner) GetPopulationOk() (*float32, bool) {
	if o == nil || IsNil(o.Population) {
		return nil, false
	}
	return o.Population, true
}

// HasPopulation returns a boolean if a field has been set.
func (o *AllresponsebodyInner) HasPopulation() bool {
	if o != nil && !IsNil(o.Population) {
		return true
	}

	return false
}

// SetPopulation gets a reference to the given float32 and assigns it to the Population field.
func (o *AllresponsebodyInner) SetPopulation(v float32) {
	o.Population = &v
}

// GetFlags returns the Flags field value if set, zero value otherwise.
func (o *AllresponsebodyInner) GetFlags() AllresponsebodyInnerFlags {
	if o == nil || IsNil(o.Flags) {
		var ret AllresponsebodyInnerFlags
		return ret
	}
	return *o.Flags
}

// GetFlagsOk returns a tuple with the Flags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AllresponsebodyInner) GetFlagsOk() (*AllresponsebodyInnerFlags, bool) {
	if o == nil || IsNil(o.Flags) {
		return nil, false
	}
	return o.Flags, true
}

// HasFlags returns a boolean if a field has been set.
func (o *AllresponsebodyInner) HasFlags() bool {
	if o != nil && !IsNil(o.Flags) {
		return true
	}

	return false
}

// SetFlags gets a reference to the given AllresponsebodyInnerFlags and assigns it to the Flags field.
func (o *AllresponsebodyInner) SetFlags(v AllresponsebodyInnerFlags) {
	o.Flags = &v
}

// GetFlag returns the Flag field value if set, zero value otherwise.
func (o *AllresponsebodyInner) GetFlag() string {
	if o == nil || IsNil(o.Flag) {
		var ret string
		return ret
	}
	return *o.Flag
}

// GetFlagOk returns a tuple with the Flag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AllresponsebodyInner) GetFlagOk() (*string, bool) {
	if o == nil || IsNil(o.Flag) {
		return nil, false
	}
	return o.Flag, true
}

// HasFlag returns a boolean if a field has been set.
func (o *AllresponsebodyInner) HasFlag() bool {
	if o != nil && !IsNil(o.Flag) {
		return true
	}

	return false
}

// SetFlag gets a reference to the given string and assigns it to the Flag field.
func (o *AllresponsebodyInner) SetFlag(v string) {
	o.Flag = &v
}

// GetLandlocked returns the Landlocked field value if set, zero value otherwise.
func (o *AllresponsebodyInner) GetLandlocked() bool {
	if o == nil || IsNil(o.Landlocked) {
		var ret bool
		return ret
	}
	return *o.Landlocked
}

// GetLandlockedOk returns a tuple with the Landlocked field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AllresponsebodyInner) GetLandlockedOk() (*bool, bool) {
	if o == nil || IsNil(o.Landlocked) {
		return nil, false
	}
	return o.Landlocked, true
}

// HasLandlocked returns a boolean if a field has been set.
func (o *AllresponsebodyInner) HasLandlocked() bool {
	if o != nil && !IsNil(o.Landlocked) {
		return true
	}

	return false
}

// SetLandlocked gets a reference to the given bool and assigns it to the Landlocked field.
func (o *AllresponsebodyInner) SetLandlocked(v bool) {
	o.Landlocked = &v
}

// GetBorders returns the Borders field value if set, zero value otherwise.
func (o *AllresponsebodyInner) GetBorders() []string {
	if o == nil || IsNil(o.Borders) {
		var ret []string
		return ret
	}
	return o.Borders
}

// GetBordersOk returns a tuple with the Borders field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AllresponsebodyInner) GetBordersOk() ([]string, bool) {
	if o == nil || IsNil(o.Borders) {
		return nil, false
	}
	return o.Borders, true
}

// HasBorders returns a boolean if a field has been set.
func (o *AllresponsebodyInner) HasBorders() bool {
	if o != nil && !IsNil(o.Borders) {
		return true
	}

	return false
}

// SetBorders gets a reference to the given []string and assigns it to the Borders field.
func (o *AllresponsebodyInner) SetBorders(v []string) {
	o.Borders = v
}

// GetTranslations returns the Translations field value if set, zero value otherwise.
func (o *AllresponsebodyInner) GetTranslations() map[string]NativeNameDetail {
	if o == nil || IsNil(o.Translations) {
		var ret map[string]NativeNameDetail
		return ret
	}
	return *o.Translations
}

// GetTranslationsOk returns a tuple with the Translations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AllresponsebodyInner) GetTranslationsOk() (*map[string]NativeNameDetail, bool) {
	if o == nil || IsNil(o.Translations) {
		return nil, false
	}
	return o.Translations, true
}

// HasTranslations returns a boolean if a field has been set.
func (o *AllresponsebodyInner) HasTranslations() bool {
	if o != nil && !IsNil(o.Translations) {
		return true
	}

	return false
}

// SetTranslations gets a reference to the given map[string]NativeNameDetail and assigns it to the Translations field.
func (o *AllresponsebodyInner) SetTranslations(v map[string]NativeNameDetail) {
	o.Translations = &v
}

// GetDemonyms returns the Demonyms field value if set, zero value otherwise.
func (o *AllresponsebodyInner) GetDemonyms() map[string]DemonymsDetails {
	if o == nil || IsNil(o.Demonyms) {
		var ret map[string]DemonymsDetails
		return ret
	}
	return *o.Demonyms
}

// GetDemonymsOk returns a tuple with the Demonyms field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AllresponsebodyInner) GetDemonymsOk() (*map[string]DemonymsDetails, bool) {
	if o == nil || IsNil(o.Demonyms) {
		return nil, false
	}
	return o.Demonyms, true
}

// HasDemonyms returns a boolean if a field has been set.
func (o *AllresponsebodyInner) HasDemonyms() bool {
	if o != nil && !IsNil(o.Demonyms) {
		return true
	}

	return false
}

// SetDemonyms gets a reference to the given map[string]DemonymsDetails and assigns it to the Demonyms field.
func (o *AllresponsebodyInner) SetDemonyms(v map[string]DemonymsDetails) {
	o.Demonyms = &v
}

// GetTimezones returns the Timezones field value if set, zero value otherwise.
func (o *AllresponsebodyInner) GetTimezones() []string {
	if o == nil || IsNil(o.Timezones) {
		var ret []string
		return ret
	}
	return o.Timezones
}

// GetTimezonesOk returns a tuple with the Timezones field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AllresponsebodyInner) GetTimezonesOk() ([]string, bool) {
	if o == nil || IsNil(o.Timezones) {
		return nil, false
	}
	return o.Timezones, true
}

// HasTimezones returns a boolean if a field has been set.
func (o *AllresponsebodyInner) HasTimezones() bool {
	if o != nil && !IsNil(o.Timezones) {
		return true
	}

	return false
}

// SetTimezones gets a reference to the given []string and assigns it to the Timezones field.
func (o *AllresponsebodyInner) SetTimezones(v []string) {
	o.Timezones = v
}

// GetContinents returns the Continents field value if set, zero value otherwise.
func (o *AllresponsebodyInner) GetContinents() []string {
	if o == nil || IsNil(o.Continents) {
		var ret []string
		return ret
	}
	return o.Continents
}

// GetContinentsOk returns a tuple with the Continents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AllresponsebodyInner) GetContinentsOk() ([]string, bool) {
	if o == nil || IsNil(o.Continents) {
		return nil, false
	}
	return o.Continents, true
}

// HasContinents returns a boolean if a field has been set.
func (o *AllresponsebodyInner) HasContinents() bool {
	if o != nil && !IsNil(o.Continents) {
		return true
	}

	return false
}

// SetContinents gets a reference to the given []string and assigns it to the Continents field.
func (o *AllresponsebodyInner) SetContinents(v []string) {
	o.Continents = v
}

// GetFifa returns the Fifa field value if set, zero value otherwise.
func (o *AllresponsebodyInner) GetFifa() string {
	if o == nil || IsNil(o.Fifa) {
		var ret string
		return ret
	}
	return *o.Fifa
}

// GetFifaOk returns a tuple with the Fifa field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AllresponsebodyInner) GetFifaOk() (*string, bool) {
	if o == nil || IsNil(o.Fifa) {
		return nil, false
	}
	return o.Fifa, true
}

// HasFifa returns a boolean if a field has been set.
func (o *AllresponsebodyInner) HasFifa() bool {
	if o != nil && !IsNil(o.Fifa) {
		return true
	}

	return false
}

// SetFifa gets a reference to the given string and assigns it to the Fifa field.
func (o *AllresponsebodyInner) SetFifa(v string) {
	o.Fifa = &v
}

// GetCar returns the Car field value if set, zero value otherwise.
func (o *AllresponsebodyInner) GetCar() CarDetails {
	if o == nil || IsNil(o.Car) {
		var ret CarDetails
		return ret
	}
	return *o.Car
}

// GetCarOk returns a tuple with the Car field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AllresponsebodyInner) GetCarOk() (*CarDetails, bool) {
	if o == nil || IsNil(o.Car) {
		return nil, false
	}
	return o.Car, true
}

// HasCar returns a boolean if a field has been set.
func (o *AllresponsebodyInner) HasCar() bool {
	if o != nil && !IsNil(o.Car) {
		return true
	}

	return false
}

// SetCar gets a reference to the given CarDetails and assigns it to the Car field.
func (o *AllresponsebodyInner) SetCar(v CarDetails) {
	o.Car = &v
}

// GetCoatOfArms returns the CoatOfArms field value if set, zero value otherwise.
func (o *AllresponsebodyInner) GetCoatOfArms() ImageDetails {
	if o == nil || IsNil(o.CoatOfArms) {
		var ret ImageDetails
		return ret
	}
	return *o.CoatOfArms
}

// GetCoatOfArmsOk returns a tuple with the CoatOfArms field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AllresponsebodyInner) GetCoatOfArmsOk() (*ImageDetails, bool) {
	if o == nil || IsNil(o.CoatOfArms) {
		return nil, false
	}
	return o.CoatOfArms, true
}

// HasCoatOfArms returns a boolean if a field has been set.
func (o *AllresponsebodyInner) HasCoatOfArms() bool {
	if o != nil && !IsNil(o.CoatOfArms) {
		return true
	}

	return false
}

// SetCoatOfArms gets a reference to the given ImageDetails and assigns it to the CoatOfArms field.
func (o *AllresponsebodyInner) SetCoatOfArms(v ImageDetails) {
	o.CoatOfArms = &v
}

// GetStartOfWeek returns the StartOfWeek field value if set, zero value otherwise.
func (o *AllresponsebodyInner) GetStartOfWeek() string {
	if o == nil || IsNil(o.StartOfWeek) {
		var ret string
		return ret
	}
	return *o.StartOfWeek
}

// GetStartOfWeekOk returns a tuple with the StartOfWeek field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AllresponsebodyInner) GetStartOfWeekOk() (*string, bool) {
	if o == nil || IsNil(o.StartOfWeek) {
		return nil, false
	}
	return o.StartOfWeek, true
}

// HasStartOfWeek returns a boolean if a field has been set.
func (o *AllresponsebodyInner) HasStartOfWeek() bool {
	if o != nil && !IsNil(o.StartOfWeek) {
		return true
	}

	return false
}

// SetStartOfWeek gets a reference to the given string and assigns it to the StartOfWeek field.
func (o *AllresponsebodyInner) SetStartOfWeek(v string) {
	o.StartOfWeek = &v
}

// GetCapitalInfo returns the CapitalInfo field value if set, zero value otherwise.
func (o *AllresponsebodyInner) GetCapitalInfo() AllresponsebodyInnerCapitalInfo {
	if o == nil || IsNil(o.CapitalInfo) {
		var ret AllresponsebodyInnerCapitalInfo
		return ret
	}
	return *o.CapitalInfo
}

// GetCapitalInfoOk returns a tuple with the CapitalInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AllresponsebodyInner) GetCapitalInfoOk() (*AllresponsebodyInnerCapitalInfo, bool) {
	if o == nil || IsNil(o.CapitalInfo) {
		return nil, false
	}
	return o.CapitalInfo, true
}

// HasCapitalInfo returns a boolean if a field has been set.
func (o *AllresponsebodyInner) HasCapitalInfo() bool {
	if o != nil && !IsNil(o.CapitalInfo) {
		return true
	}

	return false
}

// SetCapitalInfo gets a reference to the given AllresponsebodyInnerCapitalInfo and assigns it to the CapitalInfo field.
func (o *AllresponsebodyInner) SetCapitalInfo(v AllresponsebodyInnerCapitalInfo) {
	o.CapitalInfo = &v
}

// GetMaps returns the Maps field value if set, zero value otherwise.
func (o *AllresponsebodyInner) GetMaps() MapsDetails {
	if o == nil || IsNil(o.Maps) {
		var ret MapsDetails
		return ret
	}
	return *o.Maps
}

// GetMapsOk returns a tuple with the Maps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AllresponsebodyInner) GetMapsOk() (*MapsDetails, bool) {
	if o == nil || IsNil(o.Maps) {
		return nil, false
	}
	return o.Maps, true
}

// HasMaps returns a boolean if a field has been set.
func (o *AllresponsebodyInner) HasMaps() bool {
	if o != nil && !IsNil(o.Maps) {
		return true
	}

	return false
}

// SetMaps gets a reference to the given MapsDetails and assigns it to the Maps field.
func (o *AllresponsebodyInner) SetMaps(v MapsDetails) {
	o.Maps = &v
}

// GetGini returns the Gini field value if set, zero value otherwise.
func (o *AllresponsebodyInner) GetGini() map[string]float32 {
	if o == nil || IsNil(o.Gini) {
		var ret map[string]float32
		return ret
	}
	return *o.Gini
}

// GetGiniOk returns a tuple with the Gini field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AllresponsebodyInner) GetGiniOk() (*map[string]float32, bool) {
	if o == nil || IsNil(o.Gini) {
		return nil, false
	}
	return o.Gini, true
}

// HasGini returns a boolean if a field has been set.
func (o *AllresponsebodyInner) HasGini() bool {
	if o != nil && !IsNil(o.Gini) {
		return true
	}

	return false
}

// SetGini gets a reference to the given map[string]float32 and assigns it to the Gini field.
func (o *AllresponsebodyInner) SetGini(v map[string]float32) {
	o.Gini = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *AllresponsebodyInner) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AllresponsebodyInner) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *AllresponsebodyInner) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *AllresponsebodyInner) SetStatus(v string) {
	o.Status = &v
}

// GetSubregion returns the Subregion field value if set, zero value otherwise.
func (o *AllresponsebodyInner) GetSubregion() string {
	if o == nil || IsNil(o.Subregion) {
		var ret string
		return ret
	}
	return *o.Subregion
}

// GetSubregionOk returns a tuple with the Subregion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AllresponsebodyInner) GetSubregionOk() (*string, bool) {
	if o == nil || IsNil(o.Subregion) {
		return nil, false
	}
	return o.Subregion, true
}

// HasSubregion returns a boolean if a field has been set.
func (o *AllresponsebodyInner) HasSubregion() bool {
	if o != nil && !IsNil(o.Subregion) {
		return true
	}

	return false
}

// SetSubregion gets a reference to the given string and assigns it to the Subregion field.
func (o *AllresponsebodyInner) SetSubregion(v string) {
	o.Subregion = &v
}

// GetAltSpellings returns the AltSpellings field value if set, zero value otherwise.
func (o *AllresponsebodyInner) GetAltSpellings() []string {
	if o == nil || IsNil(o.AltSpellings) {
		var ret []string
		return ret
	}
	return o.AltSpellings
}

// GetAltSpellingsOk returns a tuple with the AltSpellings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AllresponsebodyInner) GetAltSpellingsOk() ([]string, bool) {
	if o == nil || IsNil(o.AltSpellings) {
		return nil, false
	}
	return o.AltSpellings, true
}

// HasAltSpellings returns a boolean if a field has been set.
func (o *AllresponsebodyInner) HasAltSpellings() bool {
	if o != nil && !IsNil(o.AltSpellings) {
		return true
	}

	return false
}

// SetAltSpellings gets a reference to the given []string and assigns it to the AltSpellings field.
func (o *AllresponsebodyInner) SetAltSpellings(v []string) {
	o.AltSpellings = v
}

// GetIdd returns the Idd field value if set, zero value otherwise.
func (o *AllresponsebodyInner) GetIdd() IddDetails {
	if o == nil || IsNil(o.Idd) {
		var ret IddDetails
		return ret
	}
	return *o.Idd
}

// GetIddOk returns a tuple with the Idd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AllresponsebodyInner) GetIddOk() (*IddDetails, bool) {
	if o == nil || IsNil(o.Idd) {
		return nil, false
	}
	return o.Idd, true
}

// HasIdd returns a boolean if a field has been set.
func (o *AllresponsebodyInner) HasIdd() bool {
	if o != nil && !IsNil(o.Idd) {
		return true
	}

	return false
}

// SetIdd gets a reference to the given IddDetails and assigns it to the Idd field.
func (o *AllresponsebodyInner) SetIdd(v IddDetails) {
	o.Idd = &v
}

// GetPostalCode returns the PostalCode field value if set, zero value otherwise.
func (o *AllresponsebodyInner) GetPostalCode() PostalCodeDetails {
	if o == nil || IsNil(o.PostalCode) {
		var ret PostalCodeDetails
		return ret
	}
	return *o.PostalCode
}

// GetPostalCodeOk returns a tuple with the PostalCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AllresponsebodyInner) GetPostalCodeOk() (*PostalCodeDetails, bool) {
	if o == nil || IsNil(o.PostalCode) {
		return nil, false
	}
	return o.PostalCode, true
}

// HasPostalCode returns a boolean if a field has been set.
func (o *AllresponsebodyInner) HasPostalCode() bool {
	if o != nil && !IsNil(o.PostalCode) {
		return true
	}

	return false
}

// SetPostalCode gets a reference to the given PostalCodeDetails and assigns it to the PostalCode field.
func (o *AllresponsebodyInner) SetPostalCode(v PostalCodeDetails) {
	o.PostalCode = &v
}

// GetLanguages returns the Languages field value if set, zero value otherwise.
func (o *AllresponsebodyInner) GetLanguages() map[string]string {
	if o == nil || IsNil(o.Languages) {
		var ret map[string]string
		return ret
	}
	return *o.Languages
}

// GetLanguagesOk returns a tuple with the Languages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AllresponsebodyInner) GetLanguagesOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Languages) {
		return nil, false
	}
	return o.Languages, true
}

// HasLanguages returns a boolean if a field has been set.
func (o *AllresponsebodyInner) HasLanguages() bool {
	if o != nil && !IsNil(o.Languages) {
		return true
	}

	return false
}

// SetLanguages gets a reference to the given map[string]string and assigns it to the Languages field.
func (o *AllresponsebodyInner) SetLanguages(v map[string]string) {
	o.Languages = &v
}

func (o AllresponsebodyInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AllresponsebodyInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Tld) {
		toSerialize["tld"] = o.Tld
	}
	if !IsNil(o.Cca2) {
		toSerialize["cca2"] = o.Cca2
	}
	if !IsNil(o.Cca3) {
		toSerialize["cca3"] = o.Cca3
	}
	if !IsNil(o.Ccn3) {
		toSerialize["ccn3"] = o.Ccn3
	}
	if !IsNil(o.Cioc) {
		toSerialize["cioc"] = o.Cioc
	}
	if !IsNil(o.Currencies) {
		toSerialize["currencies"] = o.Currencies
	}
	if !IsNil(o.Region) {
		toSerialize["region"] = o.Region
	}
	if !IsNil(o.Independent) {
		toSerialize["independent"] = o.Independent
	}
	if !IsNil(o.UnMember) {
		toSerialize["unMember"] = o.UnMember
	}
	if !IsNil(o.Capital) {
		toSerialize["capital"] = o.Capital
	}
	if !IsNil(o.Latlng) {
		toSerialize["latlng"] = o.Latlng
	}
	if !IsNil(o.Area) {
		toSerialize["area"] = o.Area
	}
	if !IsNil(o.Population) {
		toSerialize["population"] = o.Population
	}
	if !IsNil(o.Flags) {
		toSerialize["flags"] = o.Flags
	}
	if !IsNil(o.Flag) {
		toSerialize["flag"] = o.Flag
	}
	if !IsNil(o.Landlocked) {
		toSerialize["landlocked"] = o.Landlocked
	}
	if !IsNil(o.Borders) {
		toSerialize["borders"] = o.Borders
	}
	if !IsNil(o.Translations) {
		toSerialize["translations"] = o.Translations
	}
	if !IsNil(o.Demonyms) {
		toSerialize["demonyms"] = o.Demonyms
	}
	if !IsNil(o.Timezones) {
		toSerialize["timezones"] = o.Timezones
	}
	if !IsNil(o.Continents) {
		toSerialize["continents"] = o.Continents
	}
	if !IsNil(o.Fifa) {
		toSerialize["fifa"] = o.Fifa
	}
	if !IsNil(o.Car) {
		toSerialize["car"] = o.Car
	}
	if !IsNil(o.CoatOfArms) {
		toSerialize["coatOfArms"] = o.CoatOfArms
	}
	if !IsNil(o.StartOfWeek) {
		toSerialize["startOfWeek"] = o.StartOfWeek
	}
	if !IsNil(o.CapitalInfo) {
		toSerialize["capitalInfo"] = o.CapitalInfo
	}
	if !IsNil(o.Maps) {
		toSerialize["maps"] = o.Maps
	}
	if !IsNil(o.Gini) {
		toSerialize["gini"] = o.Gini
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Subregion) {
		toSerialize["subregion"] = o.Subregion
	}
	if !IsNil(o.AltSpellings) {
		toSerialize["altSpellings"] = o.AltSpellings
	}
	if !IsNil(o.Idd) {
		toSerialize["idd"] = o.Idd
	}
	if !IsNil(o.PostalCode) {
		toSerialize["postalCode"] = o.PostalCode
	}
	if !IsNil(o.Languages) {
		toSerialize["languages"] = o.Languages
	}
	return toSerialize, nil
}

type NullableAllresponsebodyInner struct {
	value *AllresponsebodyInner
	isSet bool
}

func (v NullableAllresponsebodyInner) Get() *AllresponsebodyInner {
	return v.value
}

func (v *NullableAllresponsebodyInner) Set(val *AllresponsebodyInner) {
	v.value = val
	v.isSet = true
}

func (v NullableAllresponsebodyInner) IsSet() bool {
	return v.isSet
}

func (v *NullableAllresponsebodyInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAllresponsebodyInner(val *AllresponsebodyInner) *NullableAllresponsebodyInner {
	return &NullableAllresponsebodyInner{value: val, isSet: true}
}

func (v NullableAllresponsebodyInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAllresponsebodyInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


