/*
REST Countries — Countries API (v5)

Read-only country data API. All endpoints are GET, JSON-only, and follow a JSON:API-like envelope: successful payloads sit under a top-level `data` key with `data.objects` (array of Country records) and `data.meta` (pagination block). Failures return an `errors` array of objects carrying a `message`. Authentication is a bearer API key. Spec written against https://restcountries.com/docs/countries (July 2026) and cross-checked against a live v5 record. 

API version: 5.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package restcountries

import (
	"encoding/json"
)

// checks if the CountryNumberFormat type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CountryNumberFormat{}

// CountryNumberFormat struct for CountryNumberFormat
type CountryNumberFormat struct {
	DecimalSeparator *string `json:"decimal_separator,omitempty"`
	ThousandsSeparator *string `json:"thousands_separator,omitempty"`
}

// NewCountryNumberFormat instantiates a new CountryNumberFormat object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCountryNumberFormat() *CountryNumberFormat {
	this := CountryNumberFormat{}
	return &this
}

// NewCountryNumberFormatWithDefaults instantiates a new CountryNumberFormat object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCountryNumberFormatWithDefaults() *CountryNumberFormat {
	this := CountryNumberFormat{}
	return &this
}

// GetDecimalSeparator returns the DecimalSeparator field value if set, zero value otherwise.
func (o *CountryNumberFormat) GetDecimalSeparator() string {
	if o == nil || IsNil(o.DecimalSeparator) {
		var ret string
		return ret
	}
	return *o.DecimalSeparator
}

// GetDecimalSeparatorOk returns a tuple with the DecimalSeparator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CountryNumberFormat) GetDecimalSeparatorOk() (*string, bool) {
	if o == nil || IsNil(o.DecimalSeparator) {
		return nil, false
	}
	return o.DecimalSeparator, true
}

// HasDecimalSeparator returns a boolean if a field has been set.
func (o *CountryNumberFormat) HasDecimalSeparator() bool {
	if o != nil && !IsNil(o.DecimalSeparator) {
		return true
	}

	return false
}

// SetDecimalSeparator gets a reference to the given string and assigns it to the DecimalSeparator field.
func (o *CountryNumberFormat) SetDecimalSeparator(v string) {
	o.DecimalSeparator = &v
}

// GetThousandsSeparator returns the ThousandsSeparator field value if set, zero value otherwise.
func (o *CountryNumberFormat) GetThousandsSeparator() string {
	if o == nil || IsNil(o.ThousandsSeparator) {
		var ret string
		return ret
	}
	return *o.ThousandsSeparator
}

// GetThousandsSeparatorOk returns a tuple with the ThousandsSeparator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CountryNumberFormat) GetThousandsSeparatorOk() (*string, bool) {
	if o == nil || IsNil(o.ThousandsSeparator) {
		return nil, false
	}
	return o.ThousandsSeparator, true
}

// HasThousandsSeparator returns a boolean if a field has been set.
func (o *CountryNumberFormat) HasThousandsSeparator() bool {
	if o != nil && !IsNil(o.ThousandsSeparator) {
		return true
	}

	return false
}

// SetThousandsSeparator gets a reference to the given string and assigns it to the ThousandsSeparator field.
func (o *CountryNumberFormat) SetThousandsSeparator(v string) {
	o.ThousandsSeparator = &v
}

func (o CountryNumberFormat) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CountryNumberFormat) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DecimalSeparator) {
		toSerialize["decimal_separator"] = o.DecimalSeparator
	}
	if !IsNil(o.ThousandsSeparator) {
		toSerialize["thousands_separator"] = o.ThousandsSeparator
	}
	return toSerialize, nil
}

type NullableCountryNumberFormat struct {
	value *CountryNumberFormat
	isSet bool
}

func (v NullableCountryNumberFormat) Get() *CountryNumberFormat {
	return v.value
}

func (v *NullableCountryNumberFormat) Set(val *CountryNumberFormat) {
	v.value = val
	v.isSet = true
}

func (v NullableCountryNumberFormat) IsSet() bool {
	return v.isSet
}

func (v *NullableCountryNumberFormat) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCountryNumberFormat(val *CountryNumberFormat) *NullableCountryNumberFormat {
	return &NullableCountryNumberFormat{value: val, isSet: true}
}

func (v NullableCountryNumberFormat) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCountryNumberFormat) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


