/*
REST Countries — Countries API (v5)

Read-only country data API. All endpoints are GET, JSON-only, and follow a JSON:API-like envelope: successful payloads sit under a top-level `data` key with `data.objects` (array of Country records) and `data.meta` (pagination block). Failures return an `errors` array of objects carrying a `message`. Authentication is a bearer API key. Spec written against https://restcountries.com/docs/countries (July 2026) and cross-checked against a live v5 record. 

API version: 5.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package restcountries

import (
	"encoding/json"
)

// checks if the CountryEconomy type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CountryEconomy{}

// CountryEconomy struct for CountryEconomy
type CountryEconomy struct {
	// Gini coefficient(s) keyed by reporting year.
	GiniCoefficient *map[string]float32 `json:"gini_coefficient,omitempty"`
}

// NewCountryEconomy instantiates a new CountryEconomy object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCountryEconomy() *CountryEconomy {
	this := CountryEconomy{}
	return &this
}

// NewCountryEconomyWithDefaults instantiates a new CountryEconomy object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCountryEconomyWithDefaults() *CountryEconomy {
	this := CountryEconomy{}
	return &this
}

// GetGiniCoefficient returns the GiniCoefficient field value if set, zero value otherwise.
func (o *CountryEconomy) GetGiniCoefficient() map[string]float32 {
	if o == nil || IsNil(o.GiniCoefficient) {
		var ret map[string]float32
		return ret
	}
	return *o.GiniCoefficient
}

// GetGiniCoefficientOk returns a tuple with the GiniCoefficient field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CountryEconomy) GetGiniCoefficientOk() (*map[string]float32, bool) {
	if o == nil || IsNil(o.GiniCoefficient) {
		return nil, false
	}
	return o.GiniCoefficient, true
}

// HasGiniCoefficient returns a boolean if a field has been set.
func (o *CountryEconomy) HasGiniCoefficient() bool {
	if o != nil && !IsNil(o.GiniCoefficient) {
		return true
	}

	return false
}

// SetGiniCoefficient gets a reference to the given map[string]float32 and assigns it to the GiniCoefficient field.
func (o *CountryEconomy) SetGiniCoefficient(v map[string]float32) {
	o.GiniCoefficient = &v
}

func (o CountryEconomy) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CountryEconomy) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.GiniCoefficient) {
		toSerialize["gini_coefficient"] = o.GiniCoefficient
	}
	return toSerialize, nil
}

type NullableCountryEconomy struct {
	value *CountryEconomy
	isSet bool
}

func (v NullableCountryEconomy) Get() *CountryEconomy {
	return v.value
}

func (v *NullableCountryEconomy) Set(val *CountryEconomy) {
	v.value = val
	v.isSet = true
}

func (v NullableCountryEconomy) IsSet() bool {
	return v.isSet
}

func (v *NullableCountryEconomy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCountryEconomy(val *CountryEconomy) *NullableCountryEconomy {
	return &NullableCountryEconomy{value: val, isSet: true}
}

func (v NullableCountryEconomy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCountryEconomy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


