/*
REST Countries — Countries API (v5)

Read-only country data API. All endpoints are GET, JSON-only, and follow a JSON:API-like envelope: successful payloads sit under a top-level `data` key with `data.objects` (array of Country records) and `data.meta` (pagination block). Failures return an `errors` array of objects carrying a `message`. Authentication is a bearer API key. Spec written against https://restcountries.com/docs/countries (July 2026) and cross-checked against a live v5 record. 

API version: 5.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package restcountries

import (
	"encoding/json"
)

// checks if the CountryParent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CountryParent{}

// CountryParent For dependent entities, the sovereign parent.
type CountryParent struct {
	Alpha2 *string `json:"alpha_2,omitempty"`
	Alpha3 *string `json:"alpha_3,omitempty"`
}

// NewCountryParent instantiates a new CountryParent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCountryParent() *CountryParent {
	this := CountryParent{}
	return &this
}

// NewCountryParentWithDefaults instantiates a new CountryParent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCountryParentWithDefaults() *CountryParent {
	this := CountryParent{}
	return &this
}

// GetAlpha2 returns the Alpha2 field value if set, zero value otherwise.
func (o *CountryParent) GetAlpha2() string {
	if o == nil || IsNil(o.Alpha2) {
		var ret string
		return ret
	}
	return *o.Alpha2
}

// GetAlpha2Ok returns a tuple with the Alpha2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CountryParent) GetAlpha2Ok() (*string, bool) {
	if o == nil || IsNil(o.Alpha2) {
		return nil, false
	}
	return o.Alpha2, true
}

// HasAlpha2 returns a boolean if a field has been set.
func (o *CountryParent) HasAlpha2() bool {
	if o != nil && !IsNil(o.Alpha2) {
		return true
	}

	return false
}

// SetAlpha2 gets a reference to the given string and assigns it to the Alpha2 field.
func (o *CountryParent) SetAlpha2(v string) {
	o.Alpha2 = &v
}

// GetAlpha3 returns the Alpha3 field value if set, zero value otherwise.
func (o *CountryParent) GetAlpha3() string {
	if o == nil || IsNil(o.Alpha3) {
		var ret string
		return ret
	}
	return *o.Alpha3
}

// GetAlpha3Ok returns a tuple with the Alpha3 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CountryParent) GetAlpha3Ok() (*string, bool) {
	if o == nil || IsNil(o.Alpha3) {
		return nil, false
	}
	return o.Alpha3, true
}

// HasAlpha3 returns a boolean if a field has been set.
func (o *CountryParent) HasAlpha3() bool {
	if o != nil && !IsNil(o.Alpha3) {
		return true
	}

	return false
}

// SetAlpha3 gets a reference to the given string and assigns it to the Alpha3 field.
func (o *CountryParent) SetAlpha3(v string) {
	o.Alpha3 = &v
}

func (o CountryParent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CountryParent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Alpha2) {
		toSerialize["alpha_2"] = o.Alpha2
	}
	if !IsNil(o.Alpha3) {
		toSerialize["alpha_3"] = o.Alpha3
	}
	return toSerialize, nil
}

type NullableCountryParent struct {
	value *CountryParent
	isSet bool
}

func (v NullableCountryParent) Get() *CountryParent {
	return v.value
}

func (v *NullableCountryParent) Set(val *CountryParent) {
	v.value = val
	v.isSet = true
}

func (v NullableCountryParent) IsSet() bool {
	return v.isSet
}

func (v *NullableCountryParent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCountryParent(val *CountryParent) *NullableCountryParent {
	return &NullableCountryParent{value: val, isSet: true}
}

func (v NullableCountryParent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCountryParent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


