/*
REST Countries — Countries API (v5)

Read-only country data API. All endpoints are GET, JSON-only, and follow a JSON:API-like envelope: successful payloads sit under a top-level `data` key with `data.objects` (array of Country records) and `data.meta` (pagination block). Failures return an `errors` array of objects carrying a `message`. Authentication is a bearer API key. Spec written against https://restcountries.com/docs/countries (July 2026) and cross-checked against a live v5 record. 

API version: 5.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package restcountries

import (
	"encoding/json"
)

// checks if the CountryListResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CountryListResponseData{}

// CountryListResponseData struct for CountryListResponseData
type CountryListResponseData struct {
	Objects []Country `json:"objects,omitempty"`
	Meta *ResponseMeta `json:"meta,omitempty"`
}

// NewCountryListResponseData instantiates a new CountryListResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCountryListResponseData() *CountryListResponseData {
	this := CountryListResponseData{}
	return &this
}

// NewCountryListResponseDataWithDefaults instantiates a new CountryListResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCountryListResponseDataWithDefaults() *CountryListResponseData {
	this := CountryListResponseData{}
	return &this
}

// GetObjects returns the Objects field value if set, zero value otherwise.
func (o *CountryListResponseData) GetObjects() []Country {
	if o == nil || IsNil(o.Objects) {
		var ret []Country
		return ret
	}
	return o.Objects
}

// GetObjectsOk returns a tuple with the Objects field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CountryListResponseData) GetObjectsOk() ([]Country, bool) {
	if o == nil || IsNil(o.Objects) {
		return nil, false
	}
	return o.Objects, true
}

// HasObjects returns a boolean if a field has been set.
func (o *CountryListResponseData) HasObjects() bool {
	if o != nil && !IsNil(o.Objects) {
		return true
	}

	return false
}

// SetObjects gets a reference to the given []Country and assigns it to the Objects field.
func (o *CountryListResponseData) SetObjects(v []Country) {
	o.Objects = v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *CountryListResponseData) GetMeta() ResponseMeta {
	if o == nil || IsNil(o.Meta) {
		var ret ResponseMeta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CountryListResponseData) GetMetaOk() (*ResponseMeta, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *CountryListResponseData) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given ResponseMeta and assigns it to the Meta field.
func (o *CountryListResponseData) SetMeta(v ResponseMeta) {
	o.Meta = &v
}

func (o CountryListResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CountryListResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Objects) {
		toSerialize["objects"] = o.Objects
	}
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	return toSerialize, nil
}

type NullableCountryListResponseData struct {
	value *CountryListResponseData
	isSet bool
}

func (v NullableCountryListResponseData) Get() *CountryListResponseData {
	return v.value
}

func (v *NullableCountryListResponseData) Set(val *CountryListResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableCountryListResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableCountryListResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCountryListResponseData(val *CountryListResponseData) *NullableCountryListResponseData {
	return &NullableCountryListResponseData{value: val, isSet: true}
}

func (v NullableCountryListResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCountryListResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


