/*
OpenAPI Example

This is an  OpenAPI specification for Rest Countries API.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the MapsDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MapsDetails{}

// MapsDetails struct for MapsDetails
type MapsDetails struct {
	GoogleMaps *string `json:"googleMaps,omitempty"`
	OpenStreetMaps *string `json:"openStreetMaps,omitempty"`
}

// NewMapsDetails instantiates a new MapsDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMapsDetails() *MapsDetails {
	this := MapsDetails{}
	return &this
}

// NewMapsDetailsWithDefaults instantiates a new MapsDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMapsDetailsWithDefaults() *MapsDetails {
	this := MapsDetails{}
	return &this
}

// GetGoogleMaps returns the GoogleMaps field value if set, zero value otherwise.
func (o *MapsDetails) GetGoogleMaps() string {
	if o == nil || IsNil(o.GoogleMaps) {
		var ret string
		return ret
	}
	return *o.GoogleMaps
}

// GetGoogleMapsOk returns a tuple with the GoogleMaps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MapsDetails) GetGoogleMapsOk() (*string, bool) {
	if o == nil || IsNil(o.GoogleMaps) {
		return nil, false
	}
	return o.GoogleMaps, true
}

// HasGoogleMaps returns a boolean if a field has been set.
func (o *MapsDetails) HasGoogleMaps() bool {
	if o != nil && !IsNil(o.GoogleMaps) {
		return true
	}

	return false
}

// SetGoogleMaps gets a reference to the given string and assigns it to the GoogleMaps field.
func (o *MapsDetails) SetGoogleMaps(v string) {
	o.GoogleMaps = &v
}

// GetOpenStreetMaps returns the OpenStreetMaps field value if set, zero value otherwise.
func (o *MapsDetails) GetOpenStreetMaps() string {
	if o == nil || IsNil(o.OpenStreetMaps) {
		var ret string
		return ret
	}
	return *o.OpenStreetMaps
}

// GetOpenStreetMapsOk returns a tuple with the OpenStreetMaps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MapsDetails) GetOpenStreetMapsOk() (*string, bool) {
	if o == nil || IsNil(o.OpenStreetMaps) {
		return nil, false
	}
	return o.OpenStreetMaps, true
}

// HasOpenStreetMaps returns a boolean if a field has been set.
func (o *MapsDetails) HasOpenStreetMaps() bool {
	if o != nil && !IsNil(o.OpenStreetMaps) {
		return true
	}

	return false
}

// SetOpenStreetMaps gets a reference to the given string and assigns it to the OpenStreetMaps field.
func (o *MapsDetails) SetOpenStreetMaps(v string) {
	o.OpenStreetMaps = &v
}

func (o MapsDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MapsDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.GoogleMaps) {
		toSerialize["googleMaps"] = o.GoogleMaps
	}
	if !IsNil(o.OpenStreetMaps) {
		toSerialize["openStreetMaps"] = o.OpenStreetMaps
	}
	return toSerialize, nil
}

type NullableMapsDetails struct {
	value *MapsDetails
	isSet bool
}

func (v NullableMapsDetails) Get() *MapsDetails {
	return v.value
}

func (v *NullableMapsDetails) Set(val *MapsDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableMapsDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableMapsDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMapsDetails(val *MapsDetails) *NullableMapsDetails {
	return &NullableMapsDetails{value: val, isSet: true}
}

func (v NullableMapsDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMapsDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


