/*
OpenAPI Example

Testing CountriesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	openapiclient "restcountries"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_openapi_CountriesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test CountriesAPIService GetAllCountries", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.CountriesAPI.GetAllCountries(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CountriesAPIService GetCountryByCapital", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var capital string

		resp, httpRes, err := apiClient.CountriesAPI.GetCountryByCapital(context.Background(), capital).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CountriesAPIService GetCountryByCode", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var code string

		resp, httpRes, err := apiClient.CountriesAPI.GetCountryByCode(context.Background(), code).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CountriesAPIService GetCountryByCurrency", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var currency string

		resp, httpRes, err := apiClient.CountriesAPI.GetCountryByCurrency(context.Background(), currency).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CountriesAPIService GetCountryByLanguage", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var language string

		resp, httpRes, err := apiClient.CountriesAPI.GetCountryByLanguage(context.Background(), language).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CountriesAPIService GetCountryByName", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var name string

		resp, httpRes, err := apiClient.CountriesAPI.GetCountryByName(context.Background(), name).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CountriesAPIService GetCountryByRegion", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var region string

		resp, httpRes, err := apiClient.CountriesAPI.GetCountryByRegion(context.Background(), region).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CountriesAPIService GetCountryBySubregion", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var subregion string

		resp, httpRes, err := apiClient.CountriesAPI.GetCountryBySubregion(context.Background(), subregion).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CountriesAPIService GetCountryByTranslation", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var translation string

		resp, httpRes, err := apiClient.CountriesAPI.GetCountryByTranslation(context.Background(), translation).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CountriesAPIService GetIndependentCountries", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.CountriesAPI.GetIndependentCountries(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
