/* tslint:disable */
/* eslint-disable */
/**
 * Countries Backend API
 * OpenAPI specification for the Gin countries backend. Country records are v5-shaped (proxied from REST Countries v5 and returned as a bare JSON array, envelope unwrapped by the backend).
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface Capital {
    'name'?: string;
    'coordinates'?: Coordinates;
    'attributes'?: CapitalAttributes;
}
/**
 * Role flags. Nesting under `attributes` verified against a live v5 record.
 */
export interface CapitalAttributes {
    'primary'?: boolean;
    'constitutional'?: boolean;
    'administrative'?: boolean;
    'executive'?: boolean;
    'legislative'?: boolean;
    'judicial'?: boolean;
}
export interface Classification {
    /**
     * Replaces v3.1\'s `independent` (verified against a live v5 record).
     */
    'sovereign'?: boolean;
    'un_member'?: boolean;
    'un_observer'?: boolean;
    'disputed'?: boolean;
    'dependency'?: boolean;
    'dependency_type'?: string;
    'iso_status'?: ClassificationIsoStatusEnum;
}

export const ClassificationIsoStatusEnum = {
    Official: 'official',
    UserAssigned: 'user_assigned',
} as const;

export type ClassificationIsoStatusEnum = typeof ClassificationIsoStatusEnum[keyof typeof ClassificationIsoStatusEnum];

export interface Codes {
    'alpha_2'?: string;
    'alpha_3'?: string;
    'ccn3'?: string;
    'fips'?: string;
    'gec'?: string;
    'cioc'?: string;
    'fifa'?: string;
}
export interface Coordinates {
    'lat'?: number;
    'lng'?: number;
}
/**
 * A country record. Every field is optional at the wire level because response_fields / response_fields_omit can project the object to any subset. 
 */
export interface Country {
    'names'?: Names;
    'capitals'?: Array<Capital>;
    /**
     * Keyed by ISO 639-3 language code.
     */
    'demonyms'?: { [key: string]: Demonym; };
    'codes'?: Codes;
    'flag'?: Flag;
    /**
     * Africa, Americas, Asia, Europe, Oceania.
     */
    'region'?: string;
    'subregion'?: string;
    'continents'?: Array<string>;
    'landlocked'?: boolean;
    /**
     * ISO alpha-3 codes of land-border neighbours.
     */
    'borders'?: Array<string>;
    'area'?: CountryArea;
    'coordinates'?: Coordinates;
    /**
     * UTC offsets observed (e.g. UTC+05:30).
     */
    'timezones'?: Array<string>;
    /**
     * Top-level integer (verified against a live v5 record). Dynamic, 4-hour sync.
     */
    'population'?: number;
    'economy'?: CountryEconomy;
    /**
     * Languages used in the country. `name` (English name) verified as a live lookup path; the identifier key names below follow the docs\' description (ISO 639 identifiers, BCP 47 tag, native name) and should be confirmed against one live record before relying on them (x-unverified). 
     */
    'languages'?: Array<Language>;
    /**
     * Officially supported currencies. `code` verified as a live lookup path; `name`/`symbol` follow convention and should be confirmed against one live record (x-unverified). 
     */
    'currencies'?: Array<Currency>;
    'calling_codes'?: Array<string>;
    'tlds'?: Array<string>;
    'cars'?: CountryCars;
    'postal_code'?: CountryPostalCode;
    'date'?: DateConventions;
    'number_format'?: CountryNumberFormat;
    'units'?: CountryUnits;
    'classification'?: Classification;
    'parent'?: CountryParent;
    'memberships'?: Memberships;
    /**
     * Dynamic field.
     */
    'government_type'?: string;
    /**
     * Premium dynamic field (Personal plans and above). On the free plan the array carries a single upgrade-notice object instead of leader records, so all leaf fields must stay optional. 
     */
    'leaders'?: Array<Leader>;
    'links'?: CountryLinks;
}
export interface CountryArea {
    'kilometers'?: number;
    'miles'?: number;
}
export interface CountryCars {
    'driving_side'?: CountryCarsDrivingSideEnum;
    'signs'?: Array<string>;
}

export const CountryCarsDrivingSideEnum = {
    Left: 'left',
    Right: 'right',
} as const;

export type CountryCarsDrivingSideEnum = typeof CountryCarsDrivingSideEnum[keyof typeof CountryCarsDrivingSideEnum];

export interface CountryEconomy {
    /**
     * Gini coefficient(s) keyed by reporting year.
     */
    'gini_coefficient'?: { [key: string]: number; };
}
export interface CountryLinks {
    'official'?: string;
    'wikipedia'?: string;
    'open_street_maps'?: string;
    'google_maps'?: string;
}
export interface CountryNumberFormat {
    'decimal_separator'?: string;
    'thousands_separator'?: string;
}
/**
 * For dependent entities, the sovereign parent.
 */
export interface CountryParent {
    'alpha_2'?: string;
    'alpha_3'?: string;
}
export interface CountryPostalCode {
    /**
     * Human-readable mask, `#` for digits (e.g. \"A#A
     */
    'format'?: string;
    'regex'?: string;
}
export interface CountryUnits {
    'measurement_system'?: CountryUnitsMeasurementSystemEnum;
    'temperature_scale'?: CountryUnitsTemperatureScaleEnum;
}

export const CountryUnitsMeasurementSystemEnum = {
    Metric: 'metric',
    Imperial: 'imperial',
} as const;

export type CountryUnitsMeasurementSystemEnum = typeof CountryUnitsMeasurementSystemEnum[keyof typeof CountryUnitsMeasurementSystemEnum];
export const CountryUnitsTemperatureScaleEnum = {
    Celsius: 'Celsius',
    Fahrenheit: 'Fahrenheit',
} as const;

export type CountryUnitsTemperatureScaleEnum = typeof CountryUnitsTemperatureScaleEnum[keyof typeof CountryUnitsTemperatureScaleEnum];

export interface Currency {
    /**
     * ISO 4217 code. Verified lookup path (currencies.code).
     */
    'code'?: string;
    /**
     * x-unverified key name.
     */
    'name'?: string;
    /**
     * x-unverified key name.
     */
    'symbol'?: string;
}
export interface DateConventions {
    'start_of_week'?: string;
    'academic_year_start'?: MonthDay;
    'fiscal_year_start'?: DateConventionsFiscalYearStart;
}
export interface DateConventionsFiscalYearStart {
    'government'?: MonthDay;
    'corporate'?: DateConventionsFiscalYearStartCorporate;
    'personal'?: MonthDay;
}
export interface DateConventionsFiscalYearStartCorporate {
    'month'?: number;
    'day'?: number;
    'basis'?: DateConventionsFiscalYearStartCorporateBasisEnum;
}

export const DateConventionsFiscalYearStartCorporateBasisEnum = {
    Mandated: 'mandated',
    Default: 'default',
    Convention: 'convention',
} as const;

export type DateConventionsFiscalYearStartCorporateBasisEnum = typeof DateConventionsFiscalYearStartCorporateBasisEnum[keyof typeof DateConventionsFiscalYearStartCorporateBasisEnum];

export interface Demonym {
    'm'?: string;
    'f'?: string;
}
export interface ErrorResponse {
    'errors'?: Array<ErrorResponseErrorsInner>;
}
export interface ErrorResponseErrorsInner {
    'message'?: string;
}
export interface Flag {
    'emoji'?: string;
    'unicode'?: string;
    'html_entity'?: string;
    'url_png'?: string;
    'url_svg'?: string;
    'description'?: string;
    'colors'?: FlagColors;
}
export interface FlagColors {
    'dominant'?: string;
    'prominent'?: string;
    'palette'?: Array<FlagColorsPaletteInner>;
    'swatches'?: FlagColorsSwatches;
}
export interface FlagColorsPaletteInner {
    'hex'?: string;
    'proportion'?: number;
}
/**
 * All six roles always present; null when no matching color.
 */
export interface FlagColorsSwatches {
    'vibrant'?: string | null;
    'muted'?: string | null;
    'dark_vibrant'?: string | null;
    'dark_muted'?: string | null;
    'light_vibrant'?: string | null;
    'light_muted'?: string | null;
}
export interface Language {
    /**
     * English name. Verified lookup path (languages.name).
     */
    'name'?: string;
    /**
     * x-unverified key name.
     */
    'native_name'?: string;
    /**
     * x-unverified key name.
     */
    'bcp_47'?: string;
    /**
     * x-unverified key name.
     */
    'iso_639_1'?: string;
    /**
     * x-unverified key name.
     */
    'iso_639_3'?: string;
}
/**
 * Premium field. Per docs each leader includes assets, attributes, links, name, and title; exact sub-shapes are x-unverified.
 */
export interface Leader {
    'name'?: string;
    'title'?: string;
    'assets'?: { [key: string]: any; };
    'attributes'?: { [key: string]: any; };
    'links'?: { [key: string]: any; };
}
export interface Memberships {
    'un'?: boolean;
    'eu'?: boolean;
    'eurozone'?: boolean;
    'schengen'?: boolean;
    'nato'?: boolean;
    'commonwealth'?: boolean;
    'oecd'?: boolean;
    'g7'?: boolean;
    'g20'?: boolean;
    'brics'?: boolean;
    'opec'?: boolean;
    'african_union'?: boolean;
    'asean'?: boolean;
    'arab_league'?: boolean;
}
export interface MonthDay {
    'month'?: number;
    'day'?: number;
}
export interface NameForms {
    'common'?: string;
    'official'?: string;
}
export interface Names {
    'common'?: string;
    'official'?: string;
    'alternates'?: Array<string>;
    /**
     * Keyed by ISO 639-3 language code.
     */
    'native'?: { [key: string]: NameForms; };
    /**
     * Keyed by ISO 639-3 language code. Heavy branch; consider response_fields_omit=names.translations.
     */
    'translations'?: { [key: string]: NameForms; };
}

/**
 * CountriesApi - axios parameter creator
 */
export const CountriesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Returns a simple example response.
         * @summary GET endpoint for retrieving all countries
         * @param {Array<string>} fields Comma-separated list of v5 dot-path fields to include in the response (forwarded upstream as response_fields)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllCountries: async (fields: Array<string>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'fields' is not null or undefined
            assertParamExists('getAllCountries', 'fields', fields)
            const localVarPath = `/all`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (fields) {
                localVarQueryParameter['fields'] = fields.join(COLLECTION_FORMATS.csv);
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Search by capital city name
         * @param {string} capital The capital city name to search for
         * @param {Array<string>} [fields] Comma-separated list of v5 dot-path fields to include in the response (forwarded upstream as response_fields)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCountryByCapital: async (capital: string, fields?: Array<string>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'capital' is not null or undefined
            assertParamExists('getCountryByCapital', 'capital', capital)
            const localVarPath = `/capital/{capital}`
                .replace('{capital}', encodeURIComponent(String(capital)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (fields) {
                localVarQueryParameter['fields'] = fields.join(COLLECTION_FORMATS.csv);
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Search by country code. It can be the 2-letter or 3-letter code
         * @param {string} code The country code to search ,for example for moldova 2-letter code i.e cca2  &#x3D; MD, 3-letter code i.e cca3 and cioc&#x3D; MDA, numeric code  i.e ccn3&#x3D;498
         * @param {Array<string>} [fields] Comma-separated list of v5 dot-path fields to include in the response (forwarded upstream as response_fields)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCountryByCode: async (code: string, fields?: Array<string>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'code' is not null or undefined
            assertParamExists('getCountryByCode', 'code', code)
            const localVarPath = `/alpha/{code}`
                .replace('{code}', encodeURIComponent(String(code)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (fields) {
                localVarQueryParameter['fields'] = fields.join(COLLECTION_FORMATS.csv);
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Search by currency code
         * @param {string} currency The currency code to search for
         * @param {Array<string>} [fields] Comma-separated list of v5 dot-path fields to include in the response (forwarded upstream as response_fields)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCountryByCurrency: async (currency: string, fields?: Array<string>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'currency' is not null or undefined
            assertParamExists('getCountryByCurrency', 'currency', currency)
            const localVarPath = `/currency/{currency}`
                .replace('{currency}', encodeURIComponent(String(currency)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (fields) {
                localVarQueryParameter['fields'] = fields.join(COLLECTION_FORMATS.csv);
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Search by language code
         * @param {string} language The language code to search for
         * @param {Array<string>} [fields] Comma-separated list of v5 dot-path fields to include in the response (forwarded upstream as response_fields)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCountryByLanguage: async (language: string, fields?: Array<string>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'language' is not null or undefined
            assertParamExists('getCountryByLanguage', 'language', language)
            const localVarPath = `/lang/{language}`
                .replace('{language}', encodeURIComponent(String(language)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (fields) {
                localVarQueryParameter['fields'] = fields.join(COLLECTION_FORMATS.csv);
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Search by country name. If you want to get an exact match, use the next endpoint. It can be the common or official value
         * @param {string} name The name of the country to search for
         * @param {Array<string>} [fields] Comma-separated list of v5 dot-path fields to include in the response (forwarded upstream as response_fields)
         * @param {boolean} [fullText] Whether to perform a full-text search
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCountryByName: async (name: string, fields?: Array<string>, fullText?: boolean, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'name' is not null or undefined
            assertParamExists('getCountryByName', 'name', name)
            const localVarPath = `/name/{name}`
                .replace('{name}', encodeURIComponent(String(name)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (fields) {
                localVarQueryParameter['fields'] = fields.join(COLLECTION_FORMATS.csv);
            }

            if (fullText !== undefined) {
                localVarQueryParameter['fullText'] = fullText;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Search by region name
         * @param {string} region The region name to search for
         * @param {Array<string>} [fields] Comma-separated list of v5 dot-path fields to include in the response (forwarded upstream as response_fields)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCountryByRegion: async (region: string, fields?: Array<string>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'region' is not null or undefined
            assertParamExists('getCountryByRegion', 'region', region)
            const localVarPath = `/region/{region}`
                .replace('{region}', encodeURIComponent(String(region)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (fields) {
                localVarQueryParameter['fields'] = fields.join(COLLECTION_FORMATS.csv);
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Search by subregion name
         * @param {string} subregion The subregion name to search for
         * @param {Array<string>} [fields] Comma-separated list of v5 dot-path fields to include in the response (forwarded upstream as response_fields)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCountryBySubregion: async (subregion: string, fields?: Array<string>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'subregion' is not null or undefined
            assertParamExists('getCountryBySubregion', 'subregion', subregion)
            const localVarPath = `/subregion/{subregion}`
                .replace('{subregion}', encodeURIComponent(String(subregion)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (fields) {
                localVarQueryParameter['fields'] = fields.join(COLLECTION_FORMATS.csv);
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Search by translation name
         * @param {string} translation The translation name to search for
         * @param {Array<string>} [fields] Comma-separated list of v5 dot-path fields to include in the response (forwarded upstream as response_fields)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCountryByTranslation: async (translation: string, fields?: Array<string>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'translation' is not null or undefined
            assertParamExists('getCountryByTranslation', 'translation', translation)
            const localVarPath = `/translation/{translation}`
                .replace('{translation}', encodeURIComponent(String(translation)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (fields) {
                localVarQueryParameter['fields'] = fields.join(COLLECTION_FORMATS.csv);
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get sovereign (independent) countries
         * @param {boolean} status Sovereignty status to filter by (maps to v5 classification.sovereign)
         * @param {Array<string>} [fields] Comma-separated list of v5 dot-path fields to include in the response (forwarded upstream as response_fields)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getIndependentCountries: async (status: boolean, fields?: Array<string>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'status' is not null or undefined
            assertParamExists('getIndependentCountries', 'status', status)
            const localVarPath = `/independent`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (fields) {
                localVarQueryParameter['fields'] = fields.join(COLLECTION_FORMATS.csv);
            }

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CountriesApi - functional programming interface
 */
export const CountriesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CountriesApiAxiosParamCreator(configuration)
    return {
        /**
         * Returns a simple example response.
         * @summary GET endpoint for retrieving all countries
         * @param {Array<string>} fields Comma-separated list of v5 dot-path fields to include in the response (forwarded upstream as response_fields)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllCountries(fields: Array<string>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Country>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllCountries(fields, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CountriesApi.getAllCountries']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Search by capital city name
         * @param {string} capital The capital city name to search for
         * @param {Array<string>} [fields] Comma-separated list of v5 dot-path fields to include in the response (forwarded upstream as response_fields)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCountryByCapital(capital: string, fields?: Array<string>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Country>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCountryByCapital(capital, fields, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CountriesApi.getCountryByCapital']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Search by country code. It can be the 2-letter or 3-letter code
         * @param {string} code The country code to search ,for example for moldova 2-letter code i.e cca2  &#x3D; MD, 3-letter code i.e cca3 and cioc&#x3D; MDA, numeric code  i.e ccn3&#x3D;498
         * @param {Array<string>} [fields] Comma-separated list of v5 dot-path fields to include in the response (forwarded upstream as response_fields)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCountryByCode(code: string, fields?: Array<string>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Country>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCountryByCode(code, fields, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CountriesApi.getCountryByCode']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Search by currency code
         * @param {string} currency The currency code to search for
         * @param {Array<string>} [fields] Comma-separated list of v5 dot-path fields to include in the response (forwarded upstream as response_fields)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCountryByCurrency(currency: string, fields?: Array<string>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Country>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCountryByCurrency(currency, fields, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CountriesApi.getCountryByCurrency']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Search by language code
         * @param {string} language The language code to search for
         * @param {Array<string>} [fields] Comma-separated list of v5 dot-path fields to include in the response (forwarded upstream as response_fields)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCountryByLanguage(language: string, fields?: Array<string>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Country>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCountryByLanguage(language, fields, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CountriesApi.getCountryByLanguage']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Search by country name. If you want to get an exact match, use the next endpoint. It can be the common or official value
         * @param {string} name The name of the country to search for
         * @param {Array<string>} [fields] Comma-separated list of v5 dot-path fields to include in the response (forwarded upstream as response_fields)
         * @param {boolean} [fullText] Whether to perform a full-text search
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCountryByName(name: string, fields?: Array<string>, fullText?: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Country>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCountryByName(name, fields, fullText, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CountriesApi.getCountryByName']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Search by region name
         * @param {string} region The region name to search for
         * @param {Array<string>} [fields] Comma-separated list of v5 dot-path fields to include in the response (forwarded upstream as response_fields)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCountryByRegion(region: string, fields?: Array<string>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Country>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCountryByRegion(region, fields, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CountriesApi.getCountryByRegion']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Search by subregion name
         * @param {string} subregion The subregion name to search for
         * @param {Array<string>} [fields] Comma-separated list of v5 dot-path fields to include in the response (forwarded upstream as response_fields)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCountryBySubregion(subregion: string, fields?: Array<string>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Country>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCountryBySubregion(subregion, fields, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CountriesApi.getCountryBySubregion']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Search by translation name
         * @param {string} translation The translation name to search for
         * @param {Array<string>} [fields] Comma-separated list of v5 dot-path fields to include in the response (forwarded upstream as response_fields)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCountryByTranslation(translation: string, fields?: Array<string>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Country>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCountryByTranslation(translation, fields, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CountriesApi.getCountryByTranslation']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get sovereign (independent) countries
         * @param {boolean} status Sovereignty status to filter by (maps to v5 classification.sovereign)
         * @param {Array<string>} [fields] Comma-separated list of v5 dot-path fields to include in the response (forwarded upstream as response_fields)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getIndependentCountries(status: boolean, fields?: Array<string>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Country>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getIndependentCountries(status, fields, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CountriesApi.getIndependentCountries']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CountriesApi - factory interface
 */
export const CountriesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CountriesApiFp(configuration)
    return {
        /**
         * Returns a simple example response.
         * @summary GET endpoint for retrieving all countries
         * @param {Array<string>} fields Comma-separated list of v5 dot-path fields to include in the response (forwarded upstream as response_fields)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllCountries(fields: Array<string>, options?: RawAxiosRequestConfig): AxiosPromise<Array<Country>> {
            return localVarFp.getAllCountries(fields, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Search by capital city name
         * @param {string} capital The capital city name to search for
         * @param {Array<string>} [fields] Comma-separated list of v5 dot-path fields to include in the response (forwarded upstream as response_fields)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCountryByCapital(capital: string, fields?: Array<string>, options?: RawAxiosRequestConfig): AxiosPromise<Array<Country>> {
            return localVarFp.getCountryByCapital(capital, fields, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Search by country code. It can be the 2-letter or 3-letter code
         * @param {string} code The country code to search ,for example for moldova 2-letter code i.e cca2  &#x3D; MD, 3-letter code i.e cca3 and cioc&#x3D; MDA, numeric code  i.e ccn3&#x3D;498
         * @param {Array<string>} [fields] Comma-separated list of v5 dot-path fields to include in the response (forwarded upstream as response_fields)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCountryByCode(code: string, fields?: Array<string>, options?: RawAxiosRequestConfig): AxiosPromise<Array<Country>> {
            return localVarFp.getCountryByCode(code, fields, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Search by currency code
         * @param {string} currency The currency code to search for
         * @param {Array<string>} [fields] Comma-separated list of v5 dot-path fields to include in the response (forwarded upstream as response_fields)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCountryByCurrency(currency: string, fields?: Array<string>, options?: RawAxiosRequestConfig): AxiosPromise<Array<Country>> {
            return localVarFp.getCountryByCurrency(currency, fields, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Search by language code
         * @param {string} language The language code to search for
         * @param {Array<string>} [fields] Comma-separated list of v5 dot-path fields to include in the response (forwarded upstream as response_fields)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCountryByLanguage(language: string, fields?: Array<string>, options?: RawAxiosRequestConfig): AxiosPromise<Array<Country>> {
            return localVarFp.getCountryByLanguage(language, fields, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Search by country name. If you want to get an exact match, use the next endpoint. It can be the common or official value
         * @param {string} name The name of the country to search for
         * @param {Array<string>} [fields] Comma-separated list of v5 dot-path fields to include in the response (forwarded upstream as response_fields)
         * @param {boolean} [fullText] Whether to perform a full-text search
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCountryByName(name: string, fields?: Array<string>, fullText?: boolean, options?: RawAxiosRequestConfig): AxiosPromise<Array<Country>> {
            return localVarFp.getCountryByName(name, fields, fullText, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Search by region name
         * @param {string} region The region name to search for
         * @param {Array<string>} [fields] Comma-separated list of v5 dot-path fields to include in the response (forwarded upstream as response_fields)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCountryByRegion(region: string, fields?: Array<string>, options?: RawAxiosRequestConfig): AxiosPromise<Array<Country>> {
            return localVarFp.getCountryByRegion(region, fields, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Search by subregion name
         * @param {string} subregion The subregion name to search for
         * @param {Array<string>} [fields] Comma-separated list of v5 dot-path fields to include in the response (forwarded upstream as response_fields)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCountryBySubregion(subregion: string, fields?: Array<string>, options?: RawAxiosRequestConfig): AxiosPromise<Array<Country>> {
            return localVarFp.getCountryBySubregion(subregion, fields, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Search by translation name
         * @param {string} translation The translation name to search for
         * @param {Array<string>} [fields] Comma-separated list of v5 dot-path fields to include in the response (forwarded upstream as response_fields)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCountryByTranslation(translation: string, fields?: Array<string>, options?: RawAxiosRequestConfig): AxiosPromise<Array<Country>> {
            return localVarFp.getCountryByTranslation(translation, fields, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get sovereign (independent) countries
         * @param {boolean} status Sovereignty status to filter by (maps to v5 classification.sovereign)
         * @param {Array<string>} [fields] Comma-separated list of v5 dot-path fields to include in the response (forwarded upstream as response_fields)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getIndependentCountries(status: boolean, fields?: Array<string>, options?: RawAxiosRequestConfig): AxiosPromise<Array<Country>> {
            return localVarFp.getIndependentCountries(status, fields, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CountriesApi - object-oriented interface
 */
export class CountriesApi extends BaseAPI {
    /**
     * Returns a simple example response.
     * @summary GET endpoint for retrieving all countries
     * @param {Array<string>} fields Comma-separated list of v5 dot-path fields to include in the response (forwarded upstream as response_fields)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAllCountries(fields: Array<string>, options?: RawAxiosRequestConfig) {
        return CountriesApiFp(this.configuration).getAllCountries(fields, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Search by capital city name
     * @param {string} capital The capital city name to search for
     * @param {Array<string>} [fields] Comma-separated list of v5 dot-path fields to include in the response (forwarded upstream as response_fields)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getCountryByCapital(capital: string, fields?: Array<string>, options?: RawAxiosRequestConfig) {
        return CountriesApiFp(this.configuration).getCountryByCapital(capital, fields, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Search by country code. It can be the 2-letter or 3-letter code
     * @param {string} code The country code to search ,for example for moldova 2-letter code i.e cca2  &#x3D; MD, 3-letter code i.e cca3 and cioc&#x3D; MDA, numeric code  i.e ccn3&#x3D;498
     * @param {Array<string>} [fields] Comma-separated list of v5 dot-path fields to include in the response (forwarded upstream as response_fields)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getCountryByCode(code: string, fields?: Array<string>, options?: RawAxiosRequestConfig) {
        return CountriesApiFp(this.configuration).getCountryByCode(code, fields, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Search by currency code
     * @param {string} currency The currency code to search for
     * @param {Array<string>} [fields] Comma-separated list of v5 dot-path fields to include in the response (forwarded upstream as response_fields)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getCountryByCurrency(currency: string, fields?: Array<string>, options?: RawAxiosRequestConfig) {
        return CountriesApiFp(this.configuration).getCountryByCurrency(currency, fields, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Search by language code
     * @param {string} language The language code to search for
     * @param {Array<string>} [fields] Comma-separated list of v5 dot-path fields to include in the response (forwarded upstream as response_fields)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getCountryByLanguage(language: string, fields?: Array<string>, options?: RawAxiosRequestConfig) {
        return CountriesApiFp(this.configuration).getCountryByLanguage(language, fields, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Search by country name. If you want to get an exact match, use the next endpoint. It can be the common or official value
     * @param {string} name The name of the country to search for
     * @param {Array<string>} [fields] Comma-separated list of v5 dot-path fields to include in the response (forwarded upstream as response_fields)
     * @param {boolean} [fullText] Whether to perform a full-text search
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getCountryByName(name: string, fields?: Array<string>, fullText?: boolean, options?: RawAxiosRequestConfig) {
        return CountriesApiFp(this.configuration).getCountryByName(name, fields, fullText, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Search by region name
     * @param {string} region The region name to search for
     * @param {Array<string>} [fields] Comma-separated list of v5 dot-path fields to include in the response (forwarded upstream as response_fields)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getCountryByRegion(region: string, fields?: Array<string>, options?: RawAxiosRequestConfig) {
        return CountriesApiFp(this.configuration).getCountryByRegion(region, fields, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Search by subregion name
     * @param {string} subregion The subregion name to search for
     * @param {Array<string>} [fields] Comma-separated list of v5 dot-path fields to include in the response (forwarded upstream as response_fields)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getCountryBySubregion(subregion: string, fields?: Array<string>, options?: RawAxiosRequestConfig) {
        return CountriesApiFp(this.configuration).getCountryBySubregion(subregion, fields, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Search by translation name
     * @param {string} translation The translation name to search for
     * @param {Array<string>} [fields] Comma-separated list of v5 dot-path fields to include in the response (forwarded upstream as response_fields)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getCountryByTranslation(translation: string, fields?: Array<string>, options?: RawAxiosRequestConfig) {
        return CountriesApiFp(this.configuration).getCountryByTranslation(translation, fields, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get sovereign (independent) countries
     * @param {boolean} status Sovereignty status to filter by (maps to v5 classification.sovereign)
     * @param {Array<string>} [fields] Comma-separated list of v5 dot-path fields to include in the response (forwarded upstream as response_fields)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getIndependentCountries(status: boolean, fields?: Array<string>, options?: RawAxiosRequestConfig) {
        return CountriesApiFp(this.configuration).getIndependentCountries(status, fields, options).then((request) => request(this.axios, this.basePath));
    }
}



