/* tslint:disable */
/* eslint-disable */
/**
 * Countries Backend API
 * OpenAPI specification for the Gin countries backend. Country records are v5-shaped (proxied from REST Countries v5 and returned as a bare JSON array, envelope unwrapped by the backend).
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

